GoogleContainerTools/jib

README.md
Add a note to not use the plugin yet, since it is not released.
Upon release, this change should be reverted.
=> Update README.md prior to release.

jib-maven-plugin/pom.xml
=> Release v0.1.0

jib-maven-plugin/pom.xml
Necessary for Sonatype.
Moved tag `v0.1.0` to point to this release. (35c0b7d)
=> Adds developers and SCM to pom.xml.

CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildAndCacheApplicationLayersStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildImageSteps.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/SourceFilesConfiguration.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/BuildImageStepsTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/TestSourceFilesConfiguration.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/LayerBuilderTest.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSourceFilesConfiguration.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSourceFilesConfigurationTest.java
=> Changes all extraction paths to use Unix-style path string.

README.md
In case people were wondering.
=> Adds note about running a local Docker registry.

CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java
=> Fixes long file names.

jib-maven-plugin/pom.xml
=> Release v0.1.1

jib-maven-plugin/pom.xml
=> Release v0.1.2

CHANGELOG.md, README.md
To merge after `v0.1.2` is released.
=>  Updates README and CHANGELOG for v0.1.2.

CONTRIBUTING.md, jib-maven-plugin/pom.xml
=> Removes fmt:format from validate phase

jib-maven-plugin/pom.xml
=> Release 0.1.3

jib-maven-plugin/pom.xml
=> Release v0.1.4

jib-core/build.gradle, jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheReader.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/DescriptorDigest.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPuller.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/TestSourceFilesConfiguration.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheReaderTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/LayerBuilderTest.java, jib-maven-plugin/pom.xml, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSourceFilesConfiguration.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIT.java
https://github.com/google/error-prone
http://errorprone.info/docs/installation
Gives us better compile-time checks.
This PR also fixes everything that error-prone caught.
=> Adds error-prone to compile checks.

jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheWriter.java
=> Fixes CacheWriter#writeLayer could throw FileAlreadyExistsException.

README.md
=> Adds link to jib-users forum and gitter.

jib-core/src/integration-test/java/com/google/cloud/tools/jib/Command.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildImageStepsIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIT.java
=> Removes use of Runtime.exec.

jib-maven-plugin/pom.xml
=> Adds fmt:check to validate phase

README.md
=> Adds FAQ about ImagePullBackoff.

jib-maven-plugin/pom.xml
=> Release v0.1.5

jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/DirectoryWalker.java
=> Removes UncheckedIOException hack in DirectoryWalker.

CHANGELOG.md
=> Updates CHANGELOG to reflect changes in v0.1.4 and v0.1.5.

README.md
Fixes #139 
After release v0.1.6 #176.
=> Adds instructions for pushing to Docker Hub Registry to README.

jib-maven-plugin/pom.xml
=> Release v0.1.6

CHANGELOG.md, README.md
=> Updates README.md with useOnlyProjectCache configuration.

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
=> Fix tag backslash error message

jib-gradle-plugin/build.gradle
Last commit tagged with `v0.1.0-gradle`.
Fixes #191
=> Release jib-gradle-plugin 0.1.0

README.md
=> Adds FAQ about setting JVM flags when running image.

proposals/README.md
All future design documents and proposals will be added/discussed here.
=> Adds directory for proposals.

CONTRIBUTING.md
=> Adds instructions for running jib-gradle-plugin tests to CONTRIBUTING.

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
=> Add empty task/goal for building to docker daemon

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
=> Moves Maven Settings credentials retrieval to separate class.

jib-maven-plugin/pom.xml
With workaround from https://github.com/spring-projects/spring-boot/issues/6254#issuecomment-307151464
=> Fixes Maven integration tests.

jib-maven-plugin/pom.xml, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
Regards comment https://github.com/GoogleContainerTools/jib/pull/272#pullrequestreview-120249681 @elharo
=>  Changes integration tests to end with IntegrationTest.

CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
Fixes #283
Will release as v0.1.7
=>  Removes unnecessary throw for missing entrypoint.

jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildConfiguration.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/ProjectProperties.java
Also a bit more cleanup in the tasks. Part of #262.
=> Reduce duplicate code between BuildDockerMojo and BuildImageMojo

jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildDockerSteps.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildImageSteps.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/FinalizingStep.java
=> Moves step for Finalizing message to separate class.

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
=> Adds command line option for setting target image.

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildTarballAndLoadDockerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageToTarballTranslator.java, jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplateMapper.java, jib-core/src/test/java/com/google/cloud/tools/jib/docker/ImageToTarballTranslatorTest.java
=> Refactors out ImageToTarballTranslator.

jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
This is causing our macos CI builds to fail.
=> Ignores InsecureRecursiveDeleteException.

jib-gradle-plugin/src/integration-test/resources/projects/empty/build.gradle, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
=> Fixes Jib task dependency on classes.

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
=> Renames dockerContext goal/task.

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ImageConfiguration.java
=> Fix gradle task annotation warnings

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
=> Fix registry credential retrieval order

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
Will release `v0.9.1` after this.
=> Updates CHANGELOG with issue #401.

.github/ISSUE_TEMPLATE.md
=> Add section for gradle plugin to issue template

jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticators.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> Remove unused 'throws MalformedURLException'

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Adds compile to Maven one-liner and fixes project link.

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
Just some commits that may be useful for readers.
=> Updates CHANGELOG.

jib-core/build.gradle, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml
So that any server-side usage stats are not muddled with automated tests.
=> Disables UserAgent sending during integration tests.

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
This is originally from #407. This does not change any functionality. This PR can be merged while #407 is awaiting review.
=> Adds RegistryEndpointCallerTest.

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
Good for if users run into issues like #447
=> Adds helpful suggestion for if 'classes' task not found on project.

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/MainClassFinder.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
=> Log important messages at lifecycle level

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
=> Make JibExtension nested getters public

jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/FileOperations.java, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleSourceFilesConfiguration.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleSourceFilesConfigurationTest.java
This regards #457. It might be enough to fix the issue, or at least help with fixing the issue.
=>  Changes GradleSourceFilesConfiguration to warn instead of error when classes not found.

jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
=> Fixes broken JibPluginIntegrationTest.

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/BuildDockerTaskTest.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoTest.java
Fixes #444.
Most of the changes here are just adding tests.
=> Inform user of docker tag configuration

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildStepsRunner.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestions.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/BuildStepsRunnerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestionsTest.java
This was a duplicate message that was introduced in #472
=> Replaces HelpfulSuggestions#forCacheNeedsClean with #forCacheMetadataCorrupted.

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildTarballAndLoadDockerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/FinalizingStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
These are TODOs that have either already been completed or aren't important enough to follow through with.
=> Remove irrelevant todos

README.md
It probably makes more sense than "native".
=> Changes wording "native" to "daemonless".

jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobChecker.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPuller.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPuller.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointRequestProperties.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobCheckerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPullerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPusherTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPullerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
Getting an easy TODO out of the way
=> Rename RegistryEndpointProperties to RegistryEndpointRequestProperties

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Fixes #353
Preview at: https://github.com/GoogleContainerTools/jib/tree/coollog-patch-2/jib-maven-plugin
=> Adds dockerBuild to quickstart.

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildTarballAndLoadDockerStep.java
=> Add log message for loading to docker daemon

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> RegistryAuthenticator handle basic, case insensitive (#539)

README.md, examples/helloworld/build.gradle, examples/helloworld/pom.xml, jib-gradle-plugin/README.md, jib-maven-plugin/README.md
To merge once v0.9.4 is released.
=> Updates version to v0.9.4.

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> Make bearer authentication matching case insensitve

CONTRIBUTING.md
This should help people with running integration tests better.
=> Updates CONTRIBUTING with notice about integration testing.

README.md
For more details on how Jib works.
=> Adds link to blog post in README.

jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> Use repository for missing service in 'bearer' auth challenge

README.md
Preview at: https://github.com/GoogleContainerTools/jib/tree/coollog-patch-1
=> Adds twitter badge for easy sharing.

README.md
Preview at: https://github.com/GoogleContainerTools/jib/tree/coollog-patch-2
=> Adds ways to get involved.

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
This will help guide readers to the information they need and declutter the README so that the quickstart is easier to see.
=>  Changes Upcoming Features section to be more sustainable.

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java, jib-gradle-plugin/src/integration-test/resources/projects/simple/build.gradle, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
=> Add useCurrentTimestamp to gradle plugin

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java, jib-maven-plugin/src/test/resources/projects/simple/pom.xml
=> Add useCurrentTimestamp to maven plugin

jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplateTest.java, jib-core/src/test/resources/json/dockerconfig.json
=> Look up cred helper additionally with possible suffixes

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
=> Change jib.dockerDir to jib.targetDir in maven plugin for consistency

docs/faq.md
=> Update FAQ with new features, how to run image, and how to parameterize

jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildConfiguration.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/BuildConfigurationTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
Preparation for #643.
Just renaming and updating Javadocs. No changes in the business logic.
=> Rename fields and methods / update Javadocs

CONTRIBUTING.md, README.md, examples/helloworld/build.gradle, examples/helloworld/pom.xml, jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Update versions to 0.9.7

.github/PULL_REQUEST_TEMPLATE.md, jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java, jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageToTarballTranslator.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java
=> Simplify TarStreamBuilder

jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
=> Make Error Prone happy

jib-core/src/main/java/com/google/cloud/tools/jib/blob/StringBlob.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
=> Throw correct exception depending on whether credentials were sent

jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheWriter.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheWriterTest.java
=> Do not overwrite existing layer TAR

jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildStepsRunner.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/BuildStepsRunnerTest.java
=>  Move image-related getters in BuildConfiguration to ImageConfiguration

jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/DirectoryWalker.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- `pathFilter` is not `@Nullable`.
- We are trying all possible registries, including the original one.
=> Minor fixes

jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
To fix the failing integration test (https://github.com/GoogleContainerTools/jib/pull/739#issuecomment-409288473). The reason the empty project is still failing is probably because it doesn't actually build any layers the first time and the second time, meaning that any difference in run times is just by chance.
=> Disables second run time check for empty integration test project.

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
=> Log detailed message

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildStepsRunner.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/BuildStepsRunnerTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Fix target auth error message when base and target registry are the same

jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerContextGenerator.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java, jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerContextGeneratorTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructorTest.java, jib-core/src/test/resources/sampleDockerfile
=> Move dependencies to end of classpath

CONTRIBUTING.md, README.md, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/multi-module/build.gradle, examples/spring-boot-draft/build.gradle, examples/spring-boot-draft/pom.xml, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update Jib plugin versions and add CHANGELOG entries

jib-gradle-plugin/README.md
=> Use dynamic gradle plugin version in sub-project

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessorTest.java
Part of #594 (or fixes? not sure how much further we can/should go)
=> Reduce duplicate code in maven plugin

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
=> Fix parsing auth block in maven plugin

README.md
Preview at: https://github.com/GoogleContainerTools/jib/tree/coollog-patch-1
=> Adds link to Velocity talk/slides.

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Document adding extra files

jib-core/src/integration-test/java/com/google/cloud/tools/jib/Command.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java, jib-gradle-plugin/src/integration-test/resources/projects/simple/auth/htpasswd, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/resources/projects/simple/auth/htpasswd
=> Allow LocalRegistry to require credentials

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
=> Disable mount+from

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml
It was only used in test code.
=> Moves slf4j to test-compile only.

jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java, jib-core/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java, jib-core/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
Part of #774 
There is a lot of duplicate code that should be refactored later (after `setKnownRegistryCredentials` and `setCredHelper` are removed).
=> Makes list of credential retrievers.

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Part of #774 
This moves all of the duplicate logic in the plugins into `plugins-common`.
=> Adds DefaultCredentialRetrievers to consolidate generation of CredentialRetrievers list.

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java, jib-gradle-plugin/src/integration-test/resources/projects/default-target/build.gradle, jib-gradle-plugin/src/integration-test/resources/projects/empty/build.gradle, jib-gradle-plugin/src/integration-test/resources/projects/simple/build.gradle, jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
=> Add labels to gradle config

jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
This is breaking the integration tests. Going to revert it and then re-file a pull request when it's fixed.
=> Revert "Adds entries for all directories in layer tarball. (#772)"

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaEntrypointConstructor.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
`addEnvironmentVariable` aligns with others like `addLabels`, `addLabel`, and `addEnvironment`.
=> Some renaming and minor fixes

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ZipUtil.java
Fixing https://github.com/GoogleContainerTools/jib/pull/906#discussion_r214158523
=> Log zip filename when blocking Zip-Slip

jib-core/src/main/java/com/google/cloud/tools/jib/event/EventHandlers.java, jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEvent.java, jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEventType.java, jib-core/src/test/java/com/google/cloud/tools/jib/event/EventHandlersTest.java
Regards #909 
A preliminary implementation that shows a bit of how it will work.
=> Adds JibEvent, JibEventType, and EventHandlers.

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
=> Lower verbosity of insecure registry failover

kokoro/continuous.sh
This should take care of https://github.com/GoogleContainerTools/jib/issues/730#issuecomment-413603874
=> Restart Docker for Mac to fix clock skew in VM

jib-core/src/main/java/com/google/cloud/tools/jib/JibLogger.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java, jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
Prepares for #802.
Next is to add building to these additional tags in `PushImageStep`.
=> Adds additional tags to BuildConfiguration.

proposals/events.md
For #714
Preview at: https://github.com/GoogleContainerTools/jib/blob/events-proposal/proposals/events.md
=> Proposal RFC: Emit events from Jib Core

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojo.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestPlugin.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestProject.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojoTest.java, jib-maven-plugin/src/test/resources/projects/multi/complex-service/pom.xml, jib-maven-plugin/src/test/resources/projects/multi/complex-service/src/main/java/com/test/HelloWorld.java, jib-maven-plugin/src/test/resources/projects/multi/lib/pom.xml, jib-maven-plugin/src/test/resources/projects/multi/lib/src/main/java/com/lib/Lib.java, jib-maven-plugin/src/test/resources/projects/multi/lib/src/test/java/com/lib/LibTest.java, jib-maven-plugin/src/test/resources/projects/multi/pom.xml, jib-maven-plugin/src/test/resources/projects/multi/simple-service/pom.xml, jib-maven-plugin/src/test/resources/projects/multi/simple-service/src/main/java/com/test/HelloWorld.java
The Maven part of #864 .
Built in skaffold support goals:
1. _skaffold-files: a list of files to watch
2. _skaffold-package-goals: a list of jib goals bound to the
package phase.
fixes #958 
fixes #962
=> Add in _skaffold-files _skaffold-package-goals

jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
For https://github.com/GoogleContainerTools/jib/issues/802#issuecomment-418423375
=> Logs additional tags.

jib-maven-plugin/README.md
Fixed incorrect reference to Gradle
Fixes: gh-988
=> jib-maven-plugin Typo

kokoro/continuous.sh
=> Wait until Docker daemon is ready

build.sh
Sometimes I want to do a quick formatting.
=> Add "format" target

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
=> Parallelizes pushing to multiple tags.

jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
Making a quick try without any testing.
=> Use AbsoluteUnixPath for LayerEntry.getAbsoluteSourceFileString()

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
=> Remove deprecated parameters

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTask.java
=> Remove recursion from files task

jib-core/src/main/java/com/google/cloud/tools/jib/ProjectInfo.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
=> Add jib version to layer history

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
=> Check if WEB-INF, WEB-INF/lib, and WEB-INF/classes exist

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessorTest.java
Removes nested parameter shorthands/unused setters in preparation for #1083
=> Cleanup JibExtension

jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/DefaultTargetProjectIntegrationTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/EmptyProjectIntegrationTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/MultiProjectIntegrationTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SimpleProjectIntegrationTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
From https://github.com/GoogleContainerTools/jib/pull/1094#discussion_r222696006
Just moving code from a single file to multiple files.
=> Break up JibPluginIntegrationTest

jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageFormat.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java, proposals/jib_core_library.md
- `JibContainerBuilder#setFormat`
- `JibContainerBuilder#setCreationTime`
- `Containerizer#setToolName`
- `Containerizer#addAdditionalTag`
- Updates the proposal
=> Adds some more required parameters for Jib Core.

jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
Short-term solution for #1079.
=> Set file timestamps in image to epoch + 1 second

examples/helloworld/build.gradle, examples/java-agent/build.gradle, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/spring-boot-draft/build.gradle, examples/spring-boot-kubernetes/build.gradle
=> Update examples to use jib-gradle-plugin 0.9.12

jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
I think this is more straightforward hence easier to understand at the first sight.
=> Convert StepsRunnableConsumer to Runnable

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
=> Set tag to latest if version is unspecified in jibDockerBuild

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml, jib-plugins-common/build.gradle
=> Update commons-compress to 1.18

jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/FilePermissions.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java
=> Add file permissions to cache selector

jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerEntriesSelector.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java
=> Remove LayerEntry#getAbsolute...String methods

jib-core/CHANGELOG.md
=> Add jib-core changelog

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
=> Log inferred cred helper failure at info instead of warn

jib-gradle-plugin/CHANGELOG.md
=> CHANGELOG for jibDockerBuild.dockerClient params

CONTRIBUTING.md, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot-draft/build.gradle, examples/spring-boot-draft/pom.xml, examples/spring-boot-kubernetes/build.gradle, examples/spring-boot-kubernetes/pom.xml, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update version strings for 0.10.0

jib-maven-plugin/pom.xml
=> maven-surefire-plugin 2.22.1

CONTRIBUTING.md, STYLE_GUIDE.md
Adds an initial style guide as rules that extend the Google Java style guide for our codebase. We will add more rules/amend existing rules as necessary.
Preview at: https://github.com/GoogleContainerTools/jib/blob/style-guide/STYLE_GUIDE.md
=> Adds initial style guide.

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java, jib-maven-plugin/CHANGELOG.md, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Allow inheriting ENTRYPOINT and CMD with INHERIT keyword

docs/faq.md
In response to https://github.com/GoogleContainerTools/jib/issues/1281#issuecomment-442964122
=> Add FAQ entry for containerizing executable JAR

jib-maven-plugin/CHANGELOG.md
=> CHANGELOG: WAR image for gwt-app packaging type

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java, jib-maven-plugin/src/test/resources/projects/simple/pom-no-to-image.xml
=> Use artifact ID as image ref for dockerBuild

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Remove useOnlyProjectCache from plugin config section of docs

jib-core/src/main/java/com/google/cloud/tools/jib/async/AsyncDependencies.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/FinalizingStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
=>  Adds AsyncDependencies to reduce boilerplate code.

jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/http/BlobHttpContent.java, jib-core/src/main/java/com/google/cloud/tools/jib/http/ListenableCountingOutputStream.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPuller.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/ConnectionTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPullerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPusherTest.java
Part of #1297 
This will be used to populate `ProgressEvent`s once `ProgressEventDispatcher` is added.
=> Change RegistryClient push/pull to take callback to listen on progress.

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProgressDisplayGenerator.java
=> Fixes html entity > sign.

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/LogEventHandler.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/LogEventHandler.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/AnsiLoggerWithFooter.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/AnsiLoggerWithFooterTest.java
Part of #1297 
Wraps the original logging mechanisms.
=> Adds AnsiLoggerWithFooter to Maven/Gradle plugins.

jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/AllocationCompletionTracker.java, jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandler.java, jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandlerTest.java
=> Changes ProgressEventHandler to provide the callback with updates.

jib-maven-plugin/pom.xml
=> maven-compiler-plugin 3.8.0

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
=> Rewords task progress descriptions.

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml, jib-plugins-common/build.gradle
=> mockito 2.23.4

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
=> Adds 'jib.console' system property to disable progress bar if set to 'plain'.

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Update readmes for 1.0.0

README.md, jib-core/README.md, jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Apply README suggestions

jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
=> Add JibContainerBuilder#addLayer overload with String instead of AbsoluteUnixPath

jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/TimerEventDispatcher.java, jib-core/src/main/java/com/google/cloud/tools/jib/event/events/ProgressEvent.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/json/BuildableManifestTemplate.java
=> Fix javadoc 'see'

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java, jib-maven-plugin/src/test/resources/projects/simple/pom-complex-properties.xml
Part of #1201. Auth is a special case, so we'll have to figure out how to handle that next.
Rather than using `System.getProperty()` for the system properties, this PR gets the system properties via the Maven project and/or session.
=> Check for system properties in pom as well as commandline

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerClientParameters.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
=> Add system properties for docker client configuration

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Fixes #1394. To be merged after next RC.
=> Add dockerClient configuration to READMEs

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGenerator.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooterTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGeneratorTest.java
=> Makes progress footer at most 50 characters wide.

jib-core/build.gradle, jib-maven-plugin/pom.xml, jib-plugins-common/build.gradle
upgrade to latest version of Guava (27.0.1)
=> guava 27.0.1-jre

jib-gradle-plugin/build.gradle
Missed the Gradle plugin in #1437.
=> Upgrade Guava to 27.0.1-jre

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGenerator.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGeneratorTest.java
=> Fix progress display tests ignoring locale

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
I wanted to say "you may not need".
=> Update README about WAR configuration

jib-core/CHANGELOG.md, jib-core/README.md
Fixes #1462. Should be merged after the next core release (0.1.2? 0.2.0?)
=> Add event system explanation to jib-core readme

jib-core/examples/README.md
=> Mentions sbt-jib and AutoJib in Jib Core examples.

docs/faq.md
=> Update broken anchor

jib-core/examples/README.md
Fixes #1451 (4 examples seems like a good amount for now).
=> Add Cram to jib-core examples

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update CHANGELOG for distroless 11

jib-gradle-plugin/gradle.properties
=> Gradle release v1.0.1

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Support Java 11 WAR projects

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Handle more general ConnectException

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Fixes [#1519](https://github.com/GoogleContainerTools/jib/issues/1519)
=> Describe Jib tasks to list them when running `gradle tasks`

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credential.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/test/java/com/google/cloud/tools/jib/configuration/credentials/CredentialTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> Handle "<token>" as Username from credential helpers.

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
=> Stop displaying progress when Maven --batch-mode is specified

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
=> Add CHANGELOG and test for disabling progress bar in batch mode

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/test/java/com/google/cloud/tools/jib/configuration/credentials/CredentialTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> CHANGELOG for ACR OAuth2 auth support / refactor and clean up code

jib-gradle-plugin/gradle.properties
=> Gradle release v1.0.2

README.md, examples/README.md
https://github.com/GoogleContainerTools/jib/issues/1539#issuecomment-471538404
And a Kafka Streams example by @cricket007. Thanks!
https://github.com/GoogleContainerTools/jib/pull/1328#issuecomment-471187656
=> Add links to examples on landing page

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml, jib-plugins-common/build.gradle
=> Upgrade checkstyle to 8.18

docs/faq.md
=> Added documentation on adding javaagent to container

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
I had a doubt on this part of the code, which made me to do an experiment.
=> Add comment of ImmutableMap preserving layer ordering

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update CHANGELOG for docker.io fix

jib-core/gradle.properties
=> Core release v0.9.0

jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md
=> Update jib-core version strings for 0.9.0

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryBrokenPipeException.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryErrorException.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryNoResponseException.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/UnexpectedBlobDigestException.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
=> Check broken pipe while communicating to registries

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
=> Better error output when JSON error parsing fails

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
=> Log warnings for docker config cred helper exceptions

jib-core/src/main/java/com/google/cloud/tools/jib/image/InvalidImageReferenceException.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestions.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestionsTest.java
=> Better error message when using invalid image reference format

README.md, examples/spring-boot/README.md
Fix for https://github.com/GoogleContainerTools/jib/issues/1598
=> Update README.md to fix Spring Boot example link

docs/faq.md
Minor documentation - no ticket created.
=> Update docs to be more future proof

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
=> Set tool name as User-Agent suffix

jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> Set User-Agent HTTP header in RegistryAuthenticator

jib-gradle-plugin/gradle.properties
=> Gradle release v1.1.0

jib-maven-plugin/pom.xml
=> Maven release v1.1.0

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update version strings for 1.1.0

docs/faq.md
fixes https://github.com/GoogleContainerTools/jib/issues/332
=> Update faq to include link to "build containers the hard way"

jib-core/gradle.properties
=> Core release v0.9.1

jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md
=> Update version strings for core 0.9.1

jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/simple/build.gradle
=> Move extraClasspath from test/simple to integration-test/simple

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2Test.java, jib-maven-plugin/src/test/resources/maven/projects/multi/complex-service/pom.xml
Fixes #1660.
~~I still need to update the tests.~~
=> Return absolute paths to extra directories

docs/faq.md
=> Add FAQ when "401 Unauthorized" from registry

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update CHANGELOG for multiple extra directories

docs/faq.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleHelpfulSuggestionsBuilder.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenHelpfulSuggestionsBuilder.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestions.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/HelpfulSuggestionsTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunnerTest.java
Fixes #1619.
Also
- Added a new FAQ for "Forbidden (DENIED)".
- Expanded the previous FAQ for "Unauthorized".
- Simplified `HelpfulSuggestions` class.
=> Add FAQ for Forbidden (DENIED) / expand FAQ / update error message

jib-core/gradle.properties
=> Core release v0.9.2

docs/index.md, jib-gradle-plugin/README.md, jib-maven-plugin/README.md
For #1020.
To be merged after the 1.2.0 release
=> Update extra directories usage, merge after 1.2.0 release

jib-maven-plugin/scripts/prepare_release.sh, kokoro/continuous.bat, kokoro/continuous.sh, kokoro/presubmit.bat, kokoro/presubmit.sh
Too much garbage. I don't remember there was anything useful.
=> No maven debug output

jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md
=> Update core version strings for 0.9.2

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update plugin version strings for 1.2.0

jib-maven-plugin/CHANGELOG.md
=> Fix maven changelog

jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
@loosebazooka I don't know if you tried something on the `Initializer`, but I think it's textually redundant in that it's duplicated in other methods.
=> Remove RegistryAuthenticator.Initializer

jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java, jib-core/src/main/java/com/google/cloud/tools/jib/event/EventHandlers.java, jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
Regarding https://github.com/GoogleContainerTools/jib/commit/7f7c2e607772fdab324226dfcc7432ddb8bdda73#r33584738
=> Make Containerizer EventHandlers non optional

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml, jib-plugins-common/build.gradle
=> Update jackson-databind to 2.9.9

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Add caution on handling of symlinks as per #1576
=> Document symlink behaviour for extras

.github/ISSUE_TEMPLATE.md, docs/faq.md
Try to help users help themselves.
=> Include pointers to FAQ diagnostic answers in new-issue template

jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/Ports.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/PortsTest.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Fixes #1747. Also moved it to the API package.
=> Rename ExposedPortsParser to Ports

jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerEntry.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/LayerConfigurationTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/LayerEntriesSelectorTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
=> Prevent LayerEntry backreach into LayerConfiguration

jib-core/gradle.properties
=> Core release v0.10.0

jib-maven-plugin/pom.xml
=> Maven release v1.3.0

jib-gradle-plugin/gradle.properties
=> Gradle release v1.3.0

README.md, docs/README.md, docs/_config.yml, docs/faq.md, examples/README.md, examples/dropwizard/README.md, examples/helloworld/README.md, examples/java-agent/README.md, examples/ktor/README.md, examples/micronaut/README.md, examples/multi-module/README.md, examples/spring-boot/README.md, examples/vertx/README.md, jib-core/README.md, jib-gradle-plugin/README.md, jib-maven-plugin/README.md, jib-plugins-common/README.md
Putting this up since it seems like we don't really use these analytics. Feel free to close this if I'm wrong. Fixes #535.
=> Remove ga-beacon from docs

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
forgot to update changelog... again...
=> Update CHANGELOG for scratch option

jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V22ManifestListTemplate.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/json/V22ManifestListTemplateTest.java, jib-core/src/test/resources/core/json/v22manifest_list.json
=> add v2.2 manifest list template

jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V22ManifestListTemplate.java
=> fix javadoc comment for manifest list json template

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
wondering if I should also update the plugin changelogs?
=> Update changelog for manifest lists

jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/DockerDaemonImage.java, jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/DockerDaemonImageTest.java
Re-ordered the methods and removed the builder pattern since it seems unnecessary.
=> Simplify DockerClient

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
Fixes the Javadoc error in #1843.
=> Fix Javadoc

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update changelog and version strings for 1.4.0

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/pom.xml, jib-plugins-common/build.gradle
=> Update jackson-databind to 2.9.9.1

examples/spring-boot/build.gradle, examples/spring-boot/pom.xml
=> spring-boot 2.1.6

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldBindingMojo.java
=> Fix deprecated @Component annotation warning

jib-core/build.gradle, jib-core/src/test/java/com/google/cloud/tools/jib/global/JibSystemPropertiesTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java, jib-gradle-plugin/build.gradle, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TaskCommonTest.java, jib-maven-plugin/pom.xml, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProviderTest.java, jib-plugins-common/build.gradle, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
This is worth restoring (or clearing).
=> Restore proxy system properties after test

jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
just a minor fix of some compiler warning that pops up.
=> fix variable naming

jib-gradle-plugin/gradle.properties
=> Gradle release v1.5.0

jib-core/gradle.properties
=> Core release v0.10.1

jib-maven-plugin/pom.xml
=> Maven release v1.5.0

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update version strings for 1.5.0 plugins/0.10.1 core

jib-maven-plugin/gradle.properties
It looks like this got lost in the rebase.
=> Fix maven version 1.5.2-SNAPSHOT

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
Just realized we forgot this part of the release
=> Update versions to 1.5.1

jib-gradle-plugin/gradle.properties
=> Gradle release v1.6.0

jib-core/gradle.properties
=> Core release v0.11.0

jib-maven-plugin/gradle.properties
=> Maven release v1.6.0

docs/faq.md
=> Update 1.6.0 docs for jib.serialize property name

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Fix base image java version check

jib-gradle-plugin/gradle.properties
=> Gradle release v1.6.1

jib-maven-plugin/gradle.properties
=> Maven release v1.6.1

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update version strings for 1.6.1

jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
=> Check exit code for 'docker inspect'

build.gradle
=> Update ASM to 7.1

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update changelog for #2016

README.md, docs/faq.md, jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Staged Docs: 
- https://github.com/GoogleContainerTools/jib/blob/HaTSonHaTS/README.md
- https://github.com/GoogleContainerTools/jib/blob/HaTSonHaTS/jib-gradle-plugin/README.md
- https://github.com/GoogleContainerTools/jib/blob/HaTSonHaTS/jib-maven-plugin/README.md
- https://github.com/GoogleContainerTools/jib/blob/HaTSonHaTS/docs/faq.md
We can also use hit jib-users, slack and gitter
=> Survey in README.md (/, maven, gradle, faq)

build.gradle
=> mockito 3.1.0

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update changelog for #2039

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/SaveDockerStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
Part of `docker save` portion of #1912.
=> Get size, image ID, and diff IDs from "docker inspect"

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointRequestProperties.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
=> Request source image access only if distinct from the base image

jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobChecker.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointRequestProperties.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryErrorExceptionBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/json/ErrorEntryTemplate.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryErrorExceptionBuilderTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Cleanup code

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
Base image digest is reported/logged only when the manifest schema version is 2.
Fixes - #1884
=> Report base image digest

docs/faq.md
View with formatting here: https://github.com/GoogleContainerTools/jib/blob/7cf839d3460076e777f6b47488c1e821fda500ec/docs/faq.md
Fixes #2061.
=> Update FAQ with layering information

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TaskCommonTest.java
Just some minor refactoring and renaming.
Integration tests run OK.
=> Cleanups after #2073

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldSyncMapTemplate.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/SkaffoldSyncMapTemplateTest.java
Adds in the syncMap type that we will use to provide sync information to skaffold.
=> Add in syncmap json templates

examples/dropwizard/pom.xml
=> dropwizard 1.3.16

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ContainerizingMode.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ContainerizingModeTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
part of #2097
required for #2055
=> Moving parsing code for containerizing mode

jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojoTest.java, jib-maven-plugin/src/test/resources/maven/projects/multi/complex-service/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/multi/lib/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/multi/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/multi/simple-service/pom.xml
part of #2097 , Just need naming to make sense, so I re-use params in a test.
=> Fix test project naming

jib-maven-plugin/src/test/resources/maven/projects/multi/pom.xml
Honestly, not sure why this decided to break now, maybe travis updated their maven version.
=> set test project to 1.8 source/target

jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryUnauthorizedException.java
My bad, I missed this cast when I wrapped this once more.
=> Fix class cast exception

jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojo.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojoTest.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldSyncMapTemplate.java
Looking for a sanity check here as I mess with things. Not sure where I should be adding methods and whatever.
Part of #2097 
~~includes code from #2051 (so review that first)~~
=> Add in maven sync map generation

jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
Not really necessary, but I have to do this for completeness sake after I made the server accept concurrent connections recently.
=> Make TestWebServer thread-safe

jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
Sorry, this feels like a spam. I realized Error Prone complains with `StringBuffer` and suggests to do explicit synchronization.
Also as part of this change, I decided to do the standard way of implementing a multi-threaded server: the main server thread loops through `serverSocket.accept()` and it should spawn new threads for each socket. The dirty hack was to quickly fix some tests while I was revamping the new HTTP framework.
This only involves test code.
=> Implement standard multi-threaded socket listening

jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-dockerclient.gradle
Somehow missed this before merging.
=> Fix dockerClient configuration in integration test

examples/multi-module/README.md
=> remove draft heading

kokoro/continuous.sh, kokoro/presubmit.sh
=> Fix Kokoro MacOS

build.gradle
=> mockito 3.2.4

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
=> Support "warName" property of maven-war-plugin

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update changelog for cache location change

jib-maven-plugin/CHANGELOG.md
=> CHANGELOG for optionally ignoring registry port in <server><id> in settings.xml

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunner.java
=> Fix NPE and display exception class name for IOException

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/UpdateCheckerTest.java
Adds the jib user agent string to the update check request.
=> Add user agent to update check

jib-gradle-plugin/scripts/prepare_release.sh, jib-gradle-plugin/scripts/update_gcs_latest.sh, jib-maven-plugin/scripts/prepare_release.sh, jib-maven-plugin/scripts/update_gcs_latest.sh
=> Add scripts to update GCS with latest version string

docs/faq.md
Explain log output coming from #2200.
Should be merged after a new release.
=> Improve FAQ on auth failure

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Update README for new cache location

build.gradle, config/checkstyle/checkstyle-suppressions.xml
- update checkstyle to 8.29
- improve config modification
- add temporary check suppressions so fixes can go in gradually
beginning of #2272
=> Improve checkstyle config

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/InitMojo.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestProject.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/InitMojoTest.java, jib-maven-plugin/src/test/resources/maven/projects/multi/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/spring-boot-multi/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/spring-boot-multi/service-1/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/spring-boot-multi/service-1/src/main/java/com/test/HelloWorld.java, jib-maven-plugin/src/test/resources/maven/projects/spring-boot-multi/service-2/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/spring-boot-multi/service-2/src/main/java/com/test/HelloWorld.java
=> Fix incorrect skaffold init output in multi-module projects

config/checkstyle/checkstyle-suppressions.xml, jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerDescription.java, jib-core/src/main/java/com/google/cloud/tools/jib/cache/Retry.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildContext.java, jib-core/src/main/java/com/google/cloud/tools/jib/http/NotifyingOutputStream.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/FailoverHttpClientTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTarballTest.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLogger.java
- EmptyBlock
- EmptyLineSeparator
- MultipleVariableDeclarations
- AtclauseOrder
- ArrayTypeStyle
part of #2272
=> Fix some pending checkstyle checks

config/checkstyle/checkstyle-suppressions.xml, jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/TempDirectoryProvider.java, jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java, jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/HttpGetVerifier.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
- EmptyCatchBlock
- MissingSwitchDefault
part of #2272
=> Even more checkstyle fixes

config/checkstyle/checkstyle-suppressions.xml, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/VersionChecker.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/VersionCheckerTest.java
- JavadocParagraph
- MethodName
part of #2272
=> A few more easy checkstyle fixes

kokoro/continuous.sh, kokoro/presubmit.sh
=> Remove Kokoro Mac workaround that is no longer needed

proposals/skaffold_config.md
fyi @lightoze @balopat 
rendered: https://github.com/GoogleContainerTools/jib/blob/skaffold-config-proposal/proposals/skaffold_config.md
Should help with: https://github.com/GoogleContainerTools/skaffold/issues/3457
=> proposal for user control of skaffold helpers

jib-gradle-plugin/README.md
updated gradle requirements for 2.0.0+
=> Update required gradle version in readme

jib-gradle-plugin/gradle.properties
=> Gradle release v2.1.0

jib-maven-plugin/gradle.properties
=> Maven release v2.1.0

jib-core/gradle.properties
=> Core release v0.13.1

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update version strings for 2.1.0

proposals/container-build-plan-spec.md
\> [Preview](https://github.com/GoogleContainerTools/jib/blob/8ef257e49fad8509b9f0d816b48b3179c4a9f0d9/proposals/container-build-plan-spec.md) <
=> Container Build Plan specification

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java
I think this is the minimum fix, but I went back and forth on creating a config class that does the config work potentially making it easier to test? (I think?) I'll post that as a followup but this should do:
fixes #2294
=> For config generation use create and move of temp file

jib-core/src/test/java/com/google/cloud/tools/jib/cache/RetryTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
Just fixes some error prone warnings that popped up with the new versions.
=> fix error prone warnings

jib-core/src/main/java/com/google/cloud/tools/jib/http/Request.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java, jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
and also any underlying internal classes
fixes #2367
=> Make useragent nullable in RegistryClient

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
Both of them are available as of now.
=> Update Jib versions to 2.2.0

jib-core/CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Enable parsing base image timestamp with offset

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Merge after release.
* Adds new extra directory configuration
* ...
=> Update readmes for 2.3.0

jib-core/README.md
=> minor fix to version

jib-maven-plugin-extension-api/gradle.properties
Releasing a new version that pulls in the new Build Plan v0.2.0 dependency.
=> Maven extension release v0.3.0

jib-gradle-plugin-extension-api/gradle.properties
Releasing a new version that pulls in the new Build Plan v0.2.0 dependency.
=> Gradle extension release v0.3.0

build.gradle, jib-cli/build.gradle, jib-core/CHANGELOG.md, jib-core/build.gradle
=> Make jib-core expose jib-build-plan

.travis.yml
=> Minor cleanup

jib-core/CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/api/Ports.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/PortsTest.java
=> Ports.parse in api should return Set, not ImmutableSet

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelperTest.java
- Fixes #2450
- Junit test added
=> Add project dependencies in a separate layer for WAR projects

jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> CHANGELOG about Jib Extension Framework

examples/multi-module/build.gradle
=> Fix Jib version in sample

jib-core/CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java, jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java, jib-core/src/test/resources/core/json/dockerconfig.json, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Fix NPE when reading "auths" section in ~/.docker/config.json

jib-core/build.gradle, jib-gradle-plugin/build.gradle, jib-maven-plugin/build.gradle
Not sure I understand what's going on with the transitive test dependencies, I need to look at it again, but this should fix things in the meantime.
=> Add jbcrypt dependency where required

.github/dependabot.yml
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
=> add Dependabot v2

examples/README.md
Fixed my username and added another example
=> [examples] Changed username + added Kafka Connect

jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesExtensionTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProviderTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SkippedGoalVerifier.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/InitMojoTest.java
=> Fix assertThat deprecation

build.gradle, jib-cli/build.gradle, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpec.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Instants.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpecTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/InstantsTest.java
- add jackson databind, yaml dependencies
- add first parseable portion of buildfile
- add `Instants` class which may be removed later
=> Add yaml dependencies and FilePropertiesSpec

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/CopySpec.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
=> Add CopySpec for buildfile

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpec.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpecTest.java
=> Add PlatformSpec for buildfile

jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-extra-dirs.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-extra-dirs2.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-extra-dirs3.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build.gradle, jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-extra-dirs.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom.xml
Distroless added one more layer, so fixing the assertions. Also pinning down an image with a digest.
=> Fix integration tests

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpec.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpec.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/LayerSpec.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpecTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpecTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/LayerSpecTest.java
=> Add LayerSpec, ArchiveLayerSpec, FileLayerSpec for buildfile

jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/Platform.java, jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlanTest.java
This PR adds the ` add / set/ get platform ` methods to the Container Builder Api .
=> Adding the platform config methods to the ContainerBuildPlan api

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpec.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpecTest.java
=> Add base image spec

jib-build-plan/CHANGELOG.md, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/LayerObject.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/Platform.java, jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlanTest.java
- Updated Javadocs and CHANGELOG around the new Platform object added in #2584.
- Switched the order of OS and arch. I came to realized arch comes first everywhere.
- Minor code style changes.
=> Update Javadocs and CHANGELOG for Platforms / minor code style changes

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpec.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpecTest.java
=> Add layers spec

build.gradle, jib-core/CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java, jib-gradle-plugin-extension-api/CHANGELOG.md, jib-maven-plugin-extension-api/CHANGELOG.md
jib-build-plan 0.3.1 is now onilne.
=> Upgrade jib-build-plan to 0.3.1

jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
Added the platforms functionality to the JIbContainerBuilder and to the ContainerConfiguration
Added the testing for the functionality
=> Added the Platform Config to JibContainerBuilder and ContainerConfiguration  

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpec.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpec.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java
=> Add BuildFileSpec for buildfile

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/InvalidPlatformConfigurationException.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/InvalidPlatformException.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
This PR processes the raw platforms configurations
=> Processing Raw Platforms Configs From the Plugins

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildContext.java, jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java, jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RegistryCredentialRetrieverTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildContextTest.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Make ContainerConfiguration required when building BuildContext

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
This is the first step torwards multi-platform image building.
This PR allows Jib to pull down multiple base images which correspond to user specified platforms
=> Allowing PullBaseImageStep to pull multiple images corresponding to the platforms specified by the user

jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FilePermissionsProvider.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ModificationTimeProvider.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/OwnershipProvider.java
This pr serves as part 1 of the process to replace BiFunction usage with explicit interfaces.
For #2638
=> Creating interfaces that will be used to replace BiFunction

jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FileEntriesLayer.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FilePermissionsProvider.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ModificationTimeProvider.java, jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/OwnershipProvider.java, jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlanTest.java, jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/FileEntriesLayerTest.java
=> Use explicit interface instead of BiFunction  

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
This PR adds the ability for JIB to build multiple Images concurrently .
=> build multiple base Images concurrently

jib-build-plan/CHANGELOG.md
=> Update build-plan CHANGELOG.md

jib-build-plan/gradle.properties
=> Build plan release v0.4.0

jib-cli/src/test/java/com/google/cloud/tools/jib/cli/ActualTimestampProviderTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/FixedTimestampProviderTest.java
Originally intended to be included in #2660
=> Renaming test classes to match the main class

jib-gradle-plugin-extension-api/CHANGELOG.md, jib-maven-plugin-extension-api/CHANGELOG.md
=> Update extension APIs CHANGELOG

jib-maven-plugin-extension-api/gradle.properties
New version to pull in build plan v0.4.0 dependency.
=> Maven extension release v0.4.0

jib-gradle-plugin-extension-api/gradle.properties
New version to pull in build plan v0.4.0 dependency.
=> Gradle extension release v0.4.0

build.gradle, jib-maven-plugin-extension-api/CHANGELOG.md
=> Upgrade jib-maven-plugin-extension to 0.4.0

build.gradle
=> Upgrade jackson dependencies to 2.11.2

docs/faq.md
=> Update FAQ about 401 Unauthorized to mention the case of Docker Hub multi-level repository names

jib-gradle-plugin/gradle.properties
=> Gradle release v2.5.0

jib-gradle-plugin/CHANGELOG.md
=> Update jib-gradle-plugin CHANGELOG after 2.5.0 release

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/README.md, jib-maven-plugin/README.md
=> Update docs for Jib 2.5.0 release

jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
=> Fix NPE when Spring Boot Maven Plugin doesn't have <configuration>

examples/dropwizard/pom.xml, examples/helloworld/pom.xml, examples/java-agent/pom.xml, examples/multi-module/pom.xml, examples/spring-boot/pom.xml, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Upgrade Jib Maven to 2.5.1

jib-maven-plugin/gradle.properties
=> Maven release v2.5.1

jib-maven-plugin/gradle.properties
=> Maven release v2.5.2

docs/faq.md, examples/dropwizard/pom.xml, examples/helloworld/pom.xml, examples/java-agent/pom.xml, examples/multi-module/pom.xml, examples/spring-boot/pom.xml, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Upgrade Jib Maven versions

jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildManifestListOrSingleManifestStepTest.java
=> Create manifest list test chanseok

build.gradle, jib-maven-plugin/build.gradle, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SettingsFixture.java
=> Update and standardize maven dependencies

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PushImageStepTest.java
This PR allows Jib to push a manifestList to the registry .
=> Adding functionality to push a manifest list

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
More than one person tripped over this (#2205).
=> Update Jib examples

jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PushImageStepTest.java, jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
=> Clean up and simplify code

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update CHANGELOG about manifest cache being invalidated

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
First in a serious of refactoring PRs for preparation for #2750.
Switches keys and values of the [map of built images --> base images] to the [map of base images --> built images].
The goal is to always have base images as the primary key for all maps in `StepsRunner`. I think this gives a more coherent view of accessing data associated with multiple base images.
=> Switch keys and values of builtImagesAndBaseImages in StepsRunner

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
On top of #2769. Review #2769 first.
In the same vein in #2769, updates the map to use base images as the primary key.
=> Use base image as key for builtImagesAndContainerConfigurationPushResults

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
The current `StepsRunner` code makes it hard to write unit tests for each method.
Having each step method accept `ProgressEventDispatcher.Factory` is also consistent overall, as some methods (those working on individual images) already accept it like this one:
https://github.com/GoogleContainerTools/jib/blob/664d6615850964915bfc42cb28eb3d7ef1447473/jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java#L430-L434
=> Refactor StepsRunner to have step methods accept progressDispatcherFactory

jib-core/CHANGELOG.md, jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java, jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
=> Add ability to set Platform when building an image from scratch 

jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md
=> Update jib-core docs after 0.16.0 release

docs/faq.md
Need to merge after the next release that enables the multi-platform (multi-arch) support.
Fixes #2753.
=> Update FAQ about multi-platform image building

proposals/jib-cli-surface.md
Proposal for design for the cli surface. Implementation will follow
Rendered: https://github.com/GoogleContainerTools/jib/blob/cli-surface-proposal/proposals/jib-cli-surface.md
=> Cli surface proposal

proposals/jib-cli-surface.md
=> Update proposal for auth by cred-helper

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> CHANGELOG for OCI manifest mediaType issue

build.gradle, jib-cli/build.gradle, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Credentials.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/CredentialsTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/JibCliTest.java
Add a helper class to help process credentials with support from DefaultCredentialRetrievers
=> Credential configuration support

jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/JibCliTest.java
=> Clean up some Parameterized tests

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Build.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Containerizers.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/ContainerizersTest.java
I think multiple merges broke something unexpectedly.
=> Fix build after multiple merges

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
To fix breaking integration tests.
=> Renaming method in JarFiles to fix merging issue. 

jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/cli2/JarCommandTest.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Build.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/CommonCliOptions.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Jar.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/ContainerizersForJarTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/JarTest.java
I don't know if it's better to create `CommandSpec` directly or not. Trying the original way.
=> Minor cleanups on Jib CLI

jib-gradle-plugin/gradle.properties
=> Gradle release v2.7.0

jib-maven-plugin/gradle.properties
=> Maven release v2.7.0

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update docs for v2.7.0

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Build.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/CacheDirectories.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/CommonCliOptions.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Containerizers.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Jar.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/CacheDirectoriesTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/ContainerizersTest.java
Integrates the new CacheDirectories util into the cli commands
=> Use cacheDirectories in cli commands

jib-cli/README.md
Adds a first readme for the new jib cli
=> Update jib-cli readme

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update changelog for 2.7.1

jib-gradle-plugin/CHANGELOG.md
=> Update changelog for gradle for 2.7.1

jib-core/CHANGELOG.md, jib-core/README.md
=> Update changelog and readme for core 0.17.0

.github/RELEASE_TEMPLATES/plugin_release_checklist.md
Creates a checklist of items to complete after a release issued, will be automatically triggered when a release workflow is complete for a plugin
I may have missed stuff, but I think this covers it all?
=> Create a plugin_release_checklist.md

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/BuildTest.java
fixes https://github.com/GoogleContainerTools/jib/issues/3018
=> Use correctly processed options in build command

proposals/cli-jar-processing.md
rendered: https://github.com/GoogleContainerTools/jib/blob/cli-jar-proposal/proposals/cli-jar-processing.md
=> Proposal for Jib CLI Jar Processing

examples/README.md
=> Correcting typo in word Kafka

.github/ISSUE_TEMPLATE/issue_report.md
I think "issue" generally has a broader sense.
=> Update and rename bug_report.md to issue_report.md

build.gradle
Small change to make comment consistent.
=> Fix comment in build.gradle

jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update CHANGELOGs for registry mirror support

docs/faq.md
=> Fix broken links about global Jib config

.github/workflows/test_pr_creation.yml
=> Temporary workflow to test release PR creation

.github/workflows/test_pr_creation.yml
Didn't set the github token correctly in the previous PR.
=> Fix temporary workflow

.github/workflows/test_pr_creation.yml
=> Another fix: Use existing branch in temporary workflow

.github/workflows/test_pr_creation.yml
=> More test workflow changes: Use existing branch that doesn't have a PR already 

.github/workflows/jib-cli-release.yml, .github/workflows/prepare-release.yml
To be able to trigger unit tests from the release PR.
=> Fix creation of release PR in release workflow. 

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
=> Remove feature lock on Jib CLI Jar command

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
=> Fix typos in usage text for Jar command

README.md
Instructions: https://codecov.io/gh/GoogleContainerTools/jib/settings/badge
=> Add Codecov badge to the repo

jib-cli/CHANGELOG.md
=> Update CHANGELOG for jib-cli 0.2.0

jib-cli/gradle.properties
=> CLI release v0.2.0

jib-cli/README.md
Rendered: https://github.com/GoogleContainerTools/jib/blob/146a5447d77fbe0d36a6ce618626e5df72be1947/jib-cli/README.md#options
=> Update Jib CLI README.md

jib-cli/README.md
@mpeddada1 what do you think of this?
=> Update Jib CLI entry page

jib-cli/README.md
=> Re-org Jib CLI doc

jib-cli/gradle.properties
=> CLI release v0.3.0

jib-cli/CHANGELOG.md
=> Update CHANGELOG for jib-cli 0.3.0

jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
=> Migrate to Truth and refactor test in MavenProjectProperites

jib-maven-plugin/CHANGELOG.md
=> CHANGELOG about the new Jib Maven extension loading mechanism 

jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Didn't meant to start this, but it happened.
=> Migrate to Truth and remove warning suppressions

jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
As discussed in https://github.com/GoogleContainerTools/jib/pull/3034#issuecomment-792838731
=> Avoid potential Gradle issue of mutating immutable property

jib-cli/build.gradle, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/CommonCliOptions.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/logging/HttpTraceLevel.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/BuildTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JibCliTest.java
=>  Implement --http-trace in Jib CLI

jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java, jib-maven-plugin/CHANGELOG.md
=> Resolve TODO and update CHANGELOGs to reflect changes in #2764

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/globalconfig/GlobalConfig.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/globalconfig/GlobalConfigTest.java
=> Fix links to Jib global config FAQ

jib-cli/gradle.properties
=> CLI release v0.4.0

docs/faq.md, jib-cli/README.md
=> Update FAQ and jib-cli/README for registry mirrors support in Jib CLI

jib-cli/README.md
I was supposed to update the CHANGELOG in this PR but I accidentally did it earlier.
=> Update jib-cli/README for jib-cli-0.4.0

jib-cli/build.gradle, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java
Fixes #3156.
I am not able to reproduce the issue with this fix.
=> [Jib CLI] fix concurrency issue with --http-trace

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/logging/CliLogger.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/logging/CliLoggerTest.java
Dynamic progress output interferes with http trace.
=> [Jib CLI] Disable rich progress when http trace is enabled

jib-cli/gradle.properties
=> CLI release v0.5.0

jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Migrate tests to use Truth framework (first round)

jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
~~On top of #3168. Review it first.~~
=> Migrate tests to use Truth framework (second round)

jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/UpdateCheckerTest.java
=> Migrate UpdateChecker tests to Truth

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Fix WAR entrypoint when custom base image

jib-maven-plugin/gradle.properties
=> maven release v3.0.0

jib-gradle-plugin/gradle.properties
=> gradle release v3.0.0

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Is there anything else we missed?
=> Update plugins docs for Jib 3.0

docs/default_base_image.md
I realized this is important to document.
I'll also expand the FAQ to cover the options not explained in this PR.
=> Document options to avoid Docker Hub rate limit

.github/workflows/unit-tests.yml
=> Remove Codecov

.github/workflows/jib-cli-release.yml
=> Fix Jib CLI release workflow

jib-cli/gradle.properties
=> CLI release v0.6.0

jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java, jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Support Application Default Credentials for Google Artifact Registry

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/War.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/war/WarFiles.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarFilesTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/war/WarFilesTest.java
Implement class to create JibContainerBuilder from an ArtifactProcessor.
Note that this class doesn't include war command-line options yet.
=> Implement class to create JibContainerBuilder from the contents of a WAR file

examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, jib-gradle-plugin/build.gradle
=> remove jcenter

jib-maven-plugin/gradle.properties
=> maven release v3.1.0

jib-gradle-plugin/gradle.properties
=> gradle release v3.1.0

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> Update Jib versions after 3.1.0 release

jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Don't fail on main class inference if custom entrypoint

jib-maven-plugin/gradle.properties
=> maven release v3.1.1

jib-core/gradle.properties
=> core release v0.19.0

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ArtifactProcessors.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/CommonContainerConfigCliOptions.java, jib-cli/src/main/java/com/google/cloud/tools/jib/cli/war/WarFiles.java, jib-cli/src/test/java/com/google/cloud/tools/jib/ArtifactProcessorsTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/WarTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/war/WarFilesTest.java
=> Remove duplicate code from Jib CLI

jib-cli/gradle.properties
=> CLI release v0.7.0

docs/default_base_image.md, docs/faq.md, jib-cli/README.md
=> Update documentation for Jib CLI war command 

.github/RELEASE_TEMPLATES/cli_release_checklist.md, .github/workflows/jib-cli-release.yml, jib-cli/scripts/update_gcs_latest.sh
=> Add script to update Jib CLI version file in GCS bucket

jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java, jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
=> Add jar size suffix to target dependency paths on image when dependency jars have same artifact ID and version

jib-maven-plugin/gradle.properties
=> maven release v3.1.2

jib-gradle-plugin/gradle.properties
=> gradle release v3.1.2

jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java, jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java, jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
=> Reset user and group for automatically added parent directories while building reproducible layer tars

.github/workflows/sonar.yml, build.gradle
=> Add Sonarcloud Github Action to Jib

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
fix for sonar bug: https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTIQcB_fbtb802TP&open=AXrlUTIQcB_fbtb802TP
=> fix sonar bug: add private constructor to hide the implicit public one.

jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java, jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java, jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
This is minor fixes to silence SonarCloud bug of "Call "Optional#isPresent()" before accessing the value."
List if sonar issues:
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTJZcB_fbtb802Ti&open=AXrlUTJZcB_fbtb802Ti
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTbYcB_fbtb802Wu&open=AXrlUTbYcB_fbtb802Wu
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J96N6U6V78Ue75g&open=AXrt4J96N6U6V78Ue75g
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J96N6U6V78Ue75h&open=AXrt4J96N6U6V78Ue75h
=> create obj and call Optional#isPresent() before access. fix sonar bug.

jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
Fixes the following sonar issues:
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTMOcB_fbtb802Ug&open=AXrlUTMOcB_fbtb802Ug
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTMOcB_fbtb802Uh&open=AXrlUTMOcB_fbtb802Uh
=> Add assertions to tests

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PlatformChecker.java
Fix for [this](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTdXcB_fbtb802XI&open=AXrlUTdXcB_fbtb802XI) sonar bug.
=> fix sonar bug to call isPresent for Optional.

jib-cli/CHANGELOG.md, jib-core/CHANGELOG.md, jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blob.java, jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java, jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/blob/BlobTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageWriterTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/FailoverHttpClientTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerFailoverHttpClientTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> CHANGELOG and cleanups after the HTTP retry external PR contribution

jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
Fixes [this sonar issue](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTaFcB_fbtb802Wl&open=AXrlUTaFcB_fbtb802Wl).
=> fix sonar bug to call Optional#isPresent.

jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/XdgDirectories.java, jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/SingleThreadedExecutor.java
Fix sonar issues:
- [Replace this use of System.out or System.err by a logger.](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTQvcB_fbtb802U2&open=AXrlUTQvcB_fbtb802U2)
- [Use the built-in formatting to construct this argument.](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTfhcB_fbtb802Xm&open=AXrlUTfhcB_fbtb802Xm) X2
=> Fix sonar code smell: use log

jib-gradle-plugin/gradle.properties
=> gradle release v3.1.3

jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
Resolves sonar [issue](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTX8cB_fbtb802V0&open=AXrlUTX8cB_fbtb802V0)
=> Remove @VisibleForTesting annotation

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Add instructions for configuring and authenticating with JFrog Artifactory and JFrog Container Registry.
=> Add instructions for publishing to Artifactory

jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/FailoverHttpClientTest.java, jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerFailoverHttpClientTest.java, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Network retry on IO errors only after insecure failover is finalized

jib-gradle-plugin/gradle.properties
=> gradle release v3.1.4

jib-maven-plugin/gradle.properties
=> maven release v3.1.4

jib-core/gradle.properties
=> core release v0.20.0

jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
Fix [this](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTdjcB_fbtb802XU&open=AXrlUTdjcB_fbtb802XU) sonar issue of "Try-catch blocks should not be nested" to increase readability.
=> extract nested try block into method.

build.gradle
- `net.ltgt.apt` is [unnecessary](https://github.com/tbroyer/gradle-apt-plugin) now.
- The IntelliJ test runner setting is a personal preference. Not worth having code lines to maintain.
=> Clean up build.gradle

jib-cli/src/test/java/com/google/cloud/tools/jib/cli/BuildTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/CredentialsTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/WarTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java, jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpecTest.java
Only refactoring. No behavioral changes.
=> Refactor tests

jib-cli/gradle.properties
=> CLI release v0.8.0

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
This is a PR to help with the issues  #2237 #3330 #3346 #3528 and many more
=> Adding information about the to.image attribute

jib-core/CHANGELOG.md
=> Add missing jib-core CHANGELOG update

jib-gradle-plugin/gradle.properties
=> gradle release v3.2.0

jib-maven-plugin/gradle.properties
=> maven release v3.2.0

jib-cli/gradle.properties
=> CLI release v0.9.0

build.gradle, examples/helloworld/build.gradle, examples/java-agent/build.gradle, examples/multi-module/name-service/build.gradle, examples/spring-boot/build.gradle, jib-core/examples/build.gradle/README.md, jib-gradle-plugin/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/default-target/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/empty/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/multiproject/a_packaged/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/complex-build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/spring-boot/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/war_servlet25/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/all-local-multi-service/complex-service/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/all-local-multi-service/simple-service/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/lazy-evaluation/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/multi-service/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/multi-service/complex-service/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/multi-service/simple-service/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/platform/service/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/simple/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/skaffold-config/build.gradle, jib-gradle-plugin/src/test/resources/gradle/projects/war_servlet25/build.gradle
`compile` is obsolete, and `implementation` should work in our case.
=> minor cleanups

gradle.properties, jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java, jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/CredHelperParameters.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/InitMojoTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojoTest.java, jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojoTest.java
=> Fix tests for IPv6 environment

.github/PULL_REQUEST_TEMPLATE.md
This will hopefully help clarify the prerequisites for making contributions.
=> Add checklist to PR template

jib-core/gradle.properties
=> core release v0.21.0

jib-gradle-plugin/gradle.properties
=> gradle release v3.2.1

jib-cli/gradle.properties
=> CLI release v0.10.0

build.gradle
Reverting #3658 to see if it will fix the build.
=> Reverting nullaway upgrade

jib-cli/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Add CHANGELOG updates for imagePushed feature

jib-gradle-plugin/src/integration-test/resources/gradle/projects/default-target/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/empty/build.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-jar-containerization.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java11-incompatible.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-java11.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-timestamps-custom.gradle, jib-gradle-plugin/src/integration-test/resources/gradle/projects/war_servlet25/build-tomcat.gradle, jib-maven-plugin/src/test/resources/maven/projects/default-target/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/empty/pom.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-cred-helper-1.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-cred-helper-2.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-jar-containerization.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-java11-incompatible.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-java11.xml, jib-maven-plugin/src/test/resources/maven/projects/simple/pom-no-to-image.xml, jib-maven-plugin/src/test/resources/maven/projects/war_servlet25/pom-tomcat.xml
Continuation of #3694, but this time for maven and gradle plugins.
=> More temurin backporting

.github/workflows/jib-cli-release.yml
This SLSA attestation was not uploaded. This PR fixes it.
We have created https://github.com/slsa-framework/slsa-github-generator/issues/710 to add support without the need for this extra step.
We will follow-up with a PR once it is landed.
Thanks again.
=> Upload SLSA attestation to release

jib-cli/CHANGELOG.md, jib-core/CHANGELOG.md, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md
=> Update CHANGELOGS for jib-cli, jib-maven-plugin and jib-gradle-plugin

jib-core/README.md
=> Update README for jib core 0.22.0 release

jib-gradle-plugin/gradle.properties
=> gradle release v3.3.0

jib-core/CHANGELOG.md
=> Update CHANGELOG for jib-core 0.22.0 release

CONTRIBUTING.md, examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
For reference: https://github.com/GoogleContainerTools/jib/pull/3291/files
=> Update docs for plugins 3.3.0 release

jib-cli/gradle.properties
=> CLI release v0.11.0

jib-cli/CHANGELOG.md, jib-cli/README.md
=> Update docs for jib-cli 0.11.0 release

jib-cli/README.md
=> Typo in full example

jib-core/gradle.properties
=> core release v0.23.0

jib-maven-plugin/gradle.properties
=> maven release v3.3.1

jib-gradle-plugin/gradle.properties
=> gradle release v3.3.1

jib-cli/gradle.properties
=> CLI release v0.12.0

config/checkstyle/copyright-java.header
=> chore: add 2023 to copyright versions

jib-core/gradle.properties
=> core release v0.24.0

jib-gradle-plugin/gradle.properties
=> gradle release v3.3.2

README.md, docs/google-cloud-build.md
=> docs: Add Cloud Build (fixes #3545)

CONTRIBUTING.md, docs/configure-gcp-credentials.md, docs/default_base_image.md, docs/faq.md, examples/multi-module/README.md, jib-cli/README.md, jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java, jib-gradle-plugin/README.md, jib-maven-plugin/README.md, proposals/jib-cli-surface.md
Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md).
the [style guide](https://github.com/GoogleContainerTools/jib/blob/master/STYLE_GUIDE.md).
Fixes #<issue_number_goes_here> 🛠️
=> docs(typos): fix typos

jib-gradle-plugin/gradle.properties
=> gradle release v3.4.0

jib-maven-plugin/gradle.properties
=> maven release v3.4.0

examples/dropwizard/pom.xml, examples/helloworld/pom.xml, examples/java-agent/pom.xml, examples/multi-module/pom.xml, examples/spring-boot/pom.xml, jib-gradle-plugin/CHANGELOG.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
=> docs: update maven plugin to v3.4.0

jib-core/gradle.properties
=> core release v0.25.0

jib-gradle-plugin/README.md, jib-maven-plugin/README.md
Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md).
the [style guide](https://github.com/GoogleContainerTools/jib/blob/master/STYLE_GUIDE.md).
Fixes #4117 🛠️
=> Fix broken links in README

jib-maven-plugin/gradle.properties
=> maven release v3.4.1

jib-gradle-plugin/gradle.properties
=> gradle release v3.4.1

jib-core/gradle.properties
=> core release v0.26.0

.allstar/binary_artifacts.yaml
=> chore: allstar ignore jars used for testing

jib-gradle-plugin/gradle.properties
=> gradle release v3.4.2

examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-core/CHANGELOG.md, jib-core/README.md, jib-core/examples/build.gradle/README.md, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md
=> chore: update docs for plugins 3.4.2 and core 0.27.0

jib-maven-plugin/gradle.properties
=> maven release v3.4.2

jib-core/gradle.properties
=> core release v0.27.0

jib-cli/CHANGELOG.md, jib-cli/README.md
Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md).
Please follow the guidelines below before opening an issue or a PR:
Fixes #<issue_number_goes_here> 🛠️
=> chore: update jib-cli docs to 0.13.0

jib-cli/gradle.properties
=> CLI release v0.13.0

examples/dropwizard/pom.xml, examples/helloworld/build.gradle, examples/helloworld/pom.xml, examples/java-agent/build.gradle, examples/java-agent/pom.xml, examples/ktor/build.gradle.kts, examples/micronaut/build.gradle, examples/multi-module/build.gradle, examples/multi-module/pom.xml, examples/spring-boot/build.gradle, examples/spring-boot/pom.xml, examples/vertx/build.gradle, jib-core/CHANGELOG.md, jib-core/README.md, jib-gradle-plugin/CHANGELOG.md, jib-gradle-plugin/README.md, jib-maven-plugin/CHANGELOG.md, jib-maven-plugin/README.md
Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md).
Please follow the guidelines below before opening an issue or a PR:
Fixes #<issue_number_goes_here> 🛠️
=> chore: update docs for jib plugins 3.4.3 and jib core 0.27.1

jib-core/gradle.properties
=> core release v0.27.1

jib-maven-plugin/gradle.properties
=> maven release v3.4.3

jib-gradle-plugin/gradle.properties
=> gradle release v3.4.3

jib-gradle-plugin/CHANGELOG.md
The issue number is 4267, but the link is 4265.
=> Fix Link in CHANGELOG.md
