- jib-core/build.gradle
- kokoro/continuous.bat
- kokoro/continuous.sh
The `jib-maven-plugin` test needs `jib-core` to be installed into the local Maven repo.
> Fixes Kokoro build script.

- jib-core/build.gradle
- jib-maven-plugin/kokoro/release_build.sh
- jib-maven-plugin/kokoro/release_publish.sh
- jib-maven-plugin/kokoro/release_sign.sh
- jib-maven-plugin/pom.xml
Sets up #44
These are forked from https://github.com/GoogleCloudPlatform/endpoints-framework-maven-plugin/tree/master/kokoro.
Also, in `jib-maven-plugin`, replaces dependency on `jib-core` with using `jib-core` as additional source set. This eliminates having to publish `jib-core` as a separate artifact.
> Adds Kokoro release scripts.

- README.md
- jib-core/src/main/java/com/google/cloud/tools/jib/image/DescriptorDigest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/InvalidImageReferenceException.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageReferenceTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
Fixes #28 
Adds `from` parameter to plugin to replace the separate `baseImageRegistry`, `baseImageRepository`, and `baseImageTag` configuration parameters.
> Adds support for parsing a base image reference into components.

- CHANGELOG.md
- README.md
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/LayerMetadata.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheMetadataTest.java
> Removes unnecessary check that actually breaks legitimate builds.

- README.md
This lets users know that if they just run `mvn clean compile jib:build` each time, they don't get the cache speed-up.
> Adds note about 'mvn clean' in README.

- CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialRetrieverIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialRetrieverFactory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/RegistryCredentials.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
Fixes #101 
Also adds a test for `RetrieveRegistryCredentialsStep`.
> Uses Docker config in RetrieveRegistryCredentialsStep.

- README.md
Adds `Docker` as explicit image format. Will uncomment `and OCI` once OCI image building is supported. This should help people looking for building Docker images to more easily find Jib.
> Jib builds Java Docker images

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperFactory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/RegistryCredentials.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
Just refactoring `DockerCredentialRetriever` to `DockerCredentialHelper` (and `DockerCredentialRetrieverFactory` to `DockerCredentialHelperFactory`).
> Renames DockerCredentialRetriever to DockerCredentialHelper.

- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheReaderTest.java
`CacheReaderTest` needed to use a temporary cache directory that copies over the contents of the test resource cache directory because it is overwriting the metadata JSON file in there.
> Fixes CacheReaderTest.

- jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildAndCacheApplicationLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/BuildConfigurationTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/LayerBuilderTest.java
- Strip out non-reproducible properties from tarArchiveEntry.
- Allow the user to toggle this feature through build config.
This is a first run, there still some work to do. Decisions in this PR made but I'm not sure about:
- default for reproducibility = false
- reproducibility is configurable. 
- the defaults for file permission overwrites (as described in #7)
> Make layer builder create reproducible layers.

- CHANGELOG.md
- README.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/RegistryCredentials.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/BuildConfigurationTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
Fixes #96 
The `jib-maven-plugin` configuration is called `imageFormat` and can take `Docker` (default) or `OCI`.
> Adds configuration for building and pushing as OCI image format.

- kokoro/presubmit.bat
- kokoro/presubmit.sh
Part of #11 .
The scripts are the same currently.
Next step is to enable integration testing for `jib-maven-plugin` in the continuous scripts.
> Separates presubmit from continuous build scripts.

- kokoro/continuous.bat
- kokoro/continuous.sh
- kokoro/presubmit.bat
- kokoro/presubmit.sh
We are not using it and it is doesn't recognize java 8 constructs.
> Removes cobertura from build scripts.

- CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
`Paths.get(Resources.get("...").toURI())` fails with `FileSystemNotFoundException`. Rather, it should use `Resources.toString`.
> Fixes DockerfileTemplate resource resolution.

- CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplateTest.java
- jib-core/src/test/resources/json/dockerconfig.json
Docker config can contain `HttpHeaders` field, which we need to ignore to parse correctly.
>  Fixes parsing Docker config JSON with extra fields.

- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIT.java
- jib-maven-plugin/src/test/resources/projects/empty/pom.xml
- jib-maven-plugin/src/test/resources/projects/simple/pom.xml
Otherwise, the first build time is not necessarily larger than the second build time.
Will release `v0.1.6` after this is merged.
> Fixes BuildImageMojoIT to use only project-level cache.

- CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/ProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoTest.java
Fixes #27
Adds suggestions for build failures involving:
* "Unknown host" exception when `registry` is misconfigured
* Exception thrown when build output files are missing
* Misconfigured `imageFormat` parameter
Problems left to address:
* Different projects on same registry using invalid credentials from Docker config (#196)
* Build succeeds when main class is invalid (#189)
* Build succeeds with invalid JVM flags (#192)
> Add build failure suggestions

- jib-gradle-plugin/build.gradle
- jib-gradle-plugin/gradle.properties
The version in `gradle.properties` needs to be changed rather than the version in the `pluginsBundle`.
Tag `v0.1.0-gradle` has been updated.
> Re-release jib-gradle-plugin v0.1.0.

- README.md
a small PR updating the `RADME.md`, suggesting to user to use maven encrypt password to encrypt their credentials, if they prefer to use maven settings.
> suggest the use of maven encrypt password when using maven settings to store credentials

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/build.gradle
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/TestProject.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
> Adds jibDockerContext task.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildDockerStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildContainerConfigurationStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildDockerSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildTarballAndLoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildDockerStepsRunner.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
Part of #243.
There's a lot of duplicate code here, so this introduces a few refactoring TODOs, which I grouped into issue #262.
> Attach build to docker daemon functionality to gradle task

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIT.java
Fixes #243.
Still a couple refactoring TODOs, see #262.
> Attach build to docker daemon functionality to maven goal

- jib-core/src/main/java/com/google/cloud/tools/jib/async/AsyncStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/async/AsyncSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/async/NonBlockingSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildDockerSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePullStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildTarballAndLoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/FinalizingStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/TestSourceFilesConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
Addresses https://github.com/GoogleContainerTools/jib/pull/307#issuecomment-391126516
`.jib.builder` package was getting too cluttered
> Moves async to .jib.async and steps to .jib.builder.steps.

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
Fixes #330 
This exposes the `docker load` error to the user so that they can take action to fix it.
@chanseokoh
> Passes 'docker load' error back to user.

- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadata.java
> Synchronizes CacheMetadata methods to avoid concurrency issue.

- docs/_config.yml
- docs/index.md
Mimics https://github.com/GoogleContainerTools/skaffold/tree/master/docs
This will become a Github Pages.
The proposal for how to organize this is to have docs by under a directory for their version, including a directory called `head` for unreleased docs.
> Initializes docs directory.

- jib-gradle-plugin/scripts/prepare_release.sh
- jib-maven-plugin/scripts/prepare_release.sh
`jib-maven-plugin` tags are now of the form `v<version>-maven` instead of just `v<version>`.
>  Makes Maven prepare_release.sh more like Gradle prepare_release.sh and runs integration tests.

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleBuildLogger.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenBuildLogger.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
Seems like a more appropriate place for the method.
Also fixes #365 since there isn't really a need to rename them anymore.
> Move disableHttpLogging to BuildLoggers

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointProperties.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
This should help with fixing #388, as it requires handling `HttpHostConnectException` with different requests.
> Moves registry endpoint calling to separate class that manages request state.

- jib-core/build.gradle
> Make assemble task depend on javadoc so it runs automatically when building jib-core

- jib-core/src/main/java/com/google/cloud/tools/jib/blob/BlobDescriptor.java
Some of our debug messages print `BlobDescriptor` so this makes it more useful to read.
> Adds BlobDescriptor#toString.

- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/FileOperations.java
This should fix the export Docker context bug mentioned in https://github.com/GoogleContainerTools/jib/issues/457#issuecomment-401066278
> Fixes FileOperations#copy for possible duplicate directories.

- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Fixed in `v0.9.1` (#415)
To be merged after documentation is updated to `v0.9.1`
> Removes Azure container registry not supported limitation.

- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildStepsRunner.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestions.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/BuildStepsRunnerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestionsTest.java
Fixes #471 
Now it will say, for example:
```
Execution failed for task ':jib'.
> Build image failed, perhaps you should run `clean` to clear your build cache
```
> Suggests the user to clean their build cache upon CacheDirectoryNotOwnedException.

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
> Allows ReproducibleLayerBuilder to be configured with multiple extraction paths.

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
This makes `jibExportDockerContext` configurable like:
`build.gradle`:
```groovy
jibExportDockerContext {
targetDir = 'my-dir'
}
```
Whereas before it could only be configured from a command line property `--jib.dockerDir`
> Makes jibExportDockerContext.targetDir configurable from build.gradle.

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
Placing `@Input` and `@OutputDirectory` on the same getter invalidates the up-to-date check for `@OutputDirectory`. The CLI option `--jib.dockerDir` also was not valid since it contained a dot.
> Fixes jibExportDockerContext Input vs. OutputDirectory and changes CLI option to --targetDir.

- jib-core/build.gradle
- jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplate.java
- jib-gradle-plugin/build.gradle
- jib-maven-plugin/pom.xml
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
This may fix the breaking macOS builds. The sherter/google-java-format plugin was updated to support the latest google-java-format version.
> Updates formatter version.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticators.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryUnauthorizedException.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
This should be able to fix #541, fix #542, and fix #545
This PR adds token authentication when pulling the base image if the base image registry requires so.
> Fixes using base image from registry that requires token authentication.

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
> Rename BuildTarballAndLoadDockerStep to LoadDockerStep

- README.md
So that users can find and watch the relevant issue easily for updates.
> Links to Jib as a library for Java issue in README.

- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildStepsRunner.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestions.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryCredentialsNotSentException.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/BuildStepsRunnerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestionsTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
> Add error message for credentials not being sent over HTTP

- docs/self_sign_cert.md
Create doc with the workaround discuessed on https://github.com/GoogleContainerTools/jib/issues/543#issuecomment-404347465
> Add instructions for self signed certicate

- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestions.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/HelpfulSuggestionsTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
> Allow authentication over HTTP using system property

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplateTest.java
- jib-core/src/test/resources/json/dockerconfig_extra_matches.json
- jib-core/src/test/resources/json/dockerconfig_index_docker_io_v1.json
Part of #586 (https://github.com/GoogleContainerTools/jib/issues/586#issuecomment-405619066).
Order of preference for finding a matching credential:
1. Exact registry name
1. `https://` + registry name
1. registry name + arbitrary suffix
1. `https://` registry name + arbitrary suffix
> Additionally allow suffix matching for cred lookup

- jib-gradle-plugin/README.md
In #499, the option from gradle to export the docker context was changed from **--jib.dockerDir** to **--targetDir**, but it wasn't reflected in the docs.
> Wrong gradle option in docs to export docker context

- README.md
- docs/faq.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Copy-pasted from https://github.com/GoogleContainerTools/jib/wiki/Frequently-Asked-Questions-(FAQ)
Once this gets approved/merged I can delete the old wiki FAQ.
Fix #665
>  Move FAQ to docs/ folder

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperFactory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigTest.java
Credential helpers store credentials for ServerURLs and those credentials are fetched via the exact ServerURL. For example, a Docker config with:
```
"auths": {
"https://index.docker.io/v1/": {},
},
"credsStore": "gcr"
```
means that even if the original registry was `registry.hub.docker.com`, we need to fetch the credentials using `https://index.docker.io/v1/`.
Also fixes #651 because it needed to.
> Uses matched registry alias for credential helper.

- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java
Fixes #323 #678
The Javadoc says
```
<p>A separator is either an underscore, a dot, two underscores, or any number of dashes.
```
So, it did not make sense to allow a zero-length separator, essentially allowing not needing a separator at all.
```java
ImageReference.parse("gcr.io/qingyangc-sandbox/jibtestimage:askfjl/waegawvw/aweg");
```
The above took 206.050 secs. Now 0.014s.
> Fix regex bug

- jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/ConnectionTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java
Fixes #686.
Had to remove the `@Mock` annotation from the `httpResponse` field, since otherwise it is injected into `Connection` by `@InjectMocks`.
Also added another test class for `Connection` that interacts with a local web server.
> Prevent sending multiple requests in a connection

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
This is sort of related to #620.  This PR adds a little bit of logging around the `PullBaseImageStep` to notify the user that jib will retry when the initial unauthenticated pull fails.
```
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Getting base image nonexistant/image with no auth...
[INFO] Trying again for nonexistant/image with auth...
[INFO] Retrieving registry credentials for registry.hub.docker.com…
```
Perhaps the "auth" is a bit too encoded.
> Improve logging for pulling base image

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
I notice that `RequestState.authorization` is always the value given to the `RegistryEndpointCaller` constructor, so there is not much reason to carry this around in `RequestState`.
After that, `RequestState` becomes a meaningless class holding only a single `URL` field, so it seems obvious to get rid of it.
> Simplify RegistryEndpointCaller code

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
For #681.  If system property `jibSerialize` is set then we run all build steps on the main thread.
Our lifecycle messages don't change however — I still see lifecycle messages before any HTTP traffic begins, and we still have some operations happening in parallel (you can see requests for `distroless/java` and to `registry.hub.docker`), suggesting that we still have some parallelism happening without the StepsRunner.
```
[INFO] --- jib-maven-plugin:0.9.8-SNAPSHOT:build (default-cli) @ first ---
[WARNING] Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible
[INFO] 
[INFO] Containerizing application to foo/bar/baz...
[INFO] 
[INFO] Retrieving registry credentials for registry.hub.docker.com...
[INFO] Getting base image …
```
> System property 'jibSerialize' causes build steps to be executed serially

- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/BuildStepsRunner.java
Towards #620 
`RegistryErrorExceptions` were not explicitly handled in `BuildStepRunner#build()` and so were caught by the [catch-all `else` handler](https://github.com/GoogleContainerTools/jib/compare/i620-RegistryErrorException?expand=1#diff-644d63cbab71bf85ab42dba1ce499fe1R269) which just threw a `BuildStepsExecutionException` with the helper message _Build image failed_.  Although Maven reports the underlying `RegistryErrorException`, Gradle just shows a rather opaque _Build image failed_:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jib'.
> Build image failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':jib'.
> Build image failed
* Try:
Run with --stacktrace option to get the stack trace. Run …
```
> Log RegistryErrorExceptions

- jib-core/src/main/java/com/google/cloud/tools/jib/async/NonBlockingSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java
I had misunderstood `NonBlocksingSteps` until I read the Javadoc of `Futures.getDone()` to see what it actually does. The current Javadoc did not help; it rather created a false illusion that `get()` will magically give the result of a pending future instantly without blocking (which did not make sense at all).
> More detailed Javadocs

- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
So now I think the order of auth checking is something like:
1. Cred helper in build config
2. Username/password system properties
3. Username/password in build config
4. Maven settings
5. Common cred helpers
6. Docker config
Fix #693
> Add 'auth' configuration to maven plugin

- build.sh
Enhances the build.sh:
- adds targets to allows building just the core, maven, or gradle plugins (e.g., `build.sh gradle`)
- adds a `clean` target
- adds a `-q` option to do a quick-build, skipping tests and checks (useful for fast iterations of code tweaks)
- adds a `-e` option to output stack traces on error
- `doBuild` outputs a runnable command line for copy-n-paste
> Enhance build.sh

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
Fixes #734 
The code duplication will be taken care of by when we add a plugins-common framework (#478).
> Skips execution if packaging is 'pom'.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ImageParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
Fixes #684, fixes #709
Breaks `BuildConfiguration` parameters into new `ImageConfiguration` (`from`/`to`) and `ContainerConfiguration` classes.
> Split BuildConfiguration into multiple classes

- build.sh
An earlier iteration of build.sh implicitly rebuilt `jib-core` for each of `jib-maven-plugin` and `jib-gradle-plugin`.  I subsequently pulled the `jib-core` out into a separate target (`core`) but forgot to remove the implicit rebuild.
> Remove unnecessary jib-core rebuilding

- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CachedLayer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageLayersTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #721 
The solution here is to, when adding a new layer, remove any prior layers with the same digest (essentially bumping layers to the top if re-added). This should work, for example, since applying layers A and B in order ABA should produce an identical filesystem as just BA.
> Makes sure there are no duplicate cache entries.

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fix property name and add CHANGELOG entries (#682).
> jibSerialized -> jibSerialize

- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
https://github.com/GoogleContainerTools/jib/pull/749 did not seem to fix the issue completely (simple project still fails, although running the macOS integration tests locally does not fail). This PR runs clean before the first integration test run so that the first run always starts with a clean cache.
This PR also changes the time comparison to be the actual execution time of the `jib:build` goal rather than the time the `Verifier` took so that the comparison is more accurate - this is the main fix.
> Has integration test check actual build time.

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #643.
Before:
`call(URL)` embedded the logic for handling `allowInsecureRegistries`.
Now:
The logic is broken out of `call(URL)` into `callWithInsecureRegistryHandling()`. `call(URL)` always contacts the endpoint and is irrelevant of `allowInsecureRegistries`. `callWithInsecureRegistryHandling()` is the one that handles `allowInsecureRegistries`.
> Make allowInsecureRegistries follow Docker semantics

- kokoro/continuous.bat
- kokoro/continuous.sh
This is necessary for Kokoro to use the right project. Note that only continuous tests run the integration tests.
> Sets the JIB_INTEGRATION_TESTING_PROJECT for Kokoro.

- examples/helloworld/pom.xml
I just wanted to remove the warnings below, but feel free to reject if the intention was to have a minimal working example focusing only on Jib configurations.
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for example:helloworld:jar:1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 22, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building helloworld 1
[INFO] …
```
> Eliminate Maven build warnings for helloworld example

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> Passthrough labels from base image

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Search through all configurations for dependencies of the style
'configurationName project(":path")' and have jib depend on the
'assemble' task of that project. This ensure jar dependencies
are built before jib starts to package the project.
Fixes #815
> Auto build gradle lib-project dependencies

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
Added a test that pulls a base image from a local registry requiring credentials, and pushes the built image to a different local registry that requires different credentials. This would have caught the problem discovered in #801.
Fixes #803
> Add auth integration tests with different from/to registries and credentials

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Fixes #813 for now (probably still more to do, but it's also probably not worth spending too much time on this)
> Reduce duplicate code in build image integration tests

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperNotFoundException.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
> Renames NonexistentDockerCredentialHelperException to DockerCredentialHelperNotFoundException.

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Fixes #724. Now uses explicitly configured credentials over creds pulled from elsewhere (i.e. configured known credentials, configured cred helper, inferred known credentials (e.g. maven settings), inferred cred helpers, docker settings)
> Update credential retrieval order

- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
> Only warn if inferred credential helper threw NonexistentServerUrlDockerCredentialHelperException

- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheEntry.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheWrite.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntry.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheWrite.java
- jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheEntryTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheWriteTest.java
Continuation of #874 - makes changes according to updated spec at #878 
- Changes selection by selector to only return single layer digest
- Renames CacheReadEntry to CacheEntry since it represents an entry in the cache
- Renames CacheWriteEntry to CacheWrite since it simply parameterizes a write
> Fixes CacheStorage interface and renames CacheReadEntry/CacheWriteEntry to CacheEntry/CacheWrite.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/HistoryEntry.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Fixes #875 
`created_by` is now `jib-gradle-plugin` for gradle and `jib-maven-plugin` for maven
> Make createdBy in history configurable

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SkippedGoalVerifier.java
- can use system property -Djib.skip=true to skip if part of
lifecycle
- still requires "required parameters" on jib to be configured
even if skipping, since maven doesn't provide a api for actual
goal skipping
fixes #865
> Add skip parameter to base plugin configuration

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGeneratorTest.java
- jib-core/src/test/resources/sampleDockerfile
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
- jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/projects/simple/pom-complex.xml
- jib-maven-plugin/src/test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
Fixes #890 
This adds a new `environment` configuration parameter to the maven and gradle plugins to set environment variables on the container image.
Maven:
```xml
<configuration>
<container>
<environment>
<key1>value1</key1>
<key2>value2</key2>
</environment>
</container>
</configuration>
```
Gradle:
```groovy
jib {
container {
environment = [key1:"value1", key2:"value2"]
}
}
```
This PR also adds the corresponding "ENV" command to the docker context generator.
Also slipped `skip` into the changelog to fix #929
> Add plugin configuration for environment variables

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Turns `MANIFEST_INVALID` / `TAG_INVALID` errors into slightly more helpful error messages:
>  _Tried to push image manifest for localhost:5000/foo:bar but failed because: Registry does not support Image Manifest Version 2, Schema 2_
Docker Registry 2.1, which returns a `400` / `TAG_INVALID`:
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.11-SNAPSHOT:build (default-cli) on project first: Tried to push image manifest for localhost:5000/foo:bar but failed because: Registry does not support Image Manifest Version 2, Schema 2 | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 400 Bad Request
[ERROR] {"errors":[{"code":"TAG_INVALID","message":"manifest tag did not match URI"}]}
[ERROR] -> [Help 1]
```
Docker …
> Improve the error message when pushing to a registry that does not support v2-2

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobChecker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ErrorResponseUtil.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ErrorResponseUtilTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Fixed #937, builds on fix in #932.
> Create helper for parsing an error code from error response

- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Was getting
```
/usr/local/google/home/tcordle/IdeaProjects/jib/jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java:118: warning: [CatchFail] Ignoring exceptions and calling fail() is unnecessary, and makes test output less useful
try {
^
(see http://errorprone.info/bugpattern/CatchFail)
Did you mean 'throw new AssertionError("should have been a RegistryErrorException", ex);' or 'public void testHandleHttpResponseException_dockerRegistry_tagInvalid() throws HttpResponseException{'?
/usr/local/google/home/tcordle/IdeaProjects/jib/jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java:142: warning: [CatchFail] Ignoring exceptions and calling fail() is unnecessary, and makes test output less useful
try {
^
(see …
```
> Fix ManifestPusherTest warnings

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
Fixes #900 
Also fixes #33 
Replaces `setCreatedBy` on `BuildConfiguration` with `setToolName`, which can also be used to set the user agent suffix in `RegistryClient`.
> Consolidate tool name usage

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticationFailedException.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticationFailedExceptionTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
Changes `RegistryAuthenticationFailedException` to carry the registry and image name that was being authenticated.  Changes `BuildStepsRunner` to use this information.
Fixes #942
> Report registry and image on RegistryAuthenticationFailedException

- jib-core/src/main/java/com/google/cloud/tools/jib/event/EventEmitter.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/EventHandlers.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/Handler.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEvent.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/EventEmitterTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/EventHandlersTest.java
Continuation of #921
Regards #909
`EventEmitter` will be used in the Jib execution to emit the actual events.
> Adds EventEmitter.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
For https://github.com/GoogleContainerTools/jib/issues/802#issuecomment-418423375
Now, build to Docker daemon first loads the tarball, and then does `docker tag` to tag with the additional tags.
> Builds to Docker daemon with additional tags.

- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/CacheStorage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReader.java
- jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageReaderTest.java
Fixes #985.
FYI, I noticed that no code in our repo calls `DefaultCacheStorage.listDigests()`, so this change should be pretty safe.
> List cached layer digests as Set

- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/AbsoluteUnixPath.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/RelativeUnixPath.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/UnixPathParser.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/AbsoluteUnixPathTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/RelativeUnixPathTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/UnixPathParserTest.java
Part of #992.
Followup PR will change `LayerEntry#extractionPath` to use this new `AbsoluteUnixPath`.
> Adds AbsoluteUnixPath to represent Unix paths in absolute form.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
Fixes #965.
Waits for up to 20 seconds.
- I don't think `--restart=always` is ever needed. What the flag would do is that the container will automatically start up if the Docker daemon restarts.
- No need to explicitly call `docker rm <container>` when giving `--rm` for `docker run`.
> Wait until local registry is ready when setting it up in integration tests

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/DockerContextMojoIntegrationTest.java
Running integration tests pollute my local docker container space, so I decided to auto-remove the test containers.
> Delete containers after run in integration tests

- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheMetadata.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageLayersTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> Keep duplicate layers to match history

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/projects/empty/pom.xml
For https://github.com/GoogleContainerTools/jib/issues/802#issuecomment-418423375
> Adds to.tags configuration for Maven.

- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFiles.java
- jib-core/src/main/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageWriter.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectoryTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/ncache/DefaultCacheStorageFilesTest.java
Fixes #1036 
Uses `[CACHE DIRECTORY]/tmp` as the temporary directory.
> Stores temporary cache files under cache directory.

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurationsTest.java
Fixes #1050.
Also one tiny change that adds the resources layer directory directly for Gradle.
> Remove sorting / add resources directory directly

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
Fixes #1013. Stole from #1047 + fixed a test.
> Fix docker error output not being captured

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
This is useful for `JibContainerBuilder#containerize` #1076 to pass the `Docker` executable path configured on `DockerDaemonImage`.
> Makes Docker executable configurable.

- jib-gradle-plugin/gradle.properties
Fixes #1110
This is releasing `v0.9.11` with just the #1061 fix. Note that branch `0.9.12` should NOT be merged into master.
> Gradle release v0.9.12

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
- proposals/jib_core_library.md
Brings `JibContainerBuilder` in sync with the new `container.user` configuration.
>  Adds JibContainerBuilder#setUser.

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaDockerContextGenerator.java
- jib-core/src/test/resources/webAppSampleDockerfile
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PluginConfigurationProcessor.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/PluginConfigurationProcessor.java
Fixes #1142. As stated in #1142, this is mostly for consistency with `programArguments` being `@Nullable`.
This doesn't change the current behavior because `JibContainerBuilder.entrypoint` will be set to a proper value computed by `PluginConfigurationProcessor.computeEntry()`.
> Make Entrypoint parameter nullable

- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
I think we're safe to say now we have preliminary support for WAR projects.
- `jib.to.credHelper` felt like it's an added feature, so moved it to the "Added" section. Feel free to disagree.
- Moved `container.user` to the "Added" section.
> Preliminary WAR support description in CHANGELOG / other fixes

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/FilePermissions.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/FilePermissionsTest.java
Fixes #1165 
Adds a `FilePermissions` class that can be instantiated from either an octal string or a set of `PosixFilePermissions`. Also has a getter for the file permission bits.
> Add FilePermissions class

- CONTRIBUTING.md
Explicitly call out that we follow the Google Java Style Guide.
Add reference to jib-plugins-common.
> Update CONTRIBUTING.md for style guide and jib-plugins-common

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/projects/simple/build.gradle
- jib-gradle-plugin/src/integration-test/resources/projects/simple/complex-build.gradle
- jib-gradle-plugin/src/integration-test/resources/projects/simple/src/main/java/com/test/HelloWorld.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerContextTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoryParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/DockerContextTaskTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-gradle-plugin/src/test/resources/projects/multi-service/complex-service/build.gradle
- jib-gradle-plugin/src/test/resources/projects/simple/build.gradle
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenLayerConfigurations.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelper.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaLayerConfigurationsHelperTest.java
Toward #794 
`extraDirectory` configuration parameter is now an object with a `path` and `permissions` field, instead of just being a file
- `extraDirectory.path` covers the original purpose of `extraDirectory`
- `extraDirectory.permissions` is a map from path on container to an octal string representation of the file's permission bits
For example, if your extra directory is `(project dir)/src/main/custom-jib`, and you want to give executable permissions to `path/to/file1` and `path/to/file2` within, you would add this configuration to your `build.gradle`:
```groovy
jib {
...
extraDirectory {
path = file('src/main/custom-jib')
permissions = [
'/path/to/file1': '755',
'/path/to/file2': '755'
]
}
}
```
The old method of configuring the extra directory is also still supported:
```groovy
jib …
```
> Update gradle extraDirectory config parameter to include path and permissions field

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
The `_jibSkaffoldFiles` task doesn't need to depend on the `classes` and `assemble` tasks.
Fixes https://github.com/GoogleContainerTools/skaffold/issues/1197
> Remove dependence of filesTask on classes and assembly

- README.md
- jib-core/README.md
Preview at: https://github.com/GoogleContainerTools/jib/tree/jib-core-readme/jib-core
This provides initial documentation for Jib Core.
> Adds README for Jib Core.

- jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/DockerContextMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
This moves the disableHttpLogging logic to the registry client level under `registry.Connection`, where the Apache `HttpTransport` is set up. The implications of this are:
- Jib Core does not show up with annoying logs anymore
- Removes all the disable logging logic from Maven side
- Gradle still needs its own disable logging logic due to how the logging is handled in Gradle
> Disables Apache HTTP logging at registry client level.

- examples/micronaut/build.gradle
As per #1234, I suggest to upgrade the dependencies of Micronaut from the M4 milestone to the 1.0.0 GA release of the framework (released Oct 23)
> Update dependencies to use the 1.0.0 GA release of Micronaut

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/DockerHealthCheck.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/DockerHealthCheckTest.java
Adds a `DockerHealthCheck` class to be used for configuring container healthchecks in jib-core. To be used used in #1217, towards #676.
> Add DockerHealthCheck class

- examples/micronaut/build.gradle
When running the Micronaut application locally, with `./gradlew run`, a main class should be specified so the JavaExec task knows which main class to run.
This should fix #1242
> Define run.main for the main class to launch

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/AuthParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TargetImageParameters.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenRawConfigurationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/AuthProperty.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Fixes #1177.
`PluginConfigurationProcessor` is getting messy so I think we should figure out how to reduce the number of parameters in each method soon.
> Fix NullPointerException with incomplete auth config

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
> Write out jib-image.id when image is built

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurationsTest.java
Check that referenced dependency files exist before configuring the layers.  Logs skipped files.
Fixes #1271
> Ensure Gradle dependency files exist

- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/Allocation.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/AllocationTest.java
Part of #1297. The `Allocation` class will be used by the `ProgressEvent`.
> Adds progress Allocation to represent Decentralized Allocation Tree node.

- proposals/progress_output.md
Regards issues: #1251, #806 
Project tracker at #1297
Preview at: https://github.com/GoogleContainerTools/jib/blob/proposal-progress-output/proposals/progress_output.md
Brief recording of the current state of the POC: https://asciinema.org/a/H4BIcjEYsSa8Rtyy0ayZt01Xh
> Proposal: Provide feedback on push progress.

- jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEventType.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/events/ProgressEvent.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/Allocation.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/events/ProgressEventTest.java
Part of #1297 
Represents a `JibEvent` indicating progress on some `Allocation`.
> Adds ProgressEvent.

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildResultTest.java
Fixes a todo that has been around for a while. It may be possible to consolidate a bit more in `PushImageStep`, but that has a bit of extra code for pushing to multiple tags, so I ignored it for now.
> Consolidate digest generation in LoadDockerStep and WriteTarFileStep

- jib-core/src/main/java/com/google/cloud/tools/jib/http/ListenableCountingOutputStream.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/ListenableCountingOutputStreamTest.java
Part of #1297 
This will be used to count sent/received bytes when pushing and pulling to/from registries.
> Adds ListenableCountingOutputStream.

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
Part of #1297 
This defers running the steps till the end and allows for `StepsRunner` to know how many steps there are before running them all.
> Change StepsRunner to be more of a builder to prepare for assigning Allocations.

- jib-core/src/main/java/com/google/cloud/tools/jib/event/events/ProgressEvent.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/Allocation.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/AllocationCompletionTracker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandler.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/events/ProgressEventTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/AllocationCompletionTrackerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/AllocationTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/MultithreadedExecutor.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandlerTest.java
Part of #1297 
`ProgressEventHandler` keeps an overall progress state as well as tracks unfinished allocations via the `AllocationCompletionTracker`. `ProgressEventHandler` will be the only concurrently-modifiable class in Jib (as of yet).
>  Adds ProgressEventHandler.

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Fixes #1238.
Adds two system properties for setting cache directories:
* `jib.baseImageCache`
* `jib.applicationCache`
> Add system properties for setting cache directories

- examples/dropwizard/README.md
- examples/dropwizard/pom.xml
Some simplification after #1290.
It's tempting to remove the `package` phase binding too (and the command becomes `./mvnw clean compile jib:dockerBuild`), but I guess that's fine.
> Minor updates to Dropwizard example

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credential.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
Part of #1297 
Every builder step now emits `ProgressEvent`s. This will be refactored once `ProgressEventDispatcher` is in.
> Assigns Allocation to each builder step.

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProgressDisplayGenerator.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ProgressDisplayGeneratorTest.java
Part of #1297 
`ProgressDisplayGenerator` generates the displayed text for progress feedback.
> Adds ProgressDisplayGenerator.

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTestHelper.java
Ensure that internally-created `ExecutorService` is shutdown.
Fixes #1310
> Ensure internally-created executor service is shutdown on completion

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/FinalizingStep.java
This is fine because we don't care about exceptions from a logging future.
> Suppresses warning about ignored Future in FinalizingStep.

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/AnsiLoggerWithFooter.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/AnsiLoggerWithFooterTest.java
Part of #1297 
To be more compatible with logging methods with newline at end.
>  Improves the logic of AnsiLoggerWithFooter.

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerClientParameters.java
Fixes this warning that shows up after running gradle tests:
```
> Task :validateTaskProperties
Task property validation finished with warnings:
- Warning: Task type 'com.google.cloud.tools.jib.gradle.BuildDockerTask': property 'dockerClient.executable' has @Input annotation used on property of type java.nio.file.Path.
```
> Fix gradle validateTaskProperties warning about dockerClient.executable

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLogger.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLogger.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ProgressDisplayGenerator.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilderTest.java
Part of #1297 
To test the new progress logging, simply run with `-Djib.showProgress=true`.
> Attachs ProgressEventHandler as an event handler via the plugins.

- jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java
`DefaultCacheStorageWriter.moveIfDoesNotExist()` uses `Files.move()` to move a cache-layer into place.  The implementation first attempted to perform an atomic rename, but should that operation error in certain ways then it would retry the move as a copy-and-delete.  But it turns out that (1) the underlying primitives may throw other hard-to-enumerate platform-specific exceptions, which we were not catching, and which may be thrown in a concurrency situation where two jobs are attempting to install the same cache-layer, and (2) `Files.move()` does a copy-and-delete when required.  
So this patch changes the code to just perform a `Files.move()` and lets the implementation do its best.  If an exception is raised but the destination directory now exists, then the implementation ignores the …
> Make DefaultCacheStorageWriter.moveIfDoesNotExist() more robust to concurrency

- jib-core/src/main/java/com/google/cloud/tools/jib/http/Connection.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/ProxyProvider.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProgressDisplayGenerator.java
Configuration from either Maven settings or system properties
Issues: #525, #1304
> Add proxy authentication

- jib-gradle-plugin/scripts/prepare_release.sh
- jib-maven-plugin/scripts/prepare_release.sh
To allow for us to release `v1.0.0-rc1` after #1362 .
This is based on https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/master/scripts/prepare_release.sh
> Adds support for rc release to prepare_release.sh.

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
With the docker context generation gone, these methods don't need to be public.
> Reduce visibility

- CONTRIBUTING.md
- build.sh
- jib-maven-plugin/pom.xml
- jib-maven-plugin/scripts/prepare_release.sh
- kokoro/continuous.sh
I am always confuse by the different names between Maven and Gradle. This will make them consistent.
> Rename Maven profile ID

- jib-core/build.gradle
Following [Stephen Colebourne's excellent advice on using the super-package as the module name](https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html), I suggest **`com.google.cloud.tools.jib`** as the module name for our `jib-core` library.
Note that once we decided the name, we should never change after the library goes GA.
Note that any traditional JARs prior to Java 9 are automatically turned into modules (the feature called `automatic modules` when specified on the module path. Even now, users can use `jib-core` with JPMS. However, if we do not declare an official name for `jib-core`, [it will become ugly in the JPMS world in the not-too-distant future](http://branchandbound.net/blog/java/2017/12/automatic-module-name/).
I've done a few sanity checks suggested in the above …
> Add Automatic-Module-Name: in MANIFEST.MF

- jib-core/build.gradle
- jib-gradle-plugin/build.gradle
- jib-maven-plugin/pom.xml
- jib-plugins-common/build.gradle
Making github security alert go away.
> Update com.fasterxml.jackson.core:jackson-databind to 2.9.8

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/projects/simple/build-dockerclient.gradle
- jib-gradle-plugin/src/integration-test/resources/projects/simple/mock-docker.sh
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/projects/simple/mock-docker.sh
- jib-maven-plugin/src/test/resources/projects/simple/pom-dockerclient.xml
Fixes #468. Maven side of #1214.
Docker parameters can be configured using:
```
<configuration>
<dockerClient>
<executable>/path/to/executable</executable>
<environment>
<key1>value1</key1>
<key2>value2</key2>
</environment>
</dockerClient>
</configuration>
```
~~Let me know if you have any ideas for how to test this (seems gradle side is also missing tests).~~ Also adds integration tests for both Maven and Gradle.
> Add docker client executable/environment configuration to Maven

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-maven-plugin/src/test/resources/projects/simple/pom-complex-properties.xml
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Follow-up to #1389, fixes #1201. Needed a bit of special work for this since auth properties are a special case and need to be defined together.
> Get maven auth system properties from pom and commandline

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
Fixes #416. Just adds a message to the `IllegalArgumentException`s that are thrown when a configured list contains a null element.
> Add clearer error messages for null elements in config lists

- jib-core/build.gradle
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/MainClassFinder.java
- jib-gradle-plugin/build.gradle
- jib-maven-plugin/pom.xml
- jib-plugins-common/build.gradle
All tests pass, but given how the main class finder is an important feature and historically has had many edge cases, we may want to do some extra manual testing on a big project.
This is about 1/7 the size of javassist, so I think we can say this fixes #841.
> Replace javassist with org.ow2.asm

- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Actual behavior is "If not set, default is used.", which is implied by the default column.
@chanseokoh for catching this
> Removes incorrect description about jib.applicationCache.

- jib-core/build.gradle
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java
- jib-gradle-plugin/build.gradle
- jib-maven-plugin/pom.xml
- jib-plugins-common/build.gradle
Not really necessary, but the latest 1.27.0 defines `Automatic-Module-Name`.
> Upgrade Google HTTP Client dependency

- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectory.java
Although I'm unable to reproduce the error in #1438, the actual error is occurring when deleting our `com.google.cloud.tools.jib.filesystem.TemporaryDirectory` which explicitly notes that the temporary directory may not be closed:
https://github.com/GoogleContainerTools/jib/blob/653ed72f36d0d5467d61757e2b3cd389c06ce496/jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/TemporaryDirectory.java#L26-L29
This patch changes `TemporaryDirectory#close()` to ignore any exceptions when deleting the temporary directory.  Although this patch doesn't fix the underlying problem in #1438, an error when deleting a temporary directory shouldn't fail the build.
It would be good to somehow log this, so I left a todo.
> Do not fail when attempting to delete temp directory

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildStepType.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ProgressEventDispatcherContainer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/events/ProgressEvent.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandler.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcherTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/events/ProgressEventTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/ProgressEventHandlerTest.java
Part of #1054. This PR adds a `BuildStepType` enum, which is passed to progress events so that jib-core users may know which progress events correspond to which steps in the build.
I'm still not totally familiar with the progress system, so let me know if this seems like an ok direction to take.
Possible followups:
- Add documentation for what each of the `BuildStepType`s mean
- Add an event for counting the number of layers involved in the push/pull steps, or modify/add progress events that make it possible to identify which layer a progress event was sent from
> Add enum for matching progress events to build steps

- examples/dropwizard/pom.xml
- examples/ktor/build.gradle.kts
Note that JVM flags in dropwizad example are for Java 8.  OpenJDK 11 doesn't support the `-XX:+UseCGroupMemoryLimitForHeap`, and has deprecated `-XX:InitialRAMFraction`, `-XX:MinRAMFraction`, and `-XX:MaxRAMFraction`.
> Explicitly note JVM flags for Java 8

- examples/README.md
- jib-core/examples/README.md
- jib-core/examples/build.gradle/README.md
Adds a single `build.gradle` example for now.
Ported from https://github.com/GoogleContainerTools/jib/issues/1452#issuecomment-458598641
Preview at https://github.com/GoogleContainerTools/jib/tree/jib-core-examples/jib-core/examples/build.gradle
> Adds examples to Jib Core.

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/builder/BuildStepsIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/BuildStepType.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayersStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/JibEventType.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/events/LayerCountEvent.java
Adds a new `LayerCountEvent` that indicates the number of layers being processed during:
- `BuildAndCacheApplicationLayerStep`s
- `PullAndCacheBaseImageLayersStep`
- `PushLayersStep`
This is probably enough events for now, so fixes #1054.
> Add event for counting layers in pull/build/push steps

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticationFailedException.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
Fixes #1440 
Originally, it was up to the library user to catch an `ExecutionException`, and determine what kind of execution caused it using a series of `if (ex instanceof ...)` statements for more fine-grained exception handling. With this PR, `ExecutionException`s' causes are re-thrown if they are `RegistryException`s, which makes jib-core error handling/documentation much more straightforward.
> Rethrow ExecutionException's cause in jib-core

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java
Fixes #1464.
Adds `JavaContainerBuilder#setAppRoot()` to support building WARs using `JavaContainerBuilder`. Also adds `JavaContainerBuilder#fromDistrolessJetty()` that uses `gcr.io/distroless/java/jetty` as the base image and `/jetty/webapps/ROOT` as the app root.
> Add setAppRoot() and fromDistrolessJetty() to JavaContainerBuilder

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTaskV2.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/FilesTaskV2Test.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutput.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutputTest.java
Part of #1484. The logic is very similar to the original `_jibSkaffoldFiles` (actually almost completely copy-pasted), but it categorizes the files and prints them out in a JSON string instead of just a list.
> Add _jibSkaffoldFilesV2 task

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleLayerConfigurations.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Small cleanup, uses `getAppRootChecked()` from `PluginConfigurationProcessor` instead of `MojoCommon`/`TaskCommon`.
> Consolidate getAppRootChecked()

- kokoro/presubmit.sh
Recently, the degree of flakiness has well crossed the tolerance threshold.
Then I just noticed we weren't applying the same workaround to restart Docker on presubmit builds. Hopefully this resolves the issue.
> Restart docker as workaround to fix clock skew

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTaskV2.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/FilesTaskV2Test.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2Test.java
- jib-maven-plugin/src/test/resources/maven/projects/multi/complex-service/pom.xml
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutput.java
Fixes #1484. Adds new goal that lists the files skaffold should watch, in JSON format.
There may be more to do resolving the extra directory, but I'm not sure. Let me know if there are test cases I should add.
> Add jib:_skaffold-files-v2 goal

- examples/micronaut/build.gradle
Fixes #1495.
#1243 added `run.main` to fix `./gradlew run` back then. But I couldn't find any documentation about `run.main`.
OTOH, [the use of `mainClassName` is documented in the Micronaunt doc](https://docs.micronaut.io/latest/guide/index.html#groovyFunctions). It makes the sample work again.
~~I had to add `jib.container.mainClass`. This might be due to #1501.~~ UPDATE: #1501 fixed in Jib 1.0.1.
> Define mainClassName in Micronaut example

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/FilesTaskV2.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/FilesTaskV2Test.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2Test.java
Since the JSON string will always only be on one line, the "END JIB JSON" footer isn't necessary.
> Remove END JIB JSON string from files task/mojo

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java
- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/Allocation.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcherTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes https://github.com/GoogleContainerTools/jib/issues/1512#issuecomment-468333807, where the root cause is believed to be an inaccurate or missing `Content-Length` value. (The log shows that `remainingAllocationUnits` is -1 when the `Verify` statement is violated.)
Closes #1512.
> Do not crash on inaccurate progress reporting

- CONTRIBUTING.md
- examples/dropwizard/pom.xml
- examples/helloworld/build.gradle
- examples/helloworld/pom.xml
- examples/java-agent/build.gradle
- examples/java-agent/pom.xml
- examples/ktor/build.gradle.kts
- examples/micronaut/build.gradle
- examples/multi-module/build.gradle
- examples/multi-module/pom.xml
- examples/spring-boot-draft/build.gradle
- examples/spring-boot-draft/pom.xml
- examples/spring-boot-kubernetes/build.gradle
- examples/spring-boot-kubernetes/pom.xml
- examples/vertx/build.gradle
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/README.md
> Update version strings for 1.0.2

- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Fixes #1530.
@andxu following the same template and pattern for other credential helper documentation, I did not list the detailed steps to configure the ACR credential helper. I think we'll keep this simple and consistent.
> Update doc for ACR credential helper configuration

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java
This changes `JavaContainerBuilder` to not build the layer configuration until `toContainerBuilder()` is called, allowing people who use `JavaContainerBuilder` to change the app root even after files have been added.
Fixes #1476.
> Allow setting approot any time during JavaContainerBuilder construction

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Jib.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageReferenceTest.java
Adds `Jib.fromScratch()`, which signals most of `PullBaseImageStep` to be skipped (and effectively skips `PullAndCacheBaseImageLayersStep` and `PushLayersStep` for the base image as a result, since there are no layers to process).
Part of #1471. Should we support this in the plugins, or does that start to stray too much from being a "Java" image builder?
> Allow setting scratch base image in jib-core

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
Fixes #1545. `client_id` is a required parameter.
> Send client_id for OAuth2 registry auth

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java
For the WAR case, classes and dependencies need to be added to a non-default directory on the container. So this PR adds the ability to set the destination to send the added files to on the container.
This is a small step towards #1373.
> Allow setting destinations on JavaContainerBuilder

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java
After #1552.
Discussed with @chanseokoh and he mentioned that the WAR case does not want to set the entrypoint using a main class. So in order for this class to be useful for building WAR containers, we need a way to skip setting the entrypoint. So, this PR will skip constructing the entrypoint if the user never calls `JavaContainerBuilder#setMainClass()`.
> Allow skipping main class in JavaContainerBuilder

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/credentials/Credential.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/RegistryImageTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/credentials/CredentialTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
> Rename from Credential.basic() to Credential.from()

- CONTRIBUTING.md
When building a new workspace, I had forgotten what the steps were to properly bring Jib into Eclipse. I also recall seeing someone asking for the instructions.
> Add instructions for importing source into Eclipse

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunner.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/BuildStepsRunnerTest.java
Slight cleanup by moving some logging events into jib core, which removes an extra `layerConfigurations` parameter being passed around.
> Move layer file info logging to containerize()

- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurations.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/JavaLayerConfigurationsTest.java
Before this PR, in `JavaLayerConfigurations`, all 5 java layers (classes, resources, dependencies, snapshot dependencies, and extra files) are added automatically, whether there are files in the layers or not. This PR skips the empty layers.
Small bit towards #1373.
> Don't add empty layers in JavaLayerConfigurations

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/LayerConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
I assume this is close to the issue https://github.com/GoogleContainerTools/jib/issues/1079 so I didn't recreate a ticket but my use case is a bit different.
I have a dockerized app using libraries relying on file lastModifiedDate to create a kind of "testable timestamp" to check if some caching should be invalidated or not.
Current impl of jib-core setModTime to 1s after epoch which breaks that usage.
To ensure it is reproducable I propose to add the timestamp in the API of addEntry(file), with a minimum of 1s after the epoch. 
This way people can choose to hardcode it or use a custom version if they know - like using maven metadata if the file comes from a maven release.
Hope it makes sense.
> add lasttimestamp to LayerEntry to ensure the timestamp can be controlled for key files

- jib-maven-plugin/pom.xml
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
Toward #1369.
Probably we initially considered the possibility that the decryptor could be null, but so far, no one has reported the violation of this:
```java
SettingsDecrypter getSettingsDecrypter() {
return Preconditions.checkNotNull(settingsDecrypter);
}
```
After all, `getSettingsDecrypter()` has not been `@Nullable`. I don't think we need to take out the `checkNotNull()`.
> No need for checking null Maven settings.xml Decryptor

- docs/faq.md
Fix up debugging item in FAQ to follow recommended practice and explicitly specify `localhost`.  Alternative to #1579 (withdrawn).
> Change JDWP example to specify localhost

- jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
Fixes #1621, hopefully.
From various logs, I think the reason is that the server writes response first and then tries to read, causing the client side to shut down connection early before reading all the input. Now the server will be more compliant to the HTTP protocol.
> Let test web server write only after reading first HTTP request

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
- jib-core/src/test/resources/core/json/v21manifest.json
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> Reverse manifest V21 layers when adding

- jib-core/src/main/java/com/google/cloud/tools/jib/event/events/LogEvent.java
Helpful to identify errors reported in tests involving logging.
> Add helper LogEvent#toString()

- jib-core/src/main/java/com/google/cloud/tools/jib/image/LayerEntry.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
So this defines a strong behavior for parents that don't exist in the layer yet.
1. order matters, a directory can only be configured if it's added to the layer before any of its children
2. for a file with parent(s) that doesn't exist yet, a default modified time is applied.
fixes #1648 
NOTE: This *does not* fix the out of order issue for defining directory permissions. That should be fixed in a followup (#1650)
> Add default timestamp to not-yet-existant parent dirs

- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V21ManifestTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/V21ManifestTemplateTest.java
- jib-core/src/test/resources/core/json/v21manifest.json
Fixes #1643.
Fixes #1641.
Travis is failing to install OpenJDK 11, so ignore that for the moment.
> Propagate labels from base image / propagate container config in case of V2.1 manifest

- jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageFiles.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriter.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V21ManifestTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageFilesTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/DefaultCacheStorageWriterTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/LockFileTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/V21ManifestTemplateTest.java
Towards #718.
Adds `writeMetadata` methods to `Cache`, `CacheStorage`, and `DefaultCacheStorageWriter`, as well as helpers for getting the image metadata directory in `DefaultCacheStorageFiles`.
Mostly ignored file-locking for now; I did reuse some methods which involve file locking, but I'll probably need to take another look in the future when the locking design is nailed down.
> Add cache methods for saving manifest and container config

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
Adds simple test for Jib Core to ensure that created images have consistent file timestamps, permissions, no implicit parent directories, and consistent ordering.  Verified this catches the directory timestamp issue in #1649, and fails if the sort is removed from `ReproducibleLayerBuilder`.
Aside: this would have been easier if we could create `LayerEntry`s without needing explicit file content.
> Test that images are reproducible

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
Follow-on to #1669 to explicitly test image manifest and configuration contents, and tar contents.
> Add content tests for image

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageTarball.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/Image.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageLayers.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildResultTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/ImageTarballTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageLayersTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ImageTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslatorTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
`Image<T extends Layer>` --> `Image`
`ImageLayers<T extends Layer>` --> `ImageLayers`
Does anyone remember why they were generics, like future extensibility?
> No generics for Image<> and ImageLayers<>

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullAndCacheBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Towards #718. Also fixes #1683.
Adds a `Containerizer#setOfflineMode` to set whether or not to set offline mode. Errors out if attempting to build to a registry, or if there is missing information from the cache.
> Add offline mode to jib-core

- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/LockFileTest.java
Fixes #1695.
- No longer deletes lock file. This was causing a race condition where one thread could release a lock, another thread could acquire a lock, and then the first thread would delete the lock file, which caused the test to fail.
- Saves a reference to the original lock file output stream to prevent it from being garbage collected/closed/releasing the file lock acquired from it.
> Fix lock file failures

- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Change `DefaultCredentialsRetriever` to use the Docker `config.json`-based retriever before using inferred registry-based retrievers.
Fixes #1694
> Use Docker config.json credential retrievers before inferred retrievers

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Fixes #1646.
I don't feel it's worth adding extra code to actually distinguish OCI vs Docker V2.2.
> Better error message for registries not supporting OCI manifest push

- jib-core/src/main/java/com/google/cloud/tools/jib/ProjectInfo.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutput.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutputTest.java
Add a `version` field to the JSON object output by the `skaffold-files-v2` goal so as to allow the format to evolve.  We populate this field with the Jib plugin version.
Note that the `ProjectInfo.VERSION` field is `@Nullable`, since it will be `null` when run from tests.
> Add version to skaffold-files-v2 output

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/SkippedGoalVerifier.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
Add new property `jib.containerize` to cause `jib-maven-plugin` to skip building image for all projects except for the specified module/project.  The module/project can be specified in one of three ways:
- by the relative path to the module (`path/to/module`)
- by the module's artifact ID (`:artifactId`)
- by the module's group and artifact IDs (`groupId:artifactId`)
This is intended for use by Skaffold for multi-module projects.
> Use `jib.containerize` property to only containerize specific module/project

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/MainClassFinder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/MainClassFinderTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
Towards #1428. Made `MainClassFinder` use a static method instead of requiring instantiation, and moves the class to the `api` package (this is a useful class for building the entrypoint for a Java container).
> Adjust MainClassFinder api

- jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageFormat.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
Towards #1428. Moves `ImageFormat` to api package and removes references to underlying classes.
> Move ImageFormat to api package

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildImageTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
It has been a real pain that we have to pass `appRoot` to instantiate a `ProjectProperties` instance. This was a chicken-and-egg situation: you need to know a certain project property to process and compute a correct `appRoot` value, but in order for `PluginConfigurationProcessor (PCP)` to process it correctly, it needs an instance of `ProjectProperties`.
So, to circumvent this annoyance, we had to do these unpleasant things:
- Exposed `PCP.getAppRootChecked()` as `public`, which is inconsistent with other `getXXXChecked()` families that are exclusively used by `PCP`.
- Had a different method signature for `PCP.getAppRootChecked()` from other `getXXXChecked()` families.
- Needed `TaskCommon.isWarProject()` and `MojoCommon.isWarProject()`.
- Had to call `getAppRootChecked()` at the …
> No need to pass appRoot when instantiate ProjectProperties

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
We haven't been including the all the input to the task correct (this only matter with jibBuildTar which has an `@Output` defined - all other jib tasks run always).
Also we had some weird code (BuildTarTask:83) that is cleaned up here.
Bug: https://github.com/GoogleContainerTools/jib/issues/1745#issuecomment-497333324
> Resolve input files more comprehensively on jibBuildTar

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Credential.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/CredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/RegistryImage.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/CredentialRetrievalException.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/CredentialTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/RegistryImageTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildConfigurationTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Towards #1428.
* `Credential` and `CredentialRetriever` are moved to api package
* Removed a link to `CredentialRetrieverFactory` in a javadoc
* Factories are left internal until API is finalized.
> Move Credential and CredentialRetriever to api package

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/SkaffoldInitTask.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/SkaffoldInitTaskTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/SkaffoldInitMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojoTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldInitOutput.java
Adds task/goal for skaffold-init usage that prints the `to.image` configuration and project name to be consumed by skaffold.
e.g.
```
BEGIN JIB
{"image":"gcr.io/image/name","project":"project-name"}
```
> Add internal Skaffold-init task/goal

- CONTRIBUTING.md
- examples/dropwizard/pom.xml
- examples/helloworld/build.gradle
- examples/helloworld/pom.xml
- examples/java-agent/build.gradle
- examples/java-agent/pom.xml
- examples/ktor/build.gradle.kts
- examples/micronaut/build.gradle
- examples/multi-module/build.gradle
- examples/multi-module/pom.xml
- examples/spring-boot/build.gradle
- examples/spring-boot/pom.xml
- examples/vertx/build.gradle
- jib-core/CHANGELOG.md
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/README.md
Merge after release is done.
Note: jib-core 0.10.0 version changes are in https://github.com/GoogleContainerTools/jib/pull/1766
> Update changelogs and version strings for 1.3.0

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JavaContainerBuilderTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java
This is part of #1724
This just redoes the previous behavior with a new API.
It does NOT cover: 
- "changing" dependencies marked in gradle
- "project/module" dependencies
> Update JavaContainerBuilder for multiple dep layers

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
> Maven: Split project dependencies out into their own layer

- jib-gradle-plugin/build.gradle
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TaskCommonTest.java
> Use bootWar instead of war for Spring Boot war projects

- jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageReference.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/ImageReferenceTest.java
fixes #1794 
This automatically allows gradle/maven users to supply a from.image = "scratch".
> Allow parsing of scratch as an image string

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/ProgressEventDispatcher.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
Fixes #1796.
I missed that the root progress tree should be created in the main thread. (`newChildProducer()` should not be called in child threads.)
> Fix root progress construction

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushContainerConfigurationStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
Getting a result from a `Future` invalidates Nullaway that has been extremely useful, as we can no longer enforce if `Future.get()` may return null or not. `Optional` works wonders here.
I see two steps among all may return null:
1. `RetrieveRegistryCredentialsStep` returning a `Credential`
2. `AuthenticatePushStep` returning an `Authorization`
We can leverage Nullaway checks using `Optional`.
> Leverage Nullaway checks using Optional for async step results

- jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerConnectionTest.java
- Enhance `TestWebServer` to return a given (and only given) set of responses in order.
- Emulate a proxy server response to test HTTP proxy user/password properties.
Towards #1434 (which is blocked on a new 1.30.2 release.)
Adding the test early to unblock #1808.
> Add test for proxy user/password properties

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/CheckJibVersionTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/CheckJibVersionMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/PackageGoalsMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldBindingMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/CheckJibVersionMojoTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/VersionChecker.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/VersionCheckerTest.java
Jib provides some internal goals and properties to support Skaffold’s Jib binding for Maven and Gradle. Some of the improvements to this binding cannot be made backwards compatible, and may require the user to update their version of Jib.  We need some way to detect and enforce these version requirements.
This PR:
1. Adds support to Jib's goals and tasks to define an expected or required version range as specified through a new property `jib.requiredVersion`.  This property can take two forms: a minimum version number (e.g., `1.4.0`) or a Maven-like version-range (`[1.4,2.0)`).
2. Changes the Gradle `JibPlugin#apply()` to perform a version check if `jib.requiredVersion` is set.
3. Changes the various Maven goals to perform a version check if `jib.requiredVersion` is set.
4. Adds a new …
> Introduce support for enforcing minimum Jib plugin versions

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutput.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/SkaffoldFilesOutputTest.java
Removes the `version` field from the `_skaffold-files-v2` / `_skaffoldFilesV2` output added in #1714.  This field was added in support of GoogleContainerTools/skaffold#2122 but unfortunately was proved inadequate.  We're instead introducing explicit version checks within Jib with #1813.
> Remove useless version field from skaffold-files-v2

- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
The `BuildImageMojoIntegrationTest` tests were failing as they were trying to push to Docker Hub.  I'm still not sure why it worked for me locally.
This PR fixes the `testExecute_jibRequireVersion_ok` and `testExecute_jibRequireVersion_fail` tests to push to the local docker registry on port 6000.  `_ok` is expected to succeed and so this test must explicitly set the Jib properties required to build to a local registry.  It's a bit confusing as some of these properties are set in the `pom-complex.xml` or `pom-complex-properties.xml` files.  But we're just trying to keep this test be simple.
> Fix BuildImageMojoIntegrationTest

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobChecker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointProvider.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobCheckerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPusherTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
Currently, the registry client framework has `callRegistryEndpoint()`, `call???()`, `handleResponse()`, etc. always return `@Nullable` generic results. Not only did this lead to code like below to manually suppress null warnings, but this also renders the NullAway checks largely useless.
```java
T manifestTemplate = callRegistryEndpoint(manifestPuller);
if (manifestTemplate == null) {
throw new IllegalStateException("ManifestPuller#handleResponse does not return null");
}
``` 
```java
return Verify.verifyNotNull(callRegistryEndpoint(...));
```
```java
URL putLocation = callRegistryEndpoint(...);
Preconditions.checkNotNull(putLocation);
```
`Optional` comes to the rescue, as in #1804.
> Leverage NullAway checks with Optional for registry client framework

- jib-core/src/test/java/com/google/cloud/tools/jib/MultithreadedExecutor.java
Note this class is test code under `src/test`.
Fixes #1845.
> Increase Timeout in MultithreadedExecutor

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLogger.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/SingleThreadedExecutor.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooterTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLoggerTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/SingleThreadedExecutorTest.java
Fixes #1839. Unlike #1846, `SingleThreadedExecutor` is not code only for testing, so I'm retaining the same 1-sec timeout in prod.
> Increase executor shutdown timeout in tests

- .github/ISSUE_TEMPLATE.md
- docs/faq.md
Fixes #1860.
Tweaked the ISSUE_TEMPLATE to:
- add note to verify with latest version, and shortened the header by directing to the FAQ
- move the environment section to the top and include explicit call outs to Jib version and build tool info
Reorganized the FAQ:
- grouped questions relating to about-images, how-tos and common-problems. 
- made the _How can I diagnose problems pulling or pushing from remote registries?_ question into a central registry-errors section.
- fixed level of the _Where is bash?_ question
- extra directory -> extra directories
> Tweak issue template and reorganize FAQ

- .travis.yml
We are hitting build failures as Travis cannot install Oracle JDK 8. It is not available on Xenial, so one way to resolve this is to stay on Trusty. Switching to openjdk8 is another option, but it will hit the Javadoc-related bug. There does exist a workaround (modifying our Javadoc to have fully qualified class names for nested classes) for the Javadoc bug, but I don't really like that.
> Stay on Ubuntu Trusty on Travis for oraclejdk8

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
Towards #1468. Adds a `DockerClient` method to `docker save` a specified image to the specified path.
> Add save to DockerClient

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ObtainBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PreparedLayer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayerStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/ObtainBaseImageLayerStepTest.java
Fixes #1867. Turns out this is not complicated at all.
> Use tri-state enum for blob existence in target repository

- jib-core/CHANGELOG.md
- jib-core/build.gradle
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/build.gradle
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/pom.xml
- jib-plugins-common/build.gradle
They tracked that `org.apache.httpcomponents:httpclient:4.5.7` introduced a breaking change by as part of URI normalization. There have been other reports of breakage due to the change too. Details are in https://github.com/googleapis/google-http-java-client/issues/795.
I think it is safe to force this version (https://github.com/googleapis/google-http-java-client/issues/795#issuecomment-523530986). I verified this fixes #1914 (for Maven) and full integration tests pass.
Fixes #1914.
> Force downgrading to org.apache.httpcomponents:httpclient:4.5.6 prevent URI normalization

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/TarImage.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/TarImageTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Fixes #1918. Changes the usage from `TarImage.named(...).saveTo(...)` to `TarImage.at(...).named(...)`. Throws an exception if the target image name is missing.
> Adjust TarImage API in preparation for local base image support

- build.gradle
- jib-maven-plugin/config/google-checks-no-indent.xml
delegates test actions to the gradle runner (so that they take care of setting up the gradle plugin classpath or installing the maven plugin)
also cleans up some xml that was causing red X's in eclipse
> Default test runner in idea to gradle, fix checkstyle xml

- jib-core/src/main/java/com/google/cloud/tools/jib/global/JibSystemProperties.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
skaffold uses `jib` to build and push java images. In order to track,  skaffold-jib adoption we want to add `UpstreamClient(skaffold-version)` to images pushed to GCR by skaffold via jib.
See https://github.com/GoogleContainerTools/skaffold/pull/2723 for kaniko implementation.
If upstreamClient is present, it will added to the user-agent when pushing to registry
> Add `upstreamClient` property to jib which tools using jib to build and push images can use.

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooterTest.java
Fixes #1952.
Instead of moving the cursor up one line, this moves it up two lines and then down one line to overwrite the previous Maven prefix left by the footer that got erased.
> Fix footer display

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageTarball.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
> Add progress events to LoadDockerStep

- jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageWriterTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
Fixes #1944. 
The issue assumed several blobs close their output streams, contrary to the javadoc in `Blob`, but this wasn't true (several implementations like `FileBlob` close the input stream, not the output stream). `Blobs#compress` does contradict the javadoc, but since this is only used in tests, I just decided to update the javadoc for `compress` and add `@VisibleForTesting` instead of changing the original `Blob` javadoc.
> Update Blobs#compress javadoc

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfig.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigTest.java
- jib-core/src/test/resources/core/json/dockerconfig.json
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #1819.
This is actually more than that. The priority is now `credHelper` --> `credsStore` --> `auths`. According to https://github.com/moby/moby/pull/25851 (and assuming it wasn't reverted), looks like at least `credHelper` should take precedence over `credsStore`:
> This change adds a "credentialHelpers" member to the config file where users can specify credential helpers on a per-registry basis. This does not over-load the "credsStore" field, which now acts as the 'default' credential store in the event that one is not explicitly specified for the registry in question.
Also, I've lifted the restriction that there should be a matching `auths` registry entry for `credsStore` to be returned. The practice to define an empty `auths` entry is documented in …
> Reorder priority for retrieving auth from Docker config (~/.docker/config.json)

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojoTest.java
Quick idea to fix https://github.com/GoogleContainerTools/skaffold/issues/2844.
Instead of running `jib:_skaffold-init` separately on every module including the root project, we use an aggregator to run the goal once across all modules. This lets us more easily detect the root project, which helps prevent `skaffold init` from setting the `module` field when we don't want it to.
The problem with this approach is that using an aggregator makes getting the `<to><image>` configuration on sub-projects harder; in this case we can only parse it from the configuration block and ignore system properties.
wdyt?
> Fix skaffold init for multimodule maven projects

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ObtainBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayerStep.java
It was incorrectly saying "application layers" even for the base image layers.
And for the timer messages, the message "preparing pushers/pullers/builders" makes sense, but I just realized the word "preparing" doesn't really fit for the progress update. Closing the progress dispatcher doesn't competes the progress in this method. Rather, the progress becomes complete (100%) when their children are complete. So I'm retaining "preparing" for the timer but changing to "launching" for progress.
> Update progress and timer messages

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/global/JibSystemProperties.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
part of #1967, take a look at where the warning is happening, open to suggestions on other ways to do this.
> Change jibSerialize to jib.serialize

- jib-core/src/main/java/com/google/cloud/tools/jib/event/progress/Allocation.java
- jib-core/src/test/java/com/google/cloud/tools/jib/event/progress/AllocationTest.java
Fixes #1972.
I think setting the minimum unit to 1 still makes sense; the progress dispatcher in this case would represent the task as a work to be completed. Also, dividing by 0 makes `fractionOfRoot` infinity, so it's better to avoid it. 
And it should definitely divide the parent fraction by `this.allocation` instead of the argument `allocation`. This has to be fixed.
> Fix progress allocation when given non-positive size

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooter.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/AnsiLoggerWithFooterTest.java
Fixes #1963.
#1963 was a regression introduced in #1953 that fixed a logging issue in Maven. But it broke Gradle.
Unfortunately, I can't think of a better and safer way than to maintain two separate paths for Maven and Gradle. I restored the original trick to fix the Gradle issue.
> Fix progress bar logger for Gradle

- jib-plugins-common/build.gradle
@chanseokoh I think this is a better solution to what we discussed.
`plugins-common` shouldn't be managing dependencies that are already in `core`
I think we might be able to do the same for test dependencies in the future.
> Better dependency handling in build

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildDockerTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerClientParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenRawConfigurationTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
Fixes #1932.
This PR moves the `jib.dockerClient` configuration from `BuildDockerTask` and `BuildDockerMojo` to `JibExtension` and `JibPluginConfiguration` to be accessible from all tasks and goals, allowing users to configure the docker client for docker daemon base images.
> Move docker client configuration to all tasks and goals

- jib-gradle-plugin/build.gradle
- jib-maven-plugin/build.gradle
the SNAPSHOT dependencies are a consequence of the monolith, the
release plugin just needs to ingore those projects, ideally the
plugin wouldn't care that compileOnly dependencies are SNAPSHOTS
but whatever, they might have a reason for that.
oh also this fixes the tagging on the maven plugin
This should fix the problem for now.... also filed: https://github.com/researchgate/gradle-release/issues/310
> Fix release by ignoring SNAPSHOT deps on core/plugins-common

- jib-core/scripts/prepare_release.sh
- jib-gradle-plugin/scripts/prepare_release.sh
- jib-maven-plugin/scripts/prepare_release.sh
This is to avoid having to revert the PRs when something that should be fixed comes up during the release. It's also aligned with the current internal release doc.
> Tell to merge the PR created by prepare_release.sh script after release is complete

- jib-core/scripts/prepare_release.sh
- jib-gradle-plugin/scripts/prepare_release.sh
- jib-maven-plugin/scripts/prepare_release.sh
Noticed in #1992 that the process can cut a step by using Github's `pull/new`-style URLs.  For example, it suggested https://github.com/GoogleContainerTools/jib/pull/new/prurls for this PR.
> Use Github URLs to create PR directly

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
> Add warning for configuring mainClass/extraClasspath/jvmFlags on WAR projects

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
Fixes #1904.
The issue makes a good point about Jib having the potential to be "smarter" with its concurrency, but maybe we should open a new issue about that.
> Mark maven goals as threadSafe

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/FilesMojoV2KotlinTest.java
Fixes #2006.
After reading the [Kotlin Maven plugin reference](https://kotlinlang.org/docs/reference/using-maven.html) (especially the part "Compiling Kotlin and Java sources" for mixing Java and Kotlin code), I decided to include every `<sourceDir>` configured. Duplicates are removed.
Also this always includes the conventional default `src/main/kotlin` whether or not it exists.
I assume there is no harm in over-approximating and listing non-existing directories.
> Add Kotlin support for Skaffold-Jib integration

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ExtractTarStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ObtainBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/ExtractTarStepTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Towards #1913. This only really makes a difference for un-cached local base image layers, but it provides a decent speedup in that case. Here were the build times using maven + a clean cache on the master branch vs. these changes:
`docker://gcr.io/distroless/java` 
* master: **7.6 seconds**
* this PR: **6.8 seconds**
`docker://openjdk:8`
* master: **29.2 seconds**
* this PR: **16.4 seconds**
> Parallelize local base image compression

- examples/java-agent/build.gradle
- examples/java-agent/pom.xml
- examples/java-agent/src/main/java/example/HelloWorld.java
Update plugin versions for `examples/java-agent`, and tweak the example to listen on `$PORT` if provided, as provided by Cloud Run.
> Update examples/java-agent plugin versions

- build.gradle
There is a denial of service vulnerability in commons-compress 1.15 through 1.18. Apache recommends upgrading to 1.19 to mitigate. For reference, see here: https://lists.apache.org/thread.html/308cc15f1f1dc53e97046fddbac240e6cd16de89a2746cf257be7f5b@%3Cdev.commons.apache.org%3E
Fixes #2029
> Upgrade commons-compress to 1.19

- build.gradle
jackson-databind 2.9.9.2 is vulnerable to several deserialization vulnerabilities. The latest stable version of 2.9 (2.9.10) mitigates these.
Fixes #2031
> Upgrade jackson-databind to 2.9.10

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
The API route base can be computed and is always "server URL + /v2/".
I also noted every `getApiRoute()` implementation does not put an extra leading slash, so I updated the method in tests reflect the reality more closely. An example implementation:
```java
public URL getApiRoute(String apiRouteBase) throws MalformedURLException {
return new URL(
apiRouteBase + registryEndpointRequestProperties.getImageName() + "/manifests/" + imageTag);
}
```
> Don't pass redundant parameter

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build.gradle
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/complex-build.gradle
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/DockerClientParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/OutputFilesParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/OutputPathsParameters.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildTarMojoIntegrationTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenRawConfigurationTest.java
- jib-maven-plugin/src/test/resources/maven/projects/simple/pom-complex.xml
- jib-maven-plugin/src/test/resources/maven/projects/simple/pom.xml
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
Fixes #1561.
Adds `outputPaths` configuration block with `tar`, `digest`, and `imageId` fields for setting output file locations.
> Add configuration for custom output file locations

- build.gradle
- jib-core/CHANGELOG.md
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
The Java 14 support is out of beta, so we may as well update. Also adds the Java 13/14 support to the changelog.
> Upgrade ASM to 7.2

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
Closes #1881.
If the base image is referenced by a digest, pull the manifest only when it was never pulled. This is what we decided to do regarding the issue: https://github.com/GoogleContainerTools/jib/issues/1881#issuecomment-517401175 and https://github.com/GoogleContainerTools/jib/issues/1881#issuecomment-517683340.
> Check base image cache if referenced by digest

- jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageReader.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageReaderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageWriterTest.java
Part of `docker save` portion of #1912. Adds methods for writing/retrieving container configuration to/from the cache using an image ID.
> Add cache methods for writing/reading local base image container config

- docs/self_sign_cert.md
https://stackoverflow.com/questions/17935619/what-is-difference-between-cacerts-and-keystore
https://docs.oracle.com/cd/E19830-01/819-4712/ablqw/index.html
Therefore, it is confusing to name the truststore as `keystore`.
> Clarify keystore (keystore.jks) vs truststore (cacerts.jsk) distinction

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/ObtainBaseImageLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushBlobStep.java
Fixes #2053.
* Clarified `Getting base image...` -> `Getting manifest for base image...`
* Added logging for skipped base image layer pulls
* Clarified logging for skipped layer pushes
> Clarify log messages for skipped layers

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestAndDigest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPuller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPullerTest.java
Pull manifest now will return the digest along with the manifest of the base image. This will be helpful for logging the base image digest #1884.
Fixes - #2034
> Return both manifest and digest for pull manifest

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LoadDockerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/ImageTarball.java
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/ImageTarballTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplateTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #2043.
Adds `jib.to.tags` to tars built with jib so `docker load`ing the tar will tag the image appropriately. This also removes the need for `DockerClient#tag`, since it's done automatically now.
> Add extra tags to tar image

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TaskCommonTest.java
Avoid creating jib tasks (also dependents like jar, assemble, war, etc) when not needed.
Before,
After,
Resolves #2072
> Advanced configuration avoidance (jib-gradle-plugin)

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SkaffoldInitMojo.java
Towards #2088.
I *think* `project.name` is still the correct field to use with gradle, but I'm not 100% sure.
> Use artifact ID instead of project name in SkaffoldInitMojo

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/SkaffoldInitTask.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/SkaffoldInitTaskTest.java
- jib-maven-plugin/CHANGELOG.md
This was an issue that was fixed in #1974 on the maven side, but I forgot to change the gradle side as well.
This PR also updates the changelog for #2090.
> Fix root build.gradle being reported in skaffold init for multi-module projects

- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
This test makes two HTTP calls, but the server could only respond once. The test succeeds only after the second call times out, which is 20 seconds on my machine.
And adding a space makes the test more robust.
> Fix slow test

- jib-core/src/main/java/com/google/cloud/tools/jib/http/Request.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobChecker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ErrorResponseUtil.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPusher.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointProvider.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobCheckerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ErrorResponseUtilTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPusherTest.java
Trying to reduce the diff of the upcoming PR for changing Jib HTTP framework.
A lot of changes are renaming `httpResponseException`: I'll most likely introduce `ResponseException` that wraps `HttpResponseException` (somewhat similar like currently `Response` wrapping `HttpResponse` and `Request` wrapping `HttpRequest`), so changing variable names in advance.
> Refactoring and renaming

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
Reuse some skip logic across maven mojos, so I can resuse in the skaffold sync map goal.
part of #2097
> Move skip execution logic to MojoCommon

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TaskCommonTest.java
Fixes #2096.
~~The only thing that may matter is that now `task.dependsOn(Object...)` takes a `List`, so I'll do some actual tests to see this works as desired.~~ Works fine.
> Don't use bootWar if disabled

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
close #2086 by removing deprecated `@org.gradle.api.tasks.Optional` annotation
> remove deprecation warnings

- build.gradle
`gradlew dev`: formats the code + runs the build + runs tests
`gradle devFull`: does all of `dev` + run integration tests
`devFull` should fail fast if JIB_INTEGRATION_TEST_PROJECT is not set.
> Add "dev" and "devFull" to build

- build.gradle
We run `javadoc` on all projects in `dev` mode.
The branch name is deceptive because I was thinking differently when I initially wrote this.
> add javadoc check to dev, cleanup spaces

- jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPuller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPuller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointProvider.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/FailoverHttpClientProxyCredentialsTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/FailoverHttpClientTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerFailoverHttpClientTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/AuthenticationMethodRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
Follow-up after #2100.
Also fixes #2117.
> Finalize new HTTP framework changes

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/AuthenticatePushStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
We've been swallowing `InsecureRegistryException` when trying to auth with the registry through `RegistryAuthenticator`. I've been mulling over why we are doing this, and I think it is rather good to surface the error. For `AuthenticatePushStep`, the intention might have been to fall back and return null or basic credentials, but I still think there's no point of doing that if we get `InsecureRegistryException`. I think it's an unrecoverable situation.
I'll give it a second look later, but for now, I think it's good to surface this.
> Do not swallow insecure server exception

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageStepsTest.java
We should eventually make the step clear of `ExecutorService`, as that's the business of `StepsRunner` which will also increase concurrency (#1913), but until then, we can apply this cleanup.
But at the same time, I said I am not sure I like having `ExecutorService` in `BuildConfiguration`: https://github.com/GoogleContainerTools/jib/pull/2125#issue-337469649
> No need to pass around ExecutorService

- build.gradle
Turns out intellij doesn't care that you're using register, the sync mechanism will resolve and configure all tasks during sync.
We can't put this check with the integrationTest (`doFirst {}`) because jib-core doesn't actually need it to run integration tests (as seen in kokoro/presubmit.sh)
> remove env check for integTest so intellij sync works

- examples/dropwizard/pom.xml
This PR simply corrects one of the examples, we happened to notice it was wrong because it was the one we copied.  It would appear that the use of jmxFlag instead of jvmFlag does not cause any problems but it is confusing and might cause issues in the future.
> Corrected dropwizard-jib-example pom to use jvmFlag rather than jmxFlag.

- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TestProject.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
`GRADLE_MIN_VERSION` is 4.9.
Verified one of the tests fails if Gradle 5 API is used.
> Set Gradle version to run in integration tests

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/CheckJibVersionTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/InitTask.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TestProject.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2Test.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/skaffold/InitTaskTest.java
This is a reorganization of skaffold related classes into a skaffold package (similar to how the maven plugin is organized), makes some task names public (which I think is okay, for users that want to directly reference those names).
> Put skaffold classes in skaffold package

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushLayerStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageStepsTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #1913.
This PR splits up the local base image steps so that the base image layer futures are returned before the layers are actually processed. This means later steps with dependencies on the base image layers can start as soon as each layer finishes being compressed, rather than waiting for all layers to be compressed before continuing.
Amount of time save varies depending on the base image, but it seems to save 4 seconds for uncached distroless (15s -> 11s).
> Allow pushing local base image layers immediately after compressing

- docs/faq.md
The special keyword USE_CURRENT_TIMESTAMP is missing an underscore, preventing it to be copied and used.
> Missing underscore in FAQ for USE_CURRENT_TIMESTAMP

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
See #2175.
However, I can never figure out why the test doesn't pass on the Travis Java 11 build. Doesn't make sense to me. Still looking into it.
> Use ConsoleLogger instead of native Gradle logger

- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
- jib-maven-plugin/src/test/resources/maven/projects/spring-boot/pom.xml
- jib-maven-plugin/src/test/resources/maven/projects/spring-boot/src/main/java/hello/Application.java
- jib-maven-plugin/src/test/resources/maven/projects/spring-boot/src/main/java/hello/HelloController.java
Implements https://github.com/GoogleContainerTools/jib/issues/1852#issuecomment-557275771 for Maven. That is, auto-detect Spring Boot fat-JAR repackaging and use the original thin JAR.
Additionally takes care of the corner cases with `<classifier>` and `<outputDirectory>` from `maven-jar-plugin`. This is basically irrelevant of the Spring Boot fat JAR stuff, but I decided to fix them for correctness.
> Detect Spring Boot fat-JAR repackaging and use original thin JAR

- kokoro/continuous.sh
I removed this in #2186, since it worked on macOS without it. Turns out, this is still required on Ubuntu. I confirm this works.
> Fix Kokoro Ubuntu

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2.java
Because configurations were changed in Gradle 5, existing implementation fails to detect dependencies between project modules.
> Use correct configuration for Skaffold dependencies

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/SyncMapTask.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/skaffold/SyncMapTaskTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojoTest.java
This is to potentially protect us from the case where we run sync and files tasks together.
> Use a different marker so we don't clash with other jib json outputs

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RetrieveRegistryCredentialsStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactoryTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
Fixes #2056.
```
[INFO] Using credentials from Docker config (/usr/local/home/guest/.docker/config.json) for francium25/test
```
```
[INFO] Using credential helper docker-credential-gcr for gcr.io/project/repo
```
```
[INFO] Using credentials from Maven settings file for gcr.io/project/repo
```
```
[INFO] Using credentials from <from><auth> for gcr.io/project/repo
```
```
[INFO] Using credentials from from.auth for gcr.io/project/repo
```
Overall, it will look like
```
[INFO] Containerizing application to francium25/test...
[WARNING] Base image 'gcr.io/chanseok-playground-new/test' does not use a specific image digest - build may not be reproducible
[INFO] Using credentials from Docker config (/usr/local/home/guest/.docker/config.json) for francium25/test
[INFO] The base image requires …
```
> Display where Jib got credentials for base and target images

- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/BuildableManifestTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/V22ManifestTemplateTest.java
- jib-core/src/test/resources/core/json/v22manifest_optional_properties.json
See #2215. This prevents Jib from crashing when `urls` is given.
`annotations` was already being retrieved. Added `urls` in the same way.
> Do not fail when "urls" field is present in manifest JSON

- jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/XdgDirectories.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/XdgDirectoriesTest.java
Fixes #2216.
Adds methods for retrieving the config directory:
* Linux: `$HOME/.config/google-cloud-tools-java/jib/`
* Mac: `$HOME/Library/Preferences/Google/Jib/`
* Windows: `%LOCALAPPDATA%\Google\Jib\Config`
Also changes the cache directory on Mac/Windows to the following:
Before:
* Mac: `$HOME/Library/Application Support/google-cloud-tools-java/jib/`
* Win: `%LOCALAPPDATA/google-cloud-tools-java/jib/`
After:
* Mac: `$HOME/Library/Caches/Google/Jib/`
* Win: `%LOCALAPPDATA\Google\Jib\Cache\`
Linux is still at `$HOME/.cache/google-cloud-tools-java/jib/`. Will need to update documentation to help users migrate the old cache over to the new location.
> Change base image cache location on mac/windows, add methods for getting XDG config location

- docs/faq.md
Docs for #2183
Closes #2183
Rendered: https://github.com/GoogleContainerTools/jib/blob/loosebazooka-patch-1/docs/faq.md
> Update faq for class not found / method not found

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentials.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenSettingsServerCredentialsTest.java
- jib-maven-plugin/src/test/resources/maven/settings/settings.xml
This PR is a suggestion to fix #2135 
It changes the lookup of the server information from the Maven settings to ignore the port information from the registry.
It splits the registry information at the (last) colon and extracts the substring before it:
`docker.example.com:12345` would match with the server id `docker.example.com`
I've tried to run as many integration tests as possible (but those working with the docker daemon didn't run on my Fedora 31 with podman).
> Ignore registry port when inferring auth from maven settings

- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> Update changelog for json image metadata file

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
We should probably set up kokoro to run integration tests every night or something.
> fix output matches for integration test

- build.gradle
see: https://github.com/JetBrains/gradle-idea-ext-plugin/pull/89
> Upgrade idea-ext to 0.7, removes deprecated gradle api usage

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
This introduces a new lifecycle task called `jibDependencies` (the name can really be anything, that was just what I came up with) that all the jib tasks depend on and it in turn depends on any requisite tasks / configurations. Being a lifecycle task, it doesn't have any task action itself and essentially exists as a convenient hook for other dependencies. In particular, `jibDependencies` will depend on the `war`/`bootWar` tasks  when applicable, the `jar` task when applicable, and always depends on the projects `runtimeClasspath` configuration.
Gradle allows tasks to depend on `FileCollection`s (rather than just tasks). When doing so Gradle expands the task graph expands to include all the necessary tasks to produce the files listed in the `FileCollection`. Doing so with the …
> Replace assemble task dependency with runtimeClasspath

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #2258.
If the server returns unexpected `WWW-Authenticate` responses  when attempting to refresh a bearer token, fall back to use the initial authenticator that succeeded to get the first token. `RegistryAuthenticator` is immutable and safe to reuse.
And fixing this will naturally make Jib to surface 401 eventually after 4 refresh attempts fail when the initial token did not have enough access scope.
> Fall back to initial authenticator if bad response

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageStepsTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/DockerClientTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #2270.
`docker inspect` returns an array, so I had to do `docker inspect -f {{json .}}` at least.
Actual command output looks like this and capitalization in JSON properties matters.
```
{                                                                                                      
"Id": "sha256:ccc6e87d482b79dd1645affd958479139486e47191dfe7a997c862d89cd8b4c0",
...
"Size": 64194748,
...
"RootFS": {
"Type": "layers",
"Layers": [
"sha256:43c67172d1d182ca5460fc962f8f053f33028e0a3a1d423e05d91b532429e73d",
...
]
},
...
}
```
> Deserialize entire "docker inspect" JSON output

- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java
Enable POSIX big-file records to support packaging arbitrarily large large files.  This setting is used by the [Spotify docker-client library](https://github.com/spotify/docker-client/blob/14b4464fb7acec25073c8c9c564136188f94562c/src/main/java/com/spotify/docker/client/CompressedDirectory.java#L114).
> Use POSIX long file mode to support enormous files

- config/checkstyle/checkstyle-suppressions.xml
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperIntegrationTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/hash/CountingDigestOutputStreamTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/V22ManifestListTemplateTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/BlobPusherTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/TimerEventHandlerTest.java
- AbbreviationAsWordInName
- WhitespaceAround
- NonEmptyAtclauseDescription
part of #2272
> More checkstyle fixes

- jib-maven-plugin/build.gradle
Originally manifests in:
[com.google.cloud.tools.jib.maven.TestRepository:51](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/TestRepository.java#L51-L52)
Something in the plexus libraries is loading the slf4j logger,
this just cleans up the error message from not having an actual
binding.
```
com.google.cloud.tools.jib.maven.MavenProjectPropertiesTest > testGetJarArtifact STANDARD_ERROR
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I figured using a simple logger (vs nop-logger) was better so
we could get some log feedback if it happened to pop up.
> Add slf4j implementation to tests

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/TestProject.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2Test.java
- jib-gradle-plugin/src/test/resources/gradle/projects/platform/build.gradle
- jib-gradle-plugin/src/test/resources/gradle/projects/platform/platform/build.gradle
- jib-gradle-plugin/src/test/resources/gradle/projects/platform/service/build.gradle
- jib-gradle-plugin/src/test/resources/gradle/projects/platform/service/src/main/java/com/test/HelloWorld.java
- jib-gradle-plugin/src/test/resources/gradle/projects/platform/settings.gradle
Fixes #2269
java-platform modules cause existing implementation to fail in two ways:
- they don't have runtimeClasspath configuration and for a good reason, you don't always want to pick up ALL platform dependencies
- they don't have a source set nor `JavaPluginConvention` plugin
I've tested the patch on my project and "skaffold build" is working correctly now.
> Do not recurse into java-platform dependencies in Skaffold task

- jib-gradle-plugin/build.gradle
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Fixes #2278.
See https://github.com/GoogleContainerTools/jib/issues/2278#issuecomment-584404686.
> Set classifier of jar task for Gradle Spring Boot projects only when safe and needed

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
This fixes a bug where user-configured task dependencies (`tasks.jib.dependsOn '...'` immediately after `jib {}` section) are overwritten by the plugin.
> Do not overwrite Gradle task dependencies

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/UpdateCheckerTest.java
I may keep looking into #2294 to see if I can somehow reproduce the error without intentionally creating an empty config file, but this should avoid the warning message in the meantime. Empty config files are now treated as empty, meaning they will be regenerated with defaults.
> Treat empty update check config as non-existent

- config/checkstyle/checkstyle-suppressions.xml
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperTest.java
- MemberName
- OverloadedMethodDeclarationOrder to "ignore" as it conflicts with
historic Jib style
Parts of #2272
> Back at it again with the checkstyle

- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
I think as far as we can go for #1945 
fixes #1945
> Put links to multimodule example in maven/gradle docs

- jib-gradle-plugin/scripts/prepare_release.sh
- jib-gradle-plugin/scripts/update_gcs_latest.sh
- jib-maven-plugin/scripts/prepare_release.sh
- jib-maven-plugin/scripts/update_gcs_latest.sh
Corrects the relative paths for the GCS update scripts, since the release scripts are run from the root project directory.
> Fix release script text

- README.md
- jib-maven-plugin/README.md
They seemed to have changed how they do this:
https://shields.io/category/version and look for maven central
> Fix maven version badge

- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
> Allow more timezone formats

- jib-maven-plugin/build.gradle
Sorry, I removed this in #2323, but turns out it suppresses some warnings.
```
> Task :jib-maven-plugin:compileTestJava                                                                                                                                                                           
warning: unknown enum constant ResolutionScope.COMPILE_PLUS_RUNTIME                                                                                                                                                
reason: class file for org.apache.maven.plugins.annotations.ResolutionScope not found                  
warning: unknown enum constant ResolutionScope.NONE                                                      
warning: unknown enum constant ResolutionScope.NONE …
```
> Fix test source compile warnings in jib-maven-plugin

- jib-core/src/main/java/com/google/cloud/tools/jib/api/AbsoluteUnixPath.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/FilePermissions.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerEntry.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Port.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/RelativeUnixPath.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/UnixPathParser.java
I plan to copy these classes into the jib-build-plan project, where we won't depend on Guava.
> Remove Guava dependency from certain core API classes

- build.gradle
- force evaluation of dependencyProject
- actually do the right kind of removal (perhaps this changed with gradle update?)
this will be caught by forcing evaluation now.
> Fix sourceProject helper

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerEntry.java
The `@deprecated` javadoc annotation allows surfacing recommendations to be use by tools.
> Use @deprecated javadoc

- jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildContext.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildAndCacheApplicationLayerStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageStepsTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/RegistryCredentialRetrieverTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildContextTest.java
No public API is affected.
`JibContainerBuilder.toBuildContext()` is already throwing `CacheDirectoryCreationException`, coming from `Containerizer.getApplicationLayersCacheDirectory()` and `Containerizer.getBaseImageLayersCacheDirectory()`.
I noticed the `IOException` from `BuildContextBuilder.build()` is only from creating cache directories, so I figured it is reasonable to make them align.
> Make BuildContext builder throw CacheDirectoryCreationException

- build.gradle
goJF was running after checkstyle which is dumb. This should make auto formatting run before checkstyle so it does break for no good reason.
> make googleJavaFormat run earlier in 'dev' mode

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
> Fix wrong hashCode() in ContainerConfiguration

- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FileEntriesLayer.java
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/LayerObject.java
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/buildplan/ContainerBuildPlan.java
- jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlanTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
The class works as the forefront Java interface for the proposed [Build Plan specification](https://github.com/GoogleContainerTools/jib/blob/2b2fe82ad0552ba3ce1de308a0fda24aab684365/proposals/container-build-plan-spec.md).
This setters share some similarities with those of `JibContainerBuilder`. Most Javadocs are copied over after minor tweaks.
> Add ContainerBuildPlan as Build Plan API interface

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelperTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Fixes #1200.
Can now use glob patterns when setting extra files permissions. Permissions configured with explicit paths will take priority over globs (e.g. if both `'/a/b/file': '777'` and `'**/file': '444'` are configured, `/a/b/file` will have `777` permissions, and all other files named `file` will have `444` permissions).
If a file matches multiple globs (e.g. if there's a file `/a/b/file`, and permissions are configured for both `/a/b/*` and `**/file`), ~~behavior is undefined at the moment~~ first configured match wins.
> Add glob support for extra file permissions

- build.gradle
- jib-maven-plugin/build.gradle
Comparing [maven-core](https://search.maven.org/artifact/org.apache.maven/maven-core) and [maven-compat](https://search.maven.org/artifact/org.apache.maven/maven-compat) releases, I think they should match.
> Sync Maven API versions in project build

- jib-core/src/main/java/com/google/cloud/tools/jib/ProjectInfo.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildContext.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildContextTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildDockerMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildImageMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/BuildTarMojo.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojo.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
fixes #1716
I think I also need this for #2350 (`XYZ.class.getPackage()` can return weird results if two jars use the same packaging [like `com.google.cloud.tools.jib`]) -- this is the source of the integration test error in that pr.
> Push out project version setting to tool

- docs/faq.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TaskCommon.java
Fixes #2356.
One of the ways to have a custom logger is through the system property `java.util.logging.config.file`. If it's defined, don't disable Google HTTP Client logging.
> Do not disable Google HTTP Client logging for custom logger in Gradle

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/LayerDefinitionParserTest.java
For some systems/jdks, the `java.io.File` api truncates the last 3 digits of `File.lastModified()`.
Use `java.nio.Files` instead.
this passes in the CI but break on my laptop: adopt openjdk `jdk8u242-b08`
> Fix last modified time test

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
Adds internal methods for conversion between `JibContainerBuilder` <--> `ContainerBuildPlan`. I can't think of other ways to enable this conversion while not adding public methods to `JibContainerBuilder`.
As we currently build a `JibContainerBuilder` instance (which is the front-end public API) in our plugins code, the idea for the extension framework is basically like this:
1. Construct `JibContainerBuilder` (current behavior).
1. Convert `JibContainerBuilder` to `ContainerBuildPlan` and pass it to extensions.
1. Extensions modify the `ContainerBuildPlan`.
1. Convert `ContainerBuildPlan` back to `JibContainerBuilder`.
1. Plugins code proceeds with `JibContainerBuilder` to build an image (current behavior)
Another approach would be to revamp everything around `BuildContext` and …
> Build plan adapter methods for JibContainerBuilder

- jib-build-plan/build.gradle
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- Returns copies of collections to achieve absolute immutable. I missed some fields by mistake.
- Fixes wrong OSGi package export in `jib-build-plan`.
Misc:
- Removes the deprecated `describeContainer`.
- Ensure type before casting; we can remove `@SuppressWarnings`.
> Return copies instead of exposing internal collections / and more

- build.gradle
- jib-core/src/main/java/com/google/cloud/tools/jib/api/MainClassFinder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/BuildableManifestTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/OciIndexTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/OciManifestTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V22ManifestListTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V22ManifestTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/MainClassFinderTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
- mark unused variable in jsontemplates
- rename conflicting type: Type (`org.objectweb.asm.Type` and `MainClassFinder.Result.Type`)
- although this could also just be fixed using fqn of the types.
> fix more error prone issues

- jib-build-plan/settings.gradle
- jib-core/settings.gradle
- jib-gradle-plugin/settings.gradle
These don't do anything of use, we always run gradle from the root. And we *should* always run gradle from root.
further reading: https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/Settings.html
> Remove useless settings.gradle files

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
We were calling `.setFormat()` only when `jib:build` and `jib:buildTar`. For `jib:dockerBuild`, we relied on the assumption that the default format of `JibContainerBuilder` is Docker. However, I think it's cleaner to enforce consistency; it's more natural to override the config when the goal is `jib:dockerBuild`.
> Always set image format configuration

- jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageReference.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/ImageReferenceTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
`ImageReference.scratch().toString()` was returning `/scratch` (with the leading slash).
Also cleaned up some test code.
> Fix ImageReference.toString() for "scratch"

- CONTRIBUTING.md
- build.gradle
- jib-gradle-plugin/build.gradle
- update plugin version
- We had to update from 10.1 -> 11.0 because they were no longer supporting the 10.1 based publishings (https://blog.gradle.org/plugin-portal-update)
- use syntax from https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/
- This full syntax is required for local publishing to work correctly
- update local development workflow
I tested this release process and it seems to work fine.
> Update gradle plugin publishing

- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageReference.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildContext.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageTarball.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/ImageReferenceTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildContextTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunner.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Fixes #2390. If the digest is set, the tag may now be null, rather than taking on the default value of `latest`. If neither the tag nor digest is specified in the creation of the `ImageReference`, then it will use the default tag `latest`.
We used digest and tag interchangeably throughout the codebase before this change, so it's possible I maybe have missed something small. To make this easier, I added two methods: `getQualifier()` and `withQualifier()`, which use the old behavior of `getTag()` and `withTag()`.
> Allow null tags

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenExtensionData.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenExtensionLogger.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
Using the standard Service Provider Interfaces (SPI) mechanism to load and run Maven plugin extensions.
This doesn't yet involve the new extension config option (like `<extensions><extension><implementation>com.example.ExtensionClass`). The config option can be added in a later PR.
With this, we are actually enabling running and testing Maven extensions. A configuration will look like this.
```xml
<plugin>
<groupId>com.google.cloud.tools</groupId>
<artifactId>jib-maven-plugin</artifactId>
<version>2.1.1-SNAPSHOT</version>
<dependencies>
<dependency>
<groupId>com.example</groupId>
<artifactId>quarkus-extension-maven</artifactId>
<version>0.1.0-SNAPSHOT</version>
</dependency>
</dependencies>
</plugin>
```
> Run Maven plugin extensions

- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Part of #1618. Maybe we can follow-up with some sort of `jib.docker.config` system property (config parameter might not make sense since this path is platform dependent).
> Respect DOCKER_CONFIG environment variable when finding credentials

- CONTRIBUTING.md
- jib-gradle-plugin/build.gradle
Adds `install` task to jib-gradle-plugin build.
> install shortcut for gradle plugin

- build.gradle
- jib-build-plan/build.gradle
- jib-core/build.gradle
- jib-gradle-plugin-extension-api/build.gradle
- jib-gradle-plugin-extension-api/gradle.properties
- jib-gradle-plugin-extension-api/settings.gradle
- jib-gradle-plugin-extension-api/src/main/java/com/google/cloud/tools/jib/gradle/extension/GradleData.java
- jib-gradle-plugin-extension-api/src/main/java/com/google/cloud/tools/jib/gradle/extension/JibGradlePluginExtension.java
- jib-maven-plugin-extension-api/build.gradle
- settings.gradle
Continued work on establish the Jib plugin extension framework.
- Sets up a sub-project for Gradle plugin extension (counterpart of #2368)
- Defines Gradle plugin extension API (counterpart of #2380)
```
ContainerBuildPlan extendContainerBuildPlan(
ContainerBuildPlan buildPlan, GradleData gradleData, ExtensionLogger logger)
throws JibPluginExtensionException;
```
One problem due to a difference from Maven: while the Maven Core API was defined with
```
dependencies {
api "org.apache.maven:maven-core:${dependencyVersions.MAVEN_API}"
```
here the Gradle API dependency is though applying `java-gradle-plugin`.
```gradle
plugins {
id 'java-gradle-plugin'
```
The problem (I think) is that the Gradle API version is not pinned. So the Gradle version that the extension dev uses will determined the …
> Set up sub-project for Gradle plugin extension and define extension API

- docs/faq.md
Add faq entry, so we can link to it for failing builds.
Using example provided in: #2148
> Add entry in faq for manifests lists

- docs/faq.md
I've been repeating this in comments too many times.
> Add HTTP request/response sample logs in FAQ

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
> improve manifest list error message with help links

- jib-gradle-plugin/build.gradle
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleExtensionLogger.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
Gradle counterpart of #2397.
Using the standard Service Provider Interfaces (SPI) mechanism to load and run Gradle plugin extensions.
This doesn't yet involve the new extension config option (like `jib.extensions=[ { implementation='com.example.ExtensionClass' }]`). The config option can be added in a later PR.
With this, we are actually enabling running and testing Gradle extensions. Extensions should be added to the classpath of the Gradle build script. Extensions added in this way apply to all sub-modules in a multi-module project, so we do need the new config option in the end.
```gradle
buildscript {
dependencies {
classpath 'com.google.cloud.tools.jib.plugins.extension.gradle.quarkus:quarkus-extension-gradle:0.1.0-SNAPSHOT'
}
}
```
> Run Gradle plugin extensions

- jib-gradle-plugin/build.gradle
- jib-maven-plugin/build.gradle
We are not yet publishing these artifacts to Maven Central. Will ignore SNAPSHOT versions for now.
> Ignore SNAPSHOT dependencies of plugin extension sub-projects when publishing

- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesExtensionTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesExtensionTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
`MavenProjectPropertyTest` was >1100 lines, and it's likely that we'll add more plugin extension test code. Moving tests to new classes.
> Move plugin extension tests to a new class

- jib-gradle-plugin/build.gradle
This prevents maven-publish from messing with plugin-publish
fixes #2424 (more specifically addresses the bug at: https://discuss.gradle.org/t/debug-an-issue-in-publish-plugin-gradle-plugin-not-being-prepended-to-groupid/32720)
I also tested the plugin release process, and it goes back to the normal behavior.
> Conditionally allow installs of local SNAPSHOT

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #2421.
I think we never inherited USER.
> Inherit USER from base image

- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
`<extensions>` --> `<pluginExtensions>`
This is to match parity with Gradle as explained in https://github.com/GoogleContainerTools/jib/pull/2431#issue-409784549.
> Rename Maven extension config name

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/MainClassResolverTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Fixes #2456.
The logic has changed:
1. main class explicitly configured (via `jib.container.mainClass`) but invalid
- before: attempted to infer a main class under `src/`.
- problems and weirdness:
- never looked into mainClassFromJar despite checking `src/` (inconsistency)
- configured `jib.container.mainClass` ignored if a valid main is found under `src/', no warning at all
- after: error
2. main class not configured, invalid mainClassFromJar, and no or multiple mains found under `src/` (i.e., the only main class we could ever get is from the jar-plugin)
- before: warned mainClassFromJar is invalid, but proceeded with it (this mainClassFromJar used to be called "backup" in our tests)
- after: error
So, the case in #2456 falls into 2) with multiple mains, and now Jib will fail while …
> rework main class finding

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-extra-dirs3.gradle
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/src/main/java/com/test/HelloWorld.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BuildTarTask.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoriesParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoryParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoryParametersSpec.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
Fixes #1581. Adds the following to the gradle configuration:
```
jib.extraDirectories.paths {
path {
from = 'from/path'
into = '/'
}
path {
from = 'another/path'
into = '/target/directory'
}
}
```
The old configuration also still works:
```
jib.extraDirectories.paths = ['from/path', 'another/path']
```
> Add gradle extra directory target configuration

- examples/micronaut/build.gradle
- examples/micronaut/gradle.properties
Upgrade Micronaut to a recent version.
This sample is used in the [Jib + Micronaut + Kubernetes codelab](https://codelabs.developers.google.com/codelabs/cloud-micronaut-kubernetes).
Fixes #2468
> Update Micronaut to a recent 2.0 version

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java
Fixes #2348. Writes the timestamp to a temp file and does an atomic move (if possible) to avoid interrupting the timestamp file overwrite.
> Fix potential update checker timestamp file corruption

- jib-build-plan/CHANGELOG.md
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FileEntriesLayer.java
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/FileEntry.java
- jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/FileEntriesLayerTest.java
- proposals/container-build-plan-spec.md
Towards writing an extension for #1257 and #1955, as well as a workaround for #1270.
Once merged, we need to re-publish all the libraries one after another.
> Update Build Plan API to accept file ownership in layers

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesExtensionTest.java
I realized we [need to inject the Gradle project](https://github.com/GoogleContainerTools/jib-extensions/pull/7/files#diff-bad2ecb1f14b7db185ced1687bb8cfa6R108-R111) when instantiating an extension-specific config object.
> Inject Gradle project when creating extension-specific config object

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelperTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrieversTest.java
Fixes #2527 
The logic to determine whether a file does not exist isn't reliable; in #2527, the exception message was localized. (Note the logic wasn't changed in #2403. We had it like that from the beginning.)
However, I think we still have to rely on `CredentialHelperNotFoundException`. Otherwise, when attempting multiple filenames (.cmd, .exe., no file ext), there's no way to distinguish which one failed because of a wrong filename, insufficient permissions, or an IO error while running.
> Also try .exe for cred helpers on Windows

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
This is a temporary workaround. Pin dockerhub registry contianer image to 2.7.0.
core issue: https://github.com/docker/distribution-library-image/issues/106
> Temporary fix for registry not having htpassword

- build.gradle
- jib-core/build.gradle
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
Turn out you must use bcrypt. md5 doesn't work for registry even if the htpasswd file is right.
The jbcrypt java library uses $2a$, not $2y$ (described in htpasswd docs: https://httpd.apache.org/docs/2.4/misc/password_encryptions.html), but $2y$ vs $2a$ doesn't seem to matter (integration tests passing).
core issue: docker/distribution-library-image#106
longterm solution for: #2538 
fixes #2537
> Programmatically generate htpasswd file

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
> Solved : NPE if the server doesn't provide any HTTP content for an error

- build.gradle
Dependabot upgraded it to 2.4.0 in #2553, but I already have PR #2510 that's not yet ready due to a bug in 2.4.0.
> Revert Error Prone back to 2.3.4 that Dependabot upgraded to 2.4.0

- build.gradle
instead of only being able to run `./gradlew dev` (behavior unchanged)
we can now also run this per module `./gradlew jib-cli:dev`, which is useful when only touching one module.
> Refactor 'dev' and 'devFull' to per project

- jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java
Solves: https://github.com/GoogleContainerTools/jib/issues/2585
> Use SystemSocketFactory instead of the default factory for SSL socket factory

- jib-core/src/test/java/com/google/cloud/tools/jib/http/TestWebServer.java
`serverSocket.getInetAddress().getHostAddress()` returns `0.0.0.0` (in the IPv4 case) because the server socket [binds the port to all network interfaces](https://stackoverflow.com/questions/11097189/is-binding-to-0-0-0-0-in-java-guaranteed-to-bind-to-all-network-interfaces). (That is, connection is accepted through any network interface addresses.)
However, `getEndpoint()` is meant to return an address that an HTTP client should use to connect to the server. Although using `0.0.0.0` as a destination address for a localhost often works, it is actually wrong to use it. `0.0.0.0` is a special address that is only meant for source, not destination:
https://stackoverflow.com/a/3655736/1701388
https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml
Since …
> Make local test web server always return a loopback address

- jib-build-plan/CHANGELOG.md
- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java
- jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlanTest.java
- jib-core/CHANGELOG.md
This PR fixes the default platform in our api from ` linux/amd64` to `amd64/linux`
> Fixing the default platform in the build plan api

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/CopySpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Validator.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/LayerSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/ValidatorTest.java
- Only check required values
- Add validator class with standard error messages
- Add in tests for value validation
Why not `@JsonInclude`?
Because `@JsonCreator` and `@JsonInclude` do not work at all
with eachother. We use `@JsonCreator` since it handles **required** fields
and we can validate non-null, non-empty at creation time. Using `@JsonInclude`
with jackson bean initialized of fields (vs creator) would give us access
to automatic non-null, non-empty validation, but we would have to push
our own **required** infrastructure. This cannot happen at yaml parse time, and
would happen after parsing in some sort of post-parsing step (or there is some
jackson validation framework that I was unable to find). I find the
`@JsonCreator` workflow slightly cleaner.
part of #2570
> Add validation to required yaml properties

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- jib-build-plan/build.gradle
- jib-cli/build.gradle
- jib-core/build.gradle
- jib-gradle-plugin-extension-api/build.gradle
- jib-gradle-plugin/build.gradle
- jib-maven-plugin-extension-api/build.gradle
- jib-maven-plugin/build.gradle
- jib-plugins-common/build.gradle
Modify the main build.gradle and related build files to reference the full dependency data instead of just the version. This change attempts to make our dependency info more friendly with dependabot, which is currently unable to parse through our dependencies.
For #2602
> Modify dependencies info to include the full dependency path instead of just the version

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/CopySpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpec.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpecTest.java
- entrypoint and cmd are still optional as we have to
differentiate between the user trying to erase a
base image value vs not setting anything.
Doing some more thinking and reading about this (https://github.com/GoogleContainerTools/jib/pull/2598#discussion_r456577550). It seems like using optional for collections is probably not great, except in the case of entrypoint and cmd.
> Convert most collections to empty instead of optional

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/AbstractManifestPuller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPullerTest.java
This enables `ManifestPuller` (and `ManifestChecker`) pulling a Docker manifest list for any image reference (hence ultimately enabling Jib to do so). Previously, Jib was pulling a manifest list only when the image reference used a digest.
> Adding the V22ManifestListTemplate media type to the list of supported manifest files

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpec.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpecTest.java
`os` and `architecture` are required when defining a platform.
part of #2570
> Make os and architecture required in PlatformSpec

- jib-maven-plugin/README.md
Update docs for hint about aws ecr 
Helps on #2627
> Update README on authenticating using jib.to.auth.username|password with major cloud registries

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
This PR adds support for a user to specify the platform he/she wants to use when building an image
> Adding support for PullBaseImageStep to search a manifest list using a user specified os/arch pair

- CONTRIBUTING.md
Includes additional steps to follow if a user is using a GCP project to run integration tests.
> Update contributor docs to include more details on running integration tests. 

- docs/faq.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
I came across to some people who didn't realize `<permissions>` supports glob patterns (#1200) in the past, so updating doc has been on my plate.
> Update docs around <extraDirectories> and <permissions>

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTest.java
This PR restricts Jib to support a single platform specification only .
Jib will throw an error if a user specifies more than one platform .
> Single Platform Specification Support

- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
Fixes #2565.
Spring Boot renames the original thin JAR only when it is replacing JAR with its repackaged fat JAR. If Spring Boot defines `<finalName>`, it doesn't rename the JAR as the fat JAR name doesn't clash with the original JAR. In this case, we were incorrectly assuming that Spring Boot renamed the original JAR with the `.jar.original` suffix.
I also discovered that we were not comparing `<classifier>`.
> Fix build error with "packaged" containerizingMode when Spring Boot defines <finalName>

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
This is a draft PR for design review
Stylistics changes are still in progress
This PR adds the ability for Jib to pull and store baseImagelayers for multiple images
> obtainBaseImageLayers for multiple images

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
- Added a guard for #2655. Basically checks if a previously cached manifest doesn't match the configured platform. If so, raise an error with an actionable message.
- Updates CHANGELOG in jib-core, jib-maven-plugin, and jib-gradle-plugin.
- Also, there was a warning that `pullBaseImages` sometimes returns a mutable list and other times immutable, so I've addressed it by always returning an immutable list.
```
.../jib/jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java:217: warning:
[MixedMutabilityReturnType]
This method returns both mutable and immutable collections or maps from different paths. This may be confusing for users of the method.
private List<Image> pullBaseImages(
```
In the meantime, I will continue to do some actual end-to-end tests.
> Check if cached manifest matches configured platform

- jib-build-plan/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
1. This PR pushes multiple container config JSONs: loops through the built images and schedules multiple pushes in `pushContainerConfiguration()`. Note care has been taken to not block scheduling threads while looping by using the `Future<Image> ` as the key in the resulting `pushResults` map.
2.This PR also pushes multiple baseImageLayers: loops through the `results.baseImagesAndLayers.get()` and schedules multiple pushes in `pushBaseImageLayers()`. Note  the resulting results from the pushes are being stored in a list for now but in the next PR we will update the resulting `pushResults` list into a map so as to track the `builtImage/baseImageLayers` key-pair values.
> Adding functionality to push base image layers and push container config to the registry

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/CopySpec.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
Preserve trailing slash information in `dest` property. This should not be done in `AbsoluteUnixPath` because that is agnostic to the filesystem. It merely contains a list of paths. Preserve the information here and use within the `jib-cli` project.
> Preserve trailing slash metadata

- docs/faq.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Should be merge only after releasing Jib 2.5.0.
The FAQ needs to be correct and helpful, as we show the link to the FAQ in our Jib error message if Jib was unable to find a matching platform. @louismurerwa
> Update FAQ and plugin reference docs about selecting base image platform from a manifest list

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/CopySpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Validator.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/ArchiveLayerSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/CopySpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpecTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/ValidatorTest.java
- Added validation for all our optional parameters
- Added new parameterized tests
- Found out yaml parses converts `null` to string if used as a map key
part of #2570
> Add more validations after yaml is serialized

- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
Fixes #2692.
Reverts the fix of #2688, which only avoided NPE but wrongly assumed Spring Boot isn't configured by returning `Optional.empty()`. Instead, this PR returns an empty `Xpp3Dom` to signal that Spring Boot is configured.
Note that we do have a [Spring Boot integration test](https://github.com/GoogleContainerTools/jib/blob/74dd7a6263c0ca2e4aaab4f96578f9c19ecda5dd/jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java#L702) for checking if we accidentally containerize a fat JAR. However, as mentioned [here](https://github.com/GoogleContainerTools/jib/issues/2687#issuecomment-671365684), this doesn't seem reproducible with a default setup. To hit both #2687 and #2692, it may be a multi-module Spring Boot setup (although I can't …
> Don't wrongly assume Spring Boot isn't configured when empty <configuration>

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesStack.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesStackTest.java
The way we use `FileEntriesLayer.addEntry` requires non-null values to be entered. So work with defaults directly here, so we can always pass all properties to that method instead of complicated logic to determine based on null values which `addEntry` to call.
> Add defaults to FilePropertiesStack

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
This PR fixes the `java.lang.IllegalStateException` resulting from the multiple use of a single progress dispatcher factory.
> Fix child progress dispatcher factory

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/DockerHealthCheck.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ImageConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
In Java 9+,  passing in `null` to ImmutableCollection#contains results in a NullPointerException. This PR uses a workaround to manually check for null values in an immutablecollection instead of calling .contains(). 
Since ImmutableCollection#contains in Java8 accepts null (https://guava.dev/releases/23.0/api/docs/com/google/common/collect/ImmutableList.html#contains-java.lang.Object-), this issue can't be reproduced in Java 8. 
Fixes #2702
> Fix NullPointerException during preconditions validation for Java 9+

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestCheckerIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/CheckImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
The method pulls the manifest referred to by a tag or digest (if exists). The pulled manifest can also be a manifest list instead of an image manifest, so renaming it to `checkManifest()`.
> Rename RegistryClient.checkimage() to RegistryClient.checkManifest()

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/Cache.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageReader.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/BuildableManifestTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageMetadataTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ManifestAndConfigTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ManifestTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/OciIndexTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/AbstractManifestPuller.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/json/ErrorEntryTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageReaderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPullerTest.java
1. Renaming `ManifestAndConfig` to `ManifestAndConfigTemplate`.
- The class is a simple pair of manifest and config. In the new design, it will be used as a JSON template for de-/serialization.
- As a JSON template, converted `Optional<>` to `@Nullable`.
1. New class: `ImageMetadataTemplate`.
- Holds
1. a manifest list (if not Docker schema 1). Can be null (when a base image reference is not a manifest list).
2. a list of manifest+config pairs (`List<ManifestAndConfigTemplate>`).
For example,
```
{
"manifestList": {  # manifest list content
"@class": "com.google.cloud.tools.jib.image.json.V22ManifestListTemplate",
"manifests": [ { ... }, { ... }, { ... }, ... ]
},
"manifestsAndConfigs": [
{
"manifest": {
"@class": "com.google.cloud.tools.jib.image.json.V22ManifestTemplate", …
```
> Prepare JSON template classes for new manifest cache design

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Layers.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/LayersTest.java
- jib-cli/src/test/resources/buildfiles/layers/archiveLayerTest/layers.yaml
- jib-cli/src/test/resources/buildfiles/layers/fileTest/default/layers.yaml
- jib-cli/src/test/resources/buildfiles/layers/fileTest/failWithExcludes/layers.yaml
- jib-cli/src/test/resources/buildfiles/layers/fileTest/failWithIncludes/layers.yaml
- jib-cli/src/test/resources/buildfiles/layers/includesExcludesTest/layers.yaml
- jib-cli/src/test/resources/buildfiles/layers/pathDoesNotExist/layers.yaml
- jib-cli/src/test/resources/buildfiles/layers/propertiesTest/layers.yaml
There are still some quirks to layer creation that we will have
to work out
- includes on file patterns can end up "excluding" directories
which will have to be readded, or we can ignore includes
directives on directories and end up with empty directories
everywhere
- directories between a target and root will be configured to
have the default properties of ReproducibleLayerBuilder rather
that what is configured by the user. This can be dealt with
by populating directories from root.
- only handles `FileEntriesLayers` types
part of #2570
> Layers creator classes

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpec.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/PlatformSpecTest.java
Since jib-core doesn't supported advanced platform spec options yet, remove these and reintroduce them later.
> Remove PlatformSpec unsupported parameters for now

- jib-gradle-plugin/src/integration-test/resources/gradle/projects/empty/build.gradle
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/TargetImageParameters.java
Specifically, [this](https://github.com/GoogleContainerTools/jib/blob/faff19bd59737e10db4425e47b7e6c9904e83833/jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/EmptyProjectIntegrationTest.java#L76) integration test was failing. This PR serves as a follow-up to #2739.
> Fix to handle integration test failure caused by #2739

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Layers.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFilesTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/LayersTest.java
- jib-cli/src/test/resources/buildfiles/projects/allDefaults/jib.yaml
- jib-cli/src/test/resources/buildfiles/projects/allProperties/jib.yaml
- jib-cli/src/test/resources/buildfiles/projects/allProperties/project/script.sh
Reads a buildfile from file and converts it into a JibContainerBuilder, this will be used by the CLI to then generate a container.
Requires #2763
> Read a buildfile and convert it into a JibContainerBuilder

- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
Fixes #2781.
We started with the default amd64/linux, and we were always adding new platforms.
> Fix platform configuration in Gradle plugin

- CONTRIBUTING.md
- build.gradle
- jib-build-plan/scripts/prepare_release.sh
- jib-core/scripts/prepare_release.sh
- jib-gradle-plugin-extension-api/scripts/prepare_release.sh
- jib-gradle-plugin/scripts/prepare_release.sh
- jib-maven-plugin-extension-api/scripts/prepare_release.sh
- jib-maven-plugin/scripts/prepare_release.sh
- jib-plugins-extension-common/scripts/prepare_release.sh
The intellij test runner has some issues with tests that are run
if integrationTest depends on test. Remove that dependency and
this fixes the issue.
Also adds some additional logging output and update release scripts
> Fixes running select integration tests from intellij

- build.gradle
- jib-cli/build.gradle
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFilesTest.java
- jib-cli/src/test/resources/buildfiles/projects/templating/missingVar.yaml
- jib-cli/src/test/resources/buildfiles/projects/templating/multiLine.yaml
- jib-cli/src/test/resources/buildfiles/projects/templating/valid.yaml
Allow templating in cli buildfiles
Expected usage:
```
$ jib build -Pkey=value
```
will replace any instances of `${key}` with `value' in the raw build file. This means the user can technically replace whole sections of the buildfile.
> Add templating to jib-cli

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Distroless now sets the workdir to "/", and we inherit it. Update
our tests to reflect this change.
Change: https://github.com/GoogleContainerTools/distroless/pull/586/files#diff-d245c60ce0ec3736ea8187d7bc3cb1c8R18
> Fix workdir value in integrationTests

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryClientTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Fixes #2784. Fixes #2134.
After we try to pull a base image manifest without sending credentials, we either attempt bearer auth or basic auth based on the `WWW-Authenticate` HTTP header value in a 401 unauthorized response. I have been thinking for a very long time even before filing #2134 this is the most ideal and optimized flow. I believe every sane registry implementation that throws 401 on a manifest request will send `WWW-Authenticate`.
However, since auth is the most frictional part, I didn't want to make a drastic change. So when the server doesn't return `WWW-Authenticate` (I don't expect this to happen), we do some fallback operations. First, we just blindly send credentials via basic auth, and if that fails again with 401, we attempt bearer auth for the last moment. This …
> Optimize authentication for base image

- CONTRIBUTING.md
- examples/helloworld/build.gradle
- examples/java-agent/build.gradle
- examples/micronaut/build.gradle
- examples/multi-module/build.gradle
- examples/spring-boot/build.gradle
- examples/vertx/build.gradle
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
- jib-gradle-plugin/gradle.properties
Update docs, actual release is not from master
See: https://github.com/GoogleContainerTools/jib/pull/2794
> Post release 2.5.1-gradle

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PlatformChecker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PlatformCheckerTest.java
Fixes #2746. Fixes #2745.
When the base image is not a manifest list (including a local Docker and tar image), logs a warning in the follow cases.
1. Multiple platforms are configured.
2. The configured platform doesn't match the actual platform, unless the "configured" platform is `amd64/linux`.
About 2): Currently we cannot distinguish between explicitly configured `amd64/linux` and the implicit `amd64/linux` default when omitted, so unfortunately sometimes we need to suppress logging even if the platforms don't match.
> Check configured platforms for single image building

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFilesTest.java
- jib-cli/src/test/resources/buildfiles/projects/allProperties/altYamls/alt-jib.yaml
Allows the cli to follow a docker style
```
$ jib build my/project/root -b some/build/file/somewhere.yaml
```
> Add ability to specify root context directory when parsing buildfile

- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/maven/projects/simple/pom-multiplatform-build.xml
Fixes the integration test failure after bumping the Jib version. The cause was the change in the `created_by` value in the container config.
```
"history": [
{
"created": "2020-07-27T23:41:26.054263591Z",
"created_by": "/bin/sh -c #(nop) ADD file:b30c8ba7ffe694c4cd200cdcfc75a57a099c28f5cc97c74b6e5c0cf2bfcc5962 in / "
},
{
"created": "2020-07-27T23:41:26.640971697Z",
"created_by": "/bin/sh -c #(nop)  CMD [\"sh\"]",
"empty_layer": true
},
{
"created": "1970-01-01T00:00:00Z",
"author": "Jib",
"created_by": "jib-maven-plugin:2.6.1-SNAPSHOT",
"comment": "dependencies"
},
```
> Fix multi-platform integration test caused by Jib version info in container config

- build.gradle
- jib-cli/build.gradle
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/JibCli.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/VersionInfo.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/JibCliTest.java
Initial implementation of #2787 
does not execute anything
Here's what the help text looks like:
```
Usage: jib [-hV] [--allow-insecure-registries] [--send-credentials-over-http]
[--application-cache=<cache-directory>] [-b=<build-file>]
[--base-image-cache=<cache-directory>] [-c=<project-root>]
[--name=<image-reference>] -t=<target-image> [--verbosity=<level>]
[--credential-helper=<credential-helper>]... [-p=<name>=<value>]...
[--tags=<tag>[,<tag>...]]... [[--username=<username> --password
[=<password>]] | [[--to-username=<username> --to-password
[=<password>]] [--from-username=<username> --from-password
[=<password>]]]] [@<filename>...]
A tool for creating container images
[@<filename>...]      One or more argument files containing options.
--allow-insecure-registries
Allow jib to …
```
> Add (new) Jib Cli parameters in base command class.

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/JibCli.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/JibCliTest.java
Implementation of #2831 
Adds option to specify credential helper specifically for target image or base image registries.
There is a way to separate out complex parameter logic like this into a separate class and then include it as a mixin. Maybe that'll help reduce some of the clutter in the future. Just dropping in here for information Mixin: https://picocli.info/apidocs/picocli/CommandLine.Mixin.html
> Add to/from credential helper

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFilesTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
This doesn have a test, needs to added as an integration test after the system is integrated together. In general it seems like the code around parsing an image and creating a containerizer/container-builder is a little tough and tends to be handled by integration tests.
follow-up issue: https://github.com/GoogleContainerTools/jib/issues/2839
> Add credentials for `from` image in BuildFile

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Containerizers.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/JibCli.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/logging/CliLogger.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/api/ContainerizerTestProxy.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/ContainerizersTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/JibCliTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/global/JibSystemProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/DefaultCredentialRetrievers.java
Convert cli options to a containerizer, create a build with default logging.
The logging probably still needs configuration (like allow `--console=plain`) or something.
Requires ~~#2811~~  ~~#2817~~
> Build Command for building from cli

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarProcessor.java
Turns out `JarFile` is `Closeable`. My IDE shows a resource leak warning.
> Close JarFile after instantiating

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarProcessor.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarProcessorTest.java
For #2845
This PR also contains some minor refactorings.
> Compute entrypoint for a standard jar in exploded mode.

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Containerizers.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/logging/CliLogger.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarProcessor.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/logging/CliLoggerTest.java
Jib CLI logging was misbehaving, ~~swallowing messages and~~ unnecessarily outputting blank lines:
```
$ jib --target=docker://foo build
Base image 'ubuntu' does not use a specific image digest - build may not be reproducible
The base image requires auth. Trying again for ubuntu...
Using credentials from Docker config (/home/chanseok/.docker/config.json) for ubuntu
Using base image with digest: sha256:fff16eea1a8ae92867721d90c59a75652ea66d29c05294e6e2f898704bdb8cf1
Container entrypoint set to [sh, hello.sh]
Executing tasks:
[==============================] 100.0% complete
```
We should be adding message consumers to `ConsoleLoggerBuilder` only when the corresponding log levels should be consumed.
Output after the fix:
```
$ jib --target=docker://foo build
Base image 'ubuntu' does not use …
```
> Fix broken Jib CLI logging

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/global/JibSystemProperties.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/global/JibSystemPropertiesTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenRawConfiguration.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ProjectProperties.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PropertyNames.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/RawConfiguration.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessorTest.java
Gives a viable solution to #1871 (#1907, #2228, #2733).
Also enables the AppCDS support (#2471).
This PR adds the option `jib.container.expandClasspathDependencies` that expands the wildcard `.../libs/*` in the entrypoint JVM classpath. It's off by default. The feature to use an `@argument` file will be added later for a permanent fix for the issue later. See https://github.com/GoogleContainerTools/jib/pull/2866#discussion_r512790086 for details.
> Add option to expand wildcard in entrypoint runtime classpath

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarModeProcessorTest.java
Remove TODOs to validate on ordering of file paths. As detailed in #2821, since ordering based on the string value of Path is done in [ReproducibleLayerBuilder](https://github.com/GoogleContainerTools/jib/blob/39b93632294e5b5a7ac40bbccb1e34ca013d17fa/jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java#L84), the order of the layer entries doesn't need to be validated at this point in the code flow. 
Closes #2821.
> Remove todos to validate on ordering of paths

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
The example comment uses `exposedPorts` to define which ports the container should expose, the `ContainerParameters` class does not have such a property. The correct property name is `ports`.
I hope that it is OK that I skipped creating a seperate issue, I though it would be for such a trivial change.
See the relevant property in `ContainerParameters` [here](https://github.com/GoogleContainerTools/jib/blob/8d34a28a156894867c6fdd8416a9f03cdf04d863/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java#L171).
> Fix example comment in JibExtension

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPusherIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPusherIntegrationTest.java
Due to the new Docker Hub rate limit, we are starting to see errors like
```
com.google.cloud.tools.jib.registry.BlobPullerIntegrationTest > classMethod FAILED
java.lang.RuntimeException: Command 'docker run --rm -d -p 5000:5000 --name registry-a8087b15-fa3c-401c-bcbe-09f2a5e52dc9 registry:2' failed: Unable to find image 'registry:2' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
See 'docker run --help'.
```
This PR uses `mirror.gcr.io` when feasible.
Note, normally, one shouldn't directly reference `mirror.gcr.io`, as the mirror is a pull-through cache and doesn't guarantee the existence of images. However, in practice I don't think …
> Migrate away from Docker Hub in integration tests

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/AuthParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
Fixes https://github.com/GoogleContainerTools/jib/issues/2905
The following are now properties and not plain strings:
- from.auth.username
- from.auth.password
- from.image
- to.auth.username
- to.auth.password
> Convert jib.*.auth.username and jib.*.auth.password to properties

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
In #2910, I hoped that `busybox` and `registry:2` will always exist in the mirror
> Note, normally, one shouldn't directly reference `mirror.gcr.io`, as the mirror is a pull-through cache and doesn't guarantee the existence of images. However, in practice I don't think `busybox` and `registry:2` will ever fail on `mirror.gcr.io`.
However, that doesn't turn out to be true. :( Reverting the mirror for now. (But we've stripped down unnecessary pulls from Docker Hub in #2910, so hopefully we become much stable while using Docker Hub.)
```
com.google.cloud.tools.jib.api.JibIntegrationTest > classMethod FAILED
java.lang.RuntimeException: Command 'docker pull mirror.gcr.io/library/busybox' failed: Error response from daemon: manifest for mirror.gcr.io/library/busybox:latest not found: manifest …
```
> Revert using mirror.gcr.io in integration tests

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtensionParametersSpec.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PlatformParametersSpec.java
While reviewing #2906, I was perplexed as it seemed working even though `objectFactory.newInstance()` does not pass an `objectFactory` as a constructor argument. Turns out [some classes are auto-injected](https://docs.gradle.org/current/javadoc/org/gradle/api/model/ObjectFactory.html#newInstance-java.lang.Class-java.lang.Object...-):
> In addition to those parameters provided as an argument to this method, the following services are also available for injection:
>
> * ObjectFactory.
To avoid potential confusion in the future, I'm making the usage consistent.
> Have consistency in instantiating Gradle parameter classes

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
Moved the upper code block before `try (ProgressEventDispatcher progressEventDispatcher = ...) {` into that try block.
The upper code block has short-circuiting returns, so taking that path fails to complete the progress allocation given to `PullBaseImageStep`.
> Fix incomplete progress dispatching in PullBaseImageStep

- build.gradle
- jib-core/build.gradle
- jib-core/src/main/java/com/google/cloud/tools/jib/json/JsonTemplateMapper.java
[Jackson Release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12)
Adds jsr310 datatype module which is now required for serializing `java.util.time.Instant`.
Bumps [jackson-databind](https://github.com/FasterXML/jackson-databind) from 2.11.3 to 2.12.0.
- [Release notes](https://github.com/FasterXML/jackson-databind/releases)
- [Commits](https://github.com/FasterXML/jackson-databind/compare/jackson-databind-2.11.3...jackson-databind-2.12.0)
Bumps [jackson-dataformat-yaml](https://github.com/FasterXML/jackson-dataformats-text) from 2.11.3 to 2.12.0.
- [Release notes](https://github.com/FasterXML/jackson-dataformats-text/releases)
- [Commits](https://github.com/FasterXML/jackson-dataformats-text/compare/jackson-dataformats-text-2.11.3...jackson-dataformats-text-2.12.0) …
> Bump jackson dependencies from 2.11.3 to 2.12.0

- jib-build-plan/scripts/prepare_release.sh
- jib-core/scripts/prepare_release.sh
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
- jib-gradle-plugin-extension-api/scripts/prepare_release.sh
- jib-gradle-plugin/scripts/prepare_release.sh
- jib-maven-plugin-extension-api/scripts/prepare_release.sh
- jib-maven-plugin/scripts/prepare_release.sh
- jib-plugins-extension-common/scripts/prepare_release.sh
We've been using `echo | ./gradlew release` to suppress interactive prompts, but we can use [`-Prelease.useAutomaticVersion=true`](https://github.com/researchgate/gradle-release#working-in-continuous-integration) instead.
Also learned that the `release` task pushes the branch and the tag, so no need to manually push them.
> Use `-Prelease.useAutomaticVersion=true` for non-interactive release and remove unnecessary branch and tag pushes

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/logging/CliLogger.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/cli2/logging/CliLoggerTest.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
Fixes #2920.
Verified that, after this PR, `jib jar -t docker://foo a.jar > a.out` correctly disables rich output. Of course, without redirection, it does rich output.
> Fix Jib CLI to disable rich console output when no console is attached

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- jib-cli/build.gradle
- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/cli2/TestProject.java
- jib-gradle-plugin/build.gradle
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- minimum to run jib is still 5.1
There are some eclipse related configurations that maybe we don't need anymore, but I don't have a good way to test eclipse right now.
> Upgrade build to 6.0.1

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/cli2/Jar.java
I was not able to find an option in picocli to disable a command. Maybe `hidden` is good enough. But I also added a guard to prevent it from running. (picocli still does argument validation though.)
> Hide and disbale Jib CLI jar sub-command

- build.gradle
Supersedes #2881, #2882, and #2940 prepared by the dependabot.
> Upgrade Google HTTP Client and Auth libraries

- build.gradle
- jib-build-plan/build.gradle
- jib-cli/build.gradle
- jib-core/build.gradle
- jib-gradle-plugin-extension-api/build.gradle
- jib-gradle-plugin/build.gradle
- jib-maven-plugin-extension-api/build.gradle
- jib-maven-plugin/build.gradle
- jib-plugins-common/build.gradle
- jib-plugins-extension-common/build.gradle
- `eclipse.classpath.plusConfigurations`: https://stackoverflow.com/a/36651485/1701388
- `setCanBeResolved(true)`: followed https://stackoverflow.com/a/55232236/1701388 although I don't know what this implies.
- Also excluded some test project resources from source in jib-cli
> Fix Gradle config for Eclipse IDE

- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/JarCommandTest.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ContainerBuilders.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/api/JibContainerBuilderTestHelper.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/ContainerBuildersTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarFilesTest.java
Closes #2923
This PR adds the `--from` option to the jib cli jar subcommand. It will be used to specify the desired base image.
> Add option to specify base image for cli jar command

- .github/workflows/jib-cli-release.yml
- There exists `build/distributions/jib-<version>.zip`. No need to manually zip.
- Adds version strings to uploaded assets.
> Improve Jib CLI release workflow

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/WriteTarFileStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/FileOperations.java
- jib-core/src/test/java/com/google/cloud/tools/jib/filesystem/FileOperationsTest.java
I was looking at how we are handling concurrency regarding sharing files and realized there are too many variations. And our use of `FileOperations.newLockingOutputStream()` confuses me, and I think this is not really necessary. 
- `CacheStorageWriter`: locking on a fresh temp file is meaningless. I don't know why we did `newLockingOutputStream()`.
- `WriteTarFileStep`: for this one, it isn't technically meaningless. But this class is for creating an image tar (which can be loaded into Docker with `docker load`), which is by default `<project root>/target/jib-image.tar`. Although the path is configurable, it's unlikely that multiple JVMs (Jib processes) will concurrently write into the same tar path in practice.
> Remove unnecessary file lock operations

- .github/RELEASE_TEMPLATES/plugin_release_checklist.md
- .github/workflows/prepare-release.yml
This will only create a release checklist for the plugin releases.
> Add new release checklist to release process for plugins only

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
`PullBaseImageStep` has got complicated over time, and the progress reporting was broken. I am trying to improve the situation with this PR. It's still not perfect, but I think it's better.
- At function call boundaries, I think it's often better to pass a dispatcher factory. The callee will have the freedom to decide how to sub-divide the given progress node.
- I think it's more robust to do `try (... = factory.create("description", size)) { ... }` at the beginning of a function as early as possible.
> Improve progress reporting in PullBaseImageStep

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java
- jib-maven-plugin/build.gradle
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/skaffold/SyncMapMojoTest.java
I have seen the flaky test failure several times on Kokoro. Looking at the test, I don't think there is a critical bug. However, the next time we see it, we'd want to get more information.
```
com.google.cloud.tools.jib.maven.skaffold.SyncMapMojoTest > testSyncMapMojo_failIfJarContainerizationMode FAILED
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.google.cloud.tools.jib.maven.skaffold.SyncMapMojoTest.testSyncMapMojo_failIfJarContainerizationMode(SyncMapMojoTest.java:178)
Gradle Test Executor 6 finished executing tests.
```
> Improve assertions in tests

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Instants.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/InstantsTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarFilesTest.java
Required a bit of refactoring to use the `Instants` class which was initially implemented for the build command.
> [jib-cli-jar] Add option to specify creation time of container

- proposals/cli-jar-processing.md
Keeping the information in the jib cli jar proposal relevant.  
[rendered](https://github.com/GoogleContainerTools/jib/blob/321f3a9c8c6affe329eaec5529b05c1490fa669c/proposals/cli-jar-processing.md)
>  Update cli-jar-processing.md

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarProcessor.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarProcessors.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/SpringBootExplodedProcessor.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/SpringBootPackagedProcessor.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/StandardExplodedProcessor.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/StandardPackagedProcessor.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarFilesTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarProcessorsTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/SpringBootExplodedProcessorTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/SpringBootPackagedProcessorTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/StandardExplodedProcessorTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/StandardPackagedProcessorTest.java
> Use AdoptOpenJDK image as default base image in Jib CLI Jar

- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/JarCommandTest.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarProcessors.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarProcessorsTest.java
Discovered this while manually testing the CLI Jar Command: IllegalArgumentException was being thrown even when `--from` was specified.
> Check if base image has been specified before throwing IllegalArgumentException in JarProcessors

- jib-cli/CHANGELOG.md
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/jar/JarFilesTest.java
> Use adoptopenjdk base image instead of openjdk in the Jib CLI

- jib-cli/README.md
Rendered: https://github.com/GoogleContainerTools/jib/blob/d750bc57e394943c259f0bba0caccba0de60b46f/jib-cli/README.md
> Add a Jar Command Quickstart to the Jib CLI README

- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
I think existing tests already check if calling `setAppRoot()` correctly takes effect. No point in having multiple tests using different app root values (`/app`, `/my/app`, and something else).
If this looks good, I'll apply a similar change to `MavenProjectProperties`
> Remove out-of-scope tests in `GradleProjectProperties`

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
> Update jib-gradle-plugin/CHANGELOG for the new option: `configurationName`

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLogger.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLoggerTest.java
> Disable coloring in build output when `--console=plain` is used

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/CommonCliOptions.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ShortErrorMessageHandler.java
For #3128
Calling `jib` results in:
```
Missing required subcommand
Usage: jib [-hV] [@<filename>...] COMMAND
Run 'jib --help' for more information on usage.
```
Calling `jib jar` results in:
```
Missing required options and parameters: '--target=<target-image>', '<jarFile>'
Usage: jib jar [-hV] [--allow-insecure-registries]
[--send-credentials-over-http]
[--base-image-cache=<cache-directory>] [--console=<type>]
[--creation-time=<creation-time>] [--from=<base-image>]
[--image-format=<image-format>] [--mode=<mode>]
[--name=<image-reference>] [--project-cache=<cache-directory>]
-t=<target-image> [-u=<user>] [--verbosity=<level>]
[--additional-tags=<tag>[,<tag>...]]...
[--entrypoint=<entrypoint>[\s+<entrypoint>...]]...
[--environment-variables=<key>=<value>[,<key>=<value>...]]... …
```
> [Jib-CLI] Print short error message when invalid option is passed in

- jib-core/build.gradle
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/Retry.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageWriterTest.java
Helps with #3127.
- `.maximumRetries(10)`, increased from 5. The delay is 15ms, so we only increase the total time by 75ms.
- As reported, the helpful error message is not shown when the operation fails due to repeated `FilesSstemException`s.
- Improves the error message. If the user still hits the issue, it's possible that the anti-virus software is impacting the performance a lot. The link provides not only a workaround but the potential to increase performance.
> Increase retry attempts and fix the issue of exception being consumed

- jib-cli/CHANGELOG.md
- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/JarCommandTest.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
Fixes #3047.
Did a manual test similar to the one described in #3011 with this `config.json`:
```
{"disableUpdateCheck":false,
"registryMirrors": [
{
"registry": "registry-1.docker.io",
"mirrors": ["mirror.gcr.io", "localhost:5000"]
}
]
}
```
(Case where we fall back to Docker Hub):
It first tries `mirror.gcr.io` and if the base image is not found then it tries `localhost:5000`. It fails on `localhost:5000` with a connection error but doesn't fail the entire build. It finally pulls from Docker Hub.
(Case where we pull from mirror.gcr.io):
And using `--from=busybox` for example, results in the image being pulled from mirror.gcr.io.
> Enable registry mirrors in Jib CLI

- jib-cli/build.gradle
- jib-cli/src/java-templates/com/google/cloud/tools/jib/cli/VersionInfo.java.template
Fixes #3149.
This will make Jib CLI use the version string as defined in `jib-cli/gradle-properties` for the `User-Agent` HTTP header and the output of `$ jib --version`.
Notes:
- Moves `VersionInfo.java` out of `src/main/java` into `src/java-templates` and converts it to a template.
- When compiling, it generates the final `VersionInfo.java` into `build/generated-src` while incorporating the `version` Gradle property into the template. The process is done with the Gradle [`Copy` task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html).
I'm not sure if IntelliJ will require this, but you may need to run the `:jib-cli:compileJava` task once after re-configuring the project.
> [Jib CLI] set correct version and User-Agent

- jib-cli/CHANGELOG.md
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JibCliTest.java
Fixes #3148.
It seems unlikely that `CliLogger.newLogger` will ever fail. This PR takes it out of the try-catch block and uses the `ConsoleLogger` to log error messages.
It additionally colorize the exception message in red.
> [Jib CLI] log exception with ConsoleLogger

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-extra-dirs-filtering.gradle
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/maven/projects/simple/pom-extra-dirs-filtering.xml
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java
> Add CHANGELOG and integration tests for extra directories filtering 

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/EmptyProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibRunHelper.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesExtensionTest.java
Just realized the assertion should have been `isGreaterThan` in #3176.
> Cleanups and fixes

- examples/helloworld/pom.xml
Seems like upgrading to 29.0-jre is not enough to close the following alert:
https://github.com/GoogleContainerTools/jib/security/dependabot/examples/helloworld/pom.xml/com.google.guava:guava/open
> Upgrade Guava

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-extra-dirs-filtering.gradle
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/test/resources/maven/projects/simple/pom-extra-dirs-filtering.xml
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelperTest.java
Most of the time, you'll specify a relative path in `<includes>` and `<excludes>`, which is the case in all of our tests.
Turns out we need to relativize local path to match against the glob matchers. The reason the tests seemed to work was that we always started with `**/`, which works for absolute path. That is, previously, `includes = ['foo']` didn't work.
---
Previous PR: #3173
Issues: #2564 #3164
> Fix extraDirectories filtering to match relative path

- .github/RELEASE_TEMPLATES/cli_release_checklist.md
- .github/RELEASE_TEMPLATES/core_release_checklist.md
- .github/RELEASE_TEMPLATES/plugin_release_checklist.md
- .github/workflows/jib-cli-release.yml
- .github/workflows/prepare-release.yml
This auto-files a checklist issue when releasing Jib Core and Jib CLI.
> Add Jib Core and CLI release checklists and update release workflows

- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
The working directory is not configured in the new base image.
> Fix integration test after changing base image

- jib-cli/CHANGELOG.md
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/CommonCliOptions.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/BuildTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JarTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/JibCliTest.java
For #3183 
Usage:
Calling `jib build --target=${IMAGE_REFERENCE} --image-metadata-out=/my/directory/jib-image.json` will result in the creation of `jib-image.json` (with image details such as image digest, id, tags) in `my/directory/`, if the directory exists.
Same for `jib jar`.
> [jib-cli] Add option to create an output JSON file that contains image metadata for the built image

- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
> Document WAR containerization with jetty

- jib-cli/README.md
Hi, I'm a Jib fan.
Most of the time, i'm running Jib from `maven` and `gradle` , but recently I had to use it from command line. To help windows colleagues adopt it, I created a [Chocolatey package](https://community.chocolatey.org/packages/jib) to make the install process even easier under windows.
Hopefully you'll like it.
Thanks a lot for Jib, it helps us save so much time !
https://twitter.com/rastadidi/status/1380255793648312321
Kind Regards,
Adrien
> 🎁 Jib CLI > Add the windows install process with chocolatey 🎁 

- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageTarball.java
- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java
Fixes #3158.
Sets the mod time on TarArchiveEntry to DEFAULT_MODIFICATION_TIME (Epoch second 1) in order to create reproducible Tar images. Associated unit test creates 2 tars output streams from the same input 2 seconds apart to show the failure if we don't explicitly set the TarArchiveEntry mod time
> #3158 - [Jib core] Tar archives with same contents are not reproducible

- jib-core/CHANGELOG.md
- jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Follow-up to https://github.com/GoogleContainerTools/jib/pull/3159#pullrequestreview-634011371.
> CHANGELOG for reproducible buildTar change / refactor tests

- docs/privacy.md
- jib-cli/README.md
Also includes link to the privacy page in jib-cli/README.
To be submitted after #3165.
> Update privacy page for Jib CLI

- README.md
Current filter on good first issue show no open issues the filter uses "kind/good first issue" but "good first issue" is used to create issues
> Fix good first issue filter in readme

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- jib-gradle-plugin/src/test/resources/gradle/projects/lazy-evaluation/build.gradle
Use Gradle Property and Provider to enable lazy evaluation for jib.container.labels (#3094)
> Use Gradle Property and Provider to enable lazy evaluation for jib.container.labels (#3094)

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/SpringBootExplodedProcessor.java
- jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheCorruptedException.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryErrorExceptionBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageFilesTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryEndpointCallerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryErrorExceptionBuilderTest.java
fixes #3283
I removed the link in most places. I also fixed and make certain tests more strict.
There was one place in which I think the URL should stay, that is: https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java#L661. 
I'm not that familiar with the codebase but it seems really unlikely for this exception not to be caused by a bug.
Feel free to review the PR!
> Remove issue tracker url in most places

- jib-cli/build.gradle
We recently added the `warTest/` directory as test resources. Without excluding it, Eclipse considers it as project source.
> Add warTest/ to Eclipse classpath exclusion list

- jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarStreamBuilderTest.java
Upgrade to latest version of commons-compress, and replace a few usages of toFile and toPath round-trips with using Paths directly. Useful for staging files using the nio filesystem, for example extracting files to a [jimfs](https://github.com/google/jimfs) filesystem before adding them to a docker image.
> Allow jib images to be built from TarArchiveEntries on alternative FileSystems

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFiles.java
Fix sonar bug for fixit: https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTIQcB_fbtb802TR&open=AXrlUTIQcB_fbtb802TR 
This change should be complaint with sonar rules, but is it worth the change or should we just leave it alone? It does make one less call to `buildFile.getLayers()`, so that could be a benefit. 
Note: there are a bunch of similar sonar bugs.
> fix sonar bug to call Optional#isPresent() before accessing value.

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/json/DockerConfigTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetrieverTest.java
- jib-core/src/test/resources/core/json/dockerconfig.json
Support username and password tokens from dockercfg auths #3364
> Added support for username and password tokens in dockercfg auth

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java
<del>Fixes this sonarcloud [issue](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&open=AXrlUTRncB_fbtb802U6&resolved=false&severities=MAJOR&types=BUG): "Either re-interrupt this method or rethrow the "InterruptedException" that can be caught here."</del>
UPDATE : As described [here](https://github.com/GoogleContainerTools/jib/pull/3369#issuecomment-891340043) the update checker is a special case where we intend to silently consume any kind of error. Added a comment explaining this instead of restoring interrupted status.
> Add more documentation for when InterruptedException is thrown in UpdateChecker

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpecTest.java
Fixes this sonar [code smell](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&open=AXrlUTL9cB_fbtb802US&resolved=false&severities=BLOCKER&types=CODE_SMELL): "Add at least one assertion to this test case."
Also migrates other test cases to Truth.
> Add assertions and migrate to Truth

- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
fixes [this sonar code-smell](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTnzcB_fbtb802Ye&open=AXrlUTnzcB_fbtb802Ye).
Adding `assertNotNull` works and looks like we just want to make sure it works without breaking in this test case. 
But is there a better way to handle this?
> fix sonar blocker -- no assertion in test case.

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesExtensionTest.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/MavenProjectPropertiesExtensionTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Fixing similar sonar bugs of 'Call "Optional#isPresent()" before accessing the value'. 
List of sonar bugs in PR:
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTs_cB_fbtb802ZK&open=AXrlUTs_cB_fbtb802ZK
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J9xN6U6V78Ue75d&open=AXrt4J9xN6U6V78Ue75d
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J9xN6U6V78Ue75e&open=AXrt4J9xN6U6V78Ue75e
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTSzcB_fbtb802VT&open=AXrlUTSzcB_fbtb802VT
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTSzcB_fbtb802VR&open=AXrlUTSzcB_fbtb802VR
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTS …
> create obj and call Optional#isPresent() before access. fix sonar bug continued.

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesSpecTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunnerTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/SkaffoldSyncMapTemplateTest.java
fixes sonar code-smell for "Add at least one assertion to this test case."
List of sonar links related:
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTLzcB_fbtb802UR&open=AXrlUTLzcB_fbtb802UR
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTjqcB_fbtb802X_&open=AXrlUTjqcB_fbtb802X_
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTUecB_fbtb802Vf&open=AXrlUTUecB_fbtb802Vf
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTUqcB_fbtb802Vh&open=AXrlUTUqcB_fbtb802Vh
Used expect attribute of the @Test annotation for tests that success with no exceptions. This should be enough to silent sonar.
> fixes several sonar code-smell for no assertion in test.

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/JibCli.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesStack.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/BuildableManifestTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MojoCommon.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/VersionChecker.java
In order to be compliant with sonarcloud policy where class members annotated with `@VisibleForTesting` shouldn't be accessed in production code. 
For example:
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTJ2cB_fbtb802Tp&open=AXrlUTJ2cB_fbtb802Tp
> Remove VisibleForTesting annotation for code used in production

- jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/Port.java
fixes [this](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt9KgFcqoYycIcfN2O&open=AXrt9KgFcqoYycIcfN2O) sonar code smell. 
changed name for private variable, and leaving public interface unchanged.
> rename field port to fix for sonar.

- jib-core/src/main/java/com/google/cloud/tools/jib/api/DescriptorDigest.java
Fix for sonar issue: [Use already-defined constant 'DIGEST_PREFIX' instead of duplicating its value here.](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTbrcB_fbtb802Ww&open=AXrlUTbrcB_fbtb802Ww)
> fix sonar issue: Use already-defined constant 'DIGEST_PREFIX'.

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Build.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Jar.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/War.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunner.java
There are a few more spots in the code where we catch an InterruptedException(causing the thread state to be cleared) but don't restore the state. Re-interrupting the thread causes the interrupted state to be restored. 
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTJ2cB_fbtb802To&open=AXrlUTJ2cB_fbtb802To
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTKfcB_fbtb802T5&open=AXrlUTKfcB_fbtb802T5
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTLLcB_fbtb802UL&open=AXrlUTLLcB_fbtb802UL
- https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTfRcB_fbtb802Xg&open=AXrlUTfRcB_fbtb802Xg
-https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTSXcB_fbtb802VA&op …
> Re-interrupt threads when InterruptedException is caught

- jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/blob/Blobs.java
- jib-core/src/main/java/com/google/cloud/tools/jib/blob/FileBlob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/blob/InputStreamBlob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/blob/JsonBlob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/blob/StringBlob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/blob/WritableContentsBlob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/http/BlobHttpContent.java
- jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryClient.java
- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarStreamBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/FailoverHttpClientTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerFailoverHttpClientTest.java
Follow up of https://github.com/GoogleContainerTools/jib/issues/1409
It enables http client retry when the blob content is re-readable.
> basic retry for http client

- jib-core/src/main/java/com/google/cloud/tools/jib/http/FailoverHttpClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/http/WithServerFailoverHttpClientTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
Fixes sonarcloud [issues](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&resolved=false&severities=BLOCKER&types=CODE_SMELL)
> Add assertions to WithServerFailoverHttpClientTest and JibPluginTest

- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ImageToJsonTranslator.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslatorTest.java
Resolves sonarcloud [item](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTY4cB_fbtb802WJ&open=AXrlUTY4cB_fbtb802WJ): "Remove usage of generic wildcard type"
> Avoid using wildcards in the return type. 

- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/skaffold/FilesTaskV2Test.java
Fix sonar code smells of assertion should have expected value first. 
sample sonar link:
https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTqfcB_fbtb802Yw&open=AXrlUTqfcB_fbtb802Yw
> fix sonar issue: swap expected and actual value.

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
Resolves sonarcloud [item](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTdjcB_fbtb802XW&open=AXrlUTdjcB_fbtb802XW): "Cast one of the operands of this multiplication operation to a 'long'"
> Cast operand as long 

- jib-cli/CHANGELOG.md
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> Update CHANGELOG about `username`/`password` support for `auths` section in `~/.docker/config.json`

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/SpringBootExplodedProcessor.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/ImageReference.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageTarball.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java
Resolves the following sonar items:
- [`SpringBootExplodedProcessor`](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTJScB_fbtb802Tg&open=AXrlUTJScB_fbtb802Tg)
- [`ImageReference`](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTcgcB_fbtb802XE&open=AXrlUTcgcB_fbtb802XE)
- [`ImageTarball`](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTaocB_fbtb802Wq&open=AXrlUTaocB_fbtb802Wq)
- [`JavaContainerBuilderHelper`](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTTicB_fbtb802Va&open=AXrlUTTicB_fbtb802Va)
> Define constants instead of using String literals

- jib-core/src/main/java/com/google/cloud/tools/jib/api/JavaContainerBuilder.java
Fix sonar issue: ["entrySet()" should be iterated when both the key and value are needed](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTcBcB_fbtb802W2&open=AXrlUTcBcB_fbtb802W2)
> sonar: loop on entrySet instead of keySet

- jib-core/src/main/java/com/google/cloud/tools/jib/api/LayerConfiguration.java
Fix for sonar issue: [A field should not duplicate the name of its containing class](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTbHcB_fbtb802Wt&open=AXrlUTbHcB_fbtb802Wt)
Does naming it "layerBuilder" makes sense?
> rename field 'builder'.

- build.gradle
- jib-cli/CHANGELOG.md
- jib-core/CHANGELOG.md
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin-extension-api/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Downgrade Google HTTP and auth libraries to resolve #3058 and #3409. These are the versions used in Jib 2.7.0 as mentioned in https://github.com/GoogleContainerTools/jib/issues/3058#issuecomment-793122490 before upgrading in [#2096](https://github.com/GoogleContainerTools/jib/pull/2960/files).
> Downgrade Google HTTP and auth libraries

- jib-core/src/main/java/com/google/cloud/tools/jib/blob/InputStreamBlob.java
- jib-core/src/main/java/com/google/cloud/tools/jib/filesystem/LockFile.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/ConsoleLoggerBuilder.java
renaming to fix Sonar issue:
- Local variables should not shadow class fields: occurrences  [(1)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTYHcB_fbtb802V1&open=AXrlUTYHcB_fbtb802V1), [(2)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J-EN6U6V78Ue75k&open=AXrt4J-EN6U6V78Ue75k) , [(3)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTQ4cB_fbtb802U3&open=AXrlUTQ4cB_fbtb802U3) and [(4)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTQ4cB_fbtb802U4&open=AXrlUTQ4cB_fbtb802U4)
- [A field should not duplicate the name of its containing class](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTfRcB_fbtb802Xi&open=AXrlUTfRcB_fbtb802Xi)
> Field name changes to fix sonar issues

- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
Remove use of regex in response to [this](https://sonarcloud.io/project/security_hotspots?id=GoogleContainerTools_jib&hotspots=AXrt9KAtcqoYycIcfN2F) sonar security hotspot review:
> Sonar security: replaced regex.

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ArtifactProcessors.java
Fixes [this](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTK5cB_fbtb802UG&open=AXrlUTK5cB_fbtb802UG) sonar code smell.
removed `classFile == null` is always false. And the case where `classFile` is empty is covered by the catch block.
> remove expression that's always false.

- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
Fix sonar issue: Test methods should not contain too many assertions
Link to issues: [here](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J8BN6U6V78Ue74_&open=AXrt4J8BN6U6V78Ue74_) and [here](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt4J8BN6U6V78Ue75A&open=AXrt4J8BN6U6V78Ue75A).
> Split tests to reduce number of assertions in each test.

- jib-build-plan/src/test/java/com/google/cloud/tools/jib/api/buildplan/AbsoluteUnixPathTest.java
Fix sonar issue: [Refactor the body of this try/catch to have only one invocation possibly throwing a runtime exception.](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrt9KfgcqoYycIcfN2M&open=AXrt9KfgcqoYycIcfN2M).
>  fix to keep only one method invocation in try/catch testing for exception

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FilePropertiesStack.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/MainClassFinder.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/DockerHealthCheck.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/skaffold/InitTask.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProvider.java
Fix sonar code smell: Use isEmpty() to check whether the collection is empty or not.
occurrences: [(1)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTH9cB_fbtb802TO&open=AXrlUTH9cB_fbtb802TO), [(2)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTcTcB_fbtb802W8&open=AXrlUTcTcB_fbtb802W8), [(3)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTd5cB_fbtb802XZ&open=AXrlUTd5cB_fbtb802XZ), [(4)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTdjcB_fbtb802XV&open=AXrlUTdjcB_fbtb802XV), [(5)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&issues=AXrlUTg7cB_fbtb802Xx&open=AXrlUTg7cB_fbtb802Xx), [(6)](https://sonarcloud.io/project/issues?id=GoogleContainerTools_ …
> use isEmpty instead of size to check empty or not.

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BaseImageSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/BuildFileSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/CopySpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/FileLayerSpec.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/LayersSpec.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/JsonToImageTranslator.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
> Eliminate ErrorProne warnings

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
The main class detection logic in the gradle plugin always assumed that
the `Main-Class` attribute, set in the main jar task, is a string. This
is not always true, as it sometimes makes sense to set it to a provider
of String in order to link multiple configurations together.
The logic now tests the class of the value returned for the `Main-Class`
attribute and in case of an `Provider<?>` value, it will call the `get`
method. If the provider is not set, this will cause the task to fail.
The resulting object is then transformed to a String.
fixes #3396
> Fix class cast exception in gradle plugin main class detection logic

- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ArtifactLayers.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ArtifactProcessors.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/ContainerBuilders.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Containerizers.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Credentials.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/Instants.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Layers.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/buildfile/Validator.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarFiles.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/jar/JarLayers.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/logging/CliLogger.java
- jib-cli/src/main/java/com/google/cloud/tools/jib/cli/war/WarFiles.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PlatformChecker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/RegistryCredentialRetriever.java
- jib-core/src/main/java/com/google/cloud/tools/jib/hash/Digests.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAliasGroup.java
- jib-core/src/main/java/com/google/cloud/tools/jib/tar/TarExtractor.java
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProvider.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/PluginConfigurationProcessor.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ZipUtil.java
Batch fix sonar code smell: add private constructor to hide implicit public one.
These are all utility classes with only static members.
list of related sonar issues: https://sonarcloud.io/project/issues?id=GoogleContainerTools_jib&resolved=false&rules=java%3AS1118&severities=MAJOR
> Fix sonar code smell: add private constructor to hide implicit public one.

- docs/faq.md
- jib-core/src/main/java/com/google/cloud/tools/jib/api/MainClassFinder.java
Related to #3483.
Stack Overflow: https://stackoverflow.com/q/69798822/1701388
> Add FAQ about unsupported Java version and throw error with more helpful message

- docs/faq.md
This is to save people from debugging issues with their application and only realizing later why not everything in `JAVA_TOOL_OPTIONS` is being picked up. 
See also http://hg.openjdk.java.net/jdk7/jdk7/hotspot/file/9b0ca45cd756/src/share/vm/runtime/arguments.cpp#l2772 for the size limitation in the JVM code itself.
> Mention that JAVA_TOOL_OPTIONS only support a max of 1024 chars

- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidator.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ConfigurationPropertyValidatorTest.java
Fixes #2224.
The only character we interpret in a special way is a comma (to separate tokens when parsing a list or a map). There should be a way to put a comma is to escape it, and that's the only character we need escaping for. However, the previous implementation didn't drop the slash used for escaping.
> Fix incorrect parsing of comma-separate Jib property values

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/BuildContext.java
- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PushImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/BuildContextTest.java
a PoC for the issue I reported here: #3518
> Build option to add architecture suffix to tags when publishing multi-platform images

- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
The user contribution #3575 broke integration tests. We don't run integration tests on PRs (integration tests require accessing an internal GCP project), so sometimes we get into this.
> fix: fix broken integration tests

- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
in buildSrc srcipt: Cannot access class 'com.google.cloud.tools.jib.api.buildplan.ImageFormat'
> fix format config on buildSrc kts srcipt

- .github/workflows/jib-cli-release.yml
Fixes https://github.com/GoogleContainerTools/jib/issues/3584 
With the current setup, the [jib zip file is renamed](https://github.com/GoogleContainerTools/jib/blob/71e3977d5b1e81b860b29c3c62c8ea807a1d2d28/.github/workflows/jib-cli-release.yml#L89) **after** the checksum file is created. This is why the contents of the file currently look like this:
```
c0f47017f1218a223f51228cc69fe9d7793e600d8a05b11e4dbdba0dee6bfc11  jib-0.9.0.zip
```
And we end up with  `jib-0.9.0.zip: No such file or directory` when we call `sha256sum -c jib-jre-0.9.0.zip.sha256`. 
Renaming the zip file to jib-jre-{version} before generating the checksum file will result in the right contents:
```
c0f47017f1218a223f51228cc69fe9d7793e600d8a05b11e4dbdba0dee6bfc11  jib-jre-0.9.0.zip
```
> Rename jib cli zip file before creating sha256 file

- build.gradle
- jib-cli/build.gradle
- jib-core/build.gradle
- Bump jackson-databind to the latest 2.13.2.2.
- Switch and use jackson-bom to manage jackson dependency versions.
> Use jackson-bom and bump jackson-databind to 2.13.2.2.

- jib-maven-plugin/README.md
This is the same as #3610.
Closes #3609
> fix docker image name misspelled in readme.

- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/WarCommandTest.java
- jib-cli/src/integration-test/resources/warTest/build.gradle
- jib-cli/src/integration-test/resources/warTest/src/main/java/example/HelloWorld.java
The integration test `WarCommandTest.testWar_jetty()` intentionally uses the latest Jetty docker image. (in the future, if this causes many issues, we can likely delete that test, as there is another test pinning version).
This PR updates the sample itself to use the new Jakarta EE namespace, and updates the base images of remaining WAR tests to be on a version compatible with Jakarta EE 9.
> upgrade from javax to jakarta namespace

- jib-gradle-plugin/src/integration-test/resources/gradle/projects/war_servlet25/build-tomcat.gradle
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/war_servlet25/build.gradle
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/war_servlet25/src/main/java/example/HelloWorld.java
- jib-gradle-plugin/src/test/resources/gradle/projects/war_servlet25/build.gradle
- jib-gradle-plugin/src/test/resources/gradle/projects/war_servlet25/src/main/java/example/HelloWorld.java
in #3661, I only fixed jib-cli. After that, more test failures turned up in gradle plugin.
Notes
- I ought to have switched to Temurin images in the first place.
- The random-looking `configurations {
moreLibs
}` is there because otherwise the tests can be run from root but not from gradle-plugin subroot.
> More samples need to switch to jakarta

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/WarProjectIntegrationTest.java
- jib-gradle-plugin/src/test/resources/gradle/projects/war_servlet25/pom-tomcat.xml
- jib-gradle-plugin/src/test/resources/gradle/projects/war_servlet25/pom.xml
- jib-maven-plugin/src/test/resources/maven/projects/war_servlet25/pom-tomcat.xml
- jib-maven-plugin/src/test/resources/maven/projects/war_servlet25/pom.xml
- jib-maven-plugin/src/test/resources/maven/projects/war_servlet25/src/main/java/example/HelloWorld.java
Takes out the remaining appearances of javax.servlet in favor of Jakarta.
Follow up to #3661 and #3663.
> remaining javax.servlet instances

- jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java
- jib-core/src/test/java/com/google/cloud/tools/jib/configuration/ContainerConfigurationTest.java
This PR improves jib's error message when a value in the environment map (`container.environment`) is `null`.
> Improve error message when environment map contains null values (#3671)

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- settings.gradle
> :zap: Gradle build optimizations

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainer.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/BuildResult.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PushImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/StepsRunner.java
- jib-core/src/test/java/com/google/cloud/tools/jib/api/JibContainerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/BuildResultTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/StepsRunnerTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/ImageMetadataOutput.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/ImageMetadataOutputTest.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunnerTest.java
This keeps track of which images were pushed onto the target registry, useful for when skipExistingImages option is in use especially in a mono-repo contest.
https://github.com/GoogleContainerTools/jib/issues/3636
> Add imagePushed field to jib-image.json

- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/JarCommandTest.java
Latest versions of temurin are incompatible with older versions of docker ([source](https://github.com/adoptium/containers/issues/215#issuecomment-1142046045)).
I don't love this fix because it means we are not testing the default Jib CLI behavior, but it will unblock the build.
> Use temurin builds based on older version of ubuntu

- docs/faq.md
Current documentation: 
https://github.com/GoogleContainerTools/jib/blob/c419354aa42c4c8a2a32f93c1524d0b31b598979/docs/faq.md#i-need-to-add-files-generated-during-the-build-process-to-a-custom-directory-on-the-image
> The same can be accomplished in Gradle by using a `Copy` task. In your `build.gradle`:
>
> ```groovy
> jib.extraDirectories = file('build/extra-directory')
> ```
does not meet the syntax:
https://github.com/GoogleContainerTools/jib/blob/b7bdec593cc4b8614c9a66e2487b2a2ad80f6aed/jib-gradle-plugin#adding-arbitrary-files-to-the-image
> You can configure different directories by using the `jib.extraDirectories.paths` parameter in your `build.gradle`:
>
> ```groovy
> jib {
>   // Copies files from 'src/main/custom-extra-dir' and '/home/user/jib-extras' instead of 'src/main/jib'
> …
```
> Fix documentation of configuring extraDirectories for Gradle plugin

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PlatformChecker.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/PlatformNotFoundInBaseImageException.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PlatformCheckerTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
Fixes #3563: Converts warnings to exceptions.
> fix: error when base image doesn't support target platforms

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/LocalRegistry.java
Set explicit permissions to `tempFolder` created for local registry integration tests to `755`.
- Currently the default permissions set for `tempFolder`  is `700`, but it seems like docker running on macOS are sometimes unable to access this.
Possibly related: https://github.com/GoogleContainerTools/jib/pull/3598
> chore: Set tempFolder permissions for local registry test

- .github/workflows/jib-cli-release.yml
- README.md
- jib-cli/README.md
Hi,
I'm reaching out on behalf of the [Open Source Security Foundation (openssf.org)](https://openssf.org/). We work on improving the security of critical open source projects like yours. 
Together with [GitHub](https://github.blog/2022-04-07-slsa-3-compliance-with-github-actions/), we designed a free, easy-to-use method of code signing. It will help your users verify that your release binaries were built from your repository’s [workflow](https://github.com/GoogleContainerTools/jib/blob/master/.github/workflows/jib-cli-release.yml) and not altered by anyone. It’s just a few lines of code, but it will make your project more secure against third-party tampering and attacks like [Codecov](https://about.codecov.io/apr-2021-post-mortem/) and …
> Generate SLSA signatures on GitHub release jar

- .github/workflows/jib-cli-release.yml
I've tried jib-cli release, and it failed. This should fix the issue.
> Fix "dubious ownership" issue on repo-sync/pull-request

- README.md
- jib-cli/README.md
This PR updates the documentation for SLSA:
- Image link
- Remove the `tag` for verification, until https://github.com/slsa-framework/slsa-verifier/issues/213 is landed
- Add a `-branch master` for verification.
> Fix SLSA doc

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/CliDockerClient.java
- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Currently, in order to verify if the docker path provided (either default or specified by the user) is installed correctly, we actually run the executable. The side effect of this is that any arbitrary executable can be executed by Jib. 
This PR avoids the need to run the executable by using `Files.isExecutable` which verifies if the path provided exists and the JVM has the correct permissions to execute the path.
> Avoid running executable to verify if docker is correctly installed and clarify documentation for `jib.dockerClient.executable`

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/CliDockerClient.java
- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Reverts GoogleContainerTools/jib#3742
> Revert "Avoid running executable to verify if docker is correctly installed and clarify documentation for `jib.dockerClient.executable`"

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/BuildableManifestTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ManifestListTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/OciIndexTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/json/V22ManifestListTemplate.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/AbstractManifestPuller.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageReaderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/cache/CacheStorageWriterTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/json/OciIndexTemplateTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/ManifestPullerTest.java
- jib-core/src/test/resources/core/json/ociindex.json
- jib-core/src/test/resources/core/json/ociindex_platforms.json
Resolves #2749
Implementation follows https://github.com/GoogleContainerTools/jib/issues/3700#issuecomment-1171283502
- Add Accept header application/vnd.oci.image.index.v1+json during base image pull
- Re-use the logic from V22ManifestListTemplate to select the target platform diget via a new interface ManifestListTemplate
> Support pulling OCI Image Index manifests

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/CliDockerClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/CliDockerClientTest.java
- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Currently, in order to verify if the docker path provided (either default or specified by the user) is installed correctly, we actually run the executable. The side effect of this is that any arbitrary executable can be executed by Jib.
This PR avoids the need to run the executable by using Files.isExecutable which verifies if the path provided exists and the JVM has the correct permissions to execute the path. However in the case of verifying whether docker is on PATH, running the `docker` command seems unavoidable at the moment. Reasoning in https://github.com/GoogleContainerTools/jib/pull/3744#discussion_r955307325
Verified with `./gradlew jib-gradle-plugin:integrationTest`
> Check if file exists when executable path is passed in through jib dockerClient.executable

- jib-core/CHANGELOG.md
> Preparing jib-core CHANGELOG for 0.22.0 release

- .github/workflows/prepare-release.yml
The Prepare Release Github Actions job is currently resulting in the following error:
```
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
```
Similar to https://github.com/GoogleCloudPlatform/app-maven-plugin/pull/465, this PR upgrades repo-sync/pull-request to 2.6.2 to resolve this.
> upgrade repo-sync/pull-request to latest version

- build.gradle
- jib-cli/CHANGELOG.md
- jib-core/CHANGELOG.md
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Resolves #3416.
Upgrade previously downgraded Google HTTP and auth libraries (#3415) back to latest version, per https://github.com/GoogleContainerTools/jib/issues/3416#issuecomment-1209772087.
> Upgrade Google HTTP libraries

- build.gradle
- jib-cli/build.gradle
- jib-core/build.gradle
Jackson BOM was removed in #3625 because a fix was not yet part of the bom. It is fine now to resynchronize dependency versions with the BOM.
> Bring Jackson BOM back

- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Not sure this is the cause for `testBuild_tarBase` test flakes we have been seeing in CI, but here is a guess from troubleshooting:
The errors occur when the second build takes longer than the first, despite caching mechanisms that should lead to a shorter build time.
`testExecute_simple`, the other integration test that compares two build times and has been passing successfully, has [an additional file update block](https://github.com/GoogleContainerTools/jib/blob/7ba06b4eedbeafd2e3e21666af54dcdf48f1bbff/jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java#L382-L395) so that it does not push the same hello world image to target local registry as other tests in the same class. This PR copies over this additional change, since …
> test: Modify resource file for flaking integration test that compares two build times

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-jar-containerization.gradle
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-timestamps-custom.gradle
Recent changes in the Kokoro release environment temporarily patch in a jvm argument (`-Djavax.net.ssl.trustStore=/var/cache/proxy.crt.jks`) causing the container build by Jib to be modified when run. Since Jib gradle integration tests try to assert on the container configuration values (including jvm args) of the generated Jib container, this causes the tests to fail with the following assertion error:
```
com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest > testBuildTar_simple FAILED
value of:
run()
diff (-expected +actual):
@@ -6,4 +6,5 @@
cat
1970-01-01T00:00:01Z
1970-01-01T00:00:01Z
+-Djavax.net.ssl.trustStore=/var/cache/proxy.crt.jks
at com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest.testBuildTar_simple(SingleProjectIntegrationTest.java:499)
```
This …
> chore: refactor gradle integration test to cater for both local and kokoro release environment

- build.gradle
Workaround for issue #3783, to avoid dependency on JCenter through gradle plugin portal.
> Workaround for gradle plugin portal metadata requests

- docs/faq.md
Clarifying the placement of the java agent, since if we put the java agent directly on `src/main/jib` it won't be available in `/myfolder/agent.jar`
> docs: clarify the placement of java agent folder

- jib-gradle-plugin/README.md
- jib-maven-plugin/README.md
Fix typo in docs, as pointed out in https://github.com/GoogleContainerTools/jib/issues/3789#issuecomment-1255420223.
> docs: Fix typo for configuring outputPaths

- jib-gradle-plugin/README.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleRawConfiguration.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleRawConfigurationTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibExtensionTest.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/JibPluginTest.java
- jib-gradle-plugin/src/test/resources/gradle/projects/lazy-evaluation/build.gradle
Fixes #3708
Usage:
To use lazy evaluation for `jib.container.creationTime` or `jib.container.filesModificationTime`, the value can be provided as an ISO 8601 date-time string like this:
```
jib {
container {
creationTime = project.provider { value }
filesModificationTime = project.provider { value }
}
}
```
> Use Gradle Property and Provider for creationTime and filesModificationTime

- kokoro/continuous.sh
Troubleshooting potential causes for intermittent authentication errors that we started observing in MacOS continuous CI:
```
java.lang.RuntimeException: Command 'docker pull gcr.io/jib-integration-testing/simpleimage:maven4639084933994' failed: Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
This PR adds an additional line into continuous build script to have `GOOGLE_APPLICATION_CREDENTIALS` searched first by `docker-credential-gcr` and overrides the [default search order](https://github.com/GoogleCloudPlatform/docker-credential-gcr#gcr-credentials).
> Override default token resolution order in docker-credential-gcr for integration testing

- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java
- jib-gradle-plugin/src/test/java/com/google/cloud/tools/jib/gradle/GradleProjectPropertiesTest.java
- jib-gradle-plugin/src/test/resources/gradle/application/extra-directory/foo
Fixes #3666. 
It looks like this issue was introduced when making the switch to custom configurations in https://github.com/GoogleContainerTools/jib/pull/3034. The previous use of `mainSourceSet.getRuntimeClasspath()` also included class and resource outputs for the main `SourceSet` that are now missed, so changes to the Java classes are no longer getting picked up as Gradle task inputs.
This PR adds back the `main` SourceSet’s outputs to [GradleProjectPriperties.getInputFiles()](https://github.com/GoogleContainerTools/jib/blob/eccebd0d52301fefce9017783c1c43fa8cc671c7/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java#L407).  (Perhaps this will need to be updated if `SourceSet` is ever made configurable, but currently this fix is consistent with …
> Fix BuildTarTask input files to also include main SourceSet outputs

- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/build-truststore-arg.gradle
Follow-up to https://github.com/GoogleContainerTools/jib/pull/3769
> fix: fix filtering of `-Djavax.net.ssl.trustStore` from output generated by integration test 

- jib-gradle-plugin/build.gradle
Currently the release build for jib-gradle-plugin additionally runs integration tests before publishing to plugin portal. 
The recent Kokoro release environment changes introduced a number of compatibility issues in our current integration test suite. After attempting patching workarounds, this PR replaces the integration test check with full build (including unit tests) instead.
> fix: replace integrationTest task with build task when making gradle plugin release

- CONTRIBUTING.md
- examples/dropwizard/pom.xml
- examples/helloworld/build.gradle
- examples/helloworld/pom.xml
- examples/java-agent/build.gradle
- examples/java-agent/pom.xml
- examples/ktor/build.gradle.kts
- examples/micronaut/build.gradle
- examples/multi-module/build.gradle
- examples/multi-module/pom.xml
- examples/spring-boot/build.gradle
- examples/spring-boot/pom.xml
- examples/vertx/build.gradle
- jib-cli/CHANGELOG.md
- jib-core/CHANGELOG.md
- jib-core/README.md
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/README.md
Corresponding to post-release actions in #3834, #3836, #3838.
> chore: update docs and examples after core 0.23.0 and plugins 3.3.1 release

- .github/workflows/jib-cli-release.yml
To fix jib-cli release workflow, which is encountering error at `Generate Builder` step. 
See: [slsa-github-generator 1.2.1 release notes](https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.2.1).
Will merge after PRs to wrap up core and plugins release.
> fix: bump slsa-github-generator version from 1.2.0 to 1.2.1

- .github/workflows/jib-cli-release.yml
Latest attempts to release Jib CLI v0.12.0 has been running into SLSA (added in #3722, #3726) issues similar to described in https://github.com/slsa-framework/slsa-github-generator/issues/1163#issuecomment-1293012316. 
We have bumped slsa-github-generator version to v1.2.1, and this PR adds the suggested `compile-generator: true` workaround. 
@laurentsimon @ianlewis Would you be able to help provide any additional pointers or context on this issue?
> fix: add compile-generator workaround for SLSA

- jib-cli/CHANGELOG.md
- jib-cli/README.md
- Also updates SLSA attestation instructions in docs, since the file naming convention was updated as of slsa-github-generator v1.2.1
> chore: update docs for Jib CLI 0.12.0 release

- .github/RELEASE_TEMPLATES/cli_release_checklist.md
- .github/RELEASE_TEMPLATES/core_release_checklist.md
- .github/RELEASE_TEMPLATES/plugin_release_checklist.md
- CONTRIBUTING.md
For scaffold update, I suggested they use renovate-bot the last time I was releasing.
For milestones, we don't currently use Github's milestones in Jib.
For communication, most users rely on automated methods like dependabot.
I also updated CONTRIBUTING file to not require a manual update at every release.
The only thing I'd like to remove that I can't is updating the "examples" -- it is best if the samples use the correct jib version, but there is no parent relationship. Maybe having dependabot update those ourselves would work?
> Simplify release steps

- build.gradle
- jib-cli/src/integration-test/resources/jarTest/spring-boot/settings-layered.gradle
- jib-cli/src/integration-test/resources/jarTest/spring-boot/settings.gradle
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/spring-boot/settings.gradle
- settings.gradle
Fixing workaround from #3784 which modified metadata sources in `build.gradle`'s `subprojects.repositories` block, when it should have been made in `settings.gradle`'s `pluginManagement.repositories` block instead.
Reference: https://discuss.gradle.org/t/plugin-portal-dependency-resolution-failing-due-to-jcenter-usage/44131
This changes dependency resolution to deprioritize gradle plugin portal (with JCenter workaround) in favour of maven central, given the latest availability issues encountered.
> fix: update gradlePluginPortal workaround for JCenter availability issue

- .github/workflows/jib-cli-release.yml
Fixes #3853. 
[v1.2.2 of slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.2.2) has been released with fix for the provenance signing issue that required the `compile-generator` workaround added to unblock our last Jib CLI release. Updating to this version and removing the workaround from #3848.
> fix: update slsa-github-generator to v1.2.2 and remove workaround

- jib-maven-plugin/README.md
No code change.
The  default  global configuration path  in Mac is `~/Library/Preferences/Google/Jib/config.json` .
> fix global configuration path for Mac

- .github/workflows/jib-cli-release.yml
- .github/workflows/sonar.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve  #3920 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: echo "::set-output name=hashes::$(cat zip.sha256 | base64 -w0)"
```
```yml
run: echo "::set-output name=date::$(date +'%Y-%m-%d' --utc)"
```
**TO-BE**
```yml
run: echo "hashes=$(cat zip.sha256 | base64 -w0)" >> …
```
> chore: Replace deprecated command with environment file

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ContainerizerIntegrationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/DefaultTargetProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/EmptyProjectIntegrationTest.java
- jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/SingleProjectIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildDockerMojoIntegrationTest.java
- jib-maven-plugin/src/integration-test/java/com/google/cloud/tools/jib/maven/BuildImageMojoIntegrationTest.java
Fixes #3925. Integration tests that assert against the entire `docker inspect` output string are observing failures, likely due to a change in output format / whitespace. This PR updates them to fetch more specific fields and specify json format.
> test: update integration test assertions for docker inspect output

- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java
- jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java
Fix a few jackson deprecations. `ObjectMapper.configure` has [been deprecated](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/latest/com/fasterxml/jackson/databind/ObjectMapper.html#configure-com.fasterxml.jackson.databind.MapperFeature-boolean-)
```
> Task :jib:jib-core:compileJava
/Users/cwalker/git/jib/jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerConfigCredentialRetriever.java:91: warning: [deprecation] configure(MapperFeature,boolean) in ObjectMapper has been deprecated
new ObjectMapper().configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
^
/Users/cwalker/git/jib/jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/LocalBaseImageSteps.java:221: warning: [deprecation] configure(MapperFeature,boolean) in …
```
> Fix jackson deprecations

- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/BlobPullerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestCheckerIntegrationTest.java
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/registry/ManifestPullerIntegrationTest.java
Fixes #3963 to unblock CI (See issue for more error details and discussion).
Changes in this PR to address manifest format change in latest distroless image:
- Updates `BlobCheckerIntegrationTest` and `BlobPullerIntegrationTest` by using a fixed older version of the distroless image
- Removes use of “latest” tag in `ManifestPullerIntegrationTest`, and extends it to specifically cover OCI format using pinned image versions
> ci: update integration tests that expect docker manifest format from distroless image

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/buildfile/BuildFilesTest.java
- jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java
- jib-plugins-common/src/test/java/com/google/cloud/tools/jib/plugins/common/UpdateCheckerTest.java
- kokoro/continuous.bat
- kokoro/presubmit.bat
Resolves #3978.
Individual issues addressed:
- [Java 8 issue](https://github.com/GoogleContainerTools/jib/issues/3978#issue-1652650425): updated scripts to use the new environment's default `JAVA_HOME` (`C:\Program Files\Java\jdk1.8.0_211`) and removes the previously set location.
- [BuildFilesTest issue](https://github.com/GoogleContainerTools/jib/issues/3978#issuecomment-1494919703): switched test to unix-based newline instead of `System.lineSeparator()` in `BuildFilesTest`.
- [UpdateCheckerTest issue](https://github.com/GoogleContainerTools/jib/issues/3978#issuecomment-1496091582): added extra lag time between operations in `UpdateCheckerTest` with before/after timestamp comparison.
> ci: fix kokoro windows build scripts

- jib-core/examples/build.gradle/README.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/JibIntegrationTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStep.java
- jib-core/src/test/java/com/google/cloud/tools/jib/builder/steps/PullBaseImageStepTest.java
Fixes #3958
Since there's no more downcast in PullBaseImageStep of manifest lists actual implementation, use the parent class in the unit tests.
Also update jib-core gradle example to compile with 0.23.0.
I was able to reproduce via a gradle build using jib-core (from: gcr.io/distroless/java17-debian11:nonroot@sha256:5154596f58d81687d66c8302face284198caf65033cde6bf6667c488b21745e6)  and verify the fix works. Though I'm not sure why the issue wasn't caught by the new integration test cases added in #3965 ?
> Fix V22ManifestListTemplate cast when pulling an oci index manifest

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClientResolver.java
This is a fix for #3981. I believe that description on the issue explains the rationale behind this change but I'd be happy to clarify if there are any questions.
the [style guide](https://github.com/GoogleContainerTools/jib/blob/master/STYLE_GUIDE.md).
Fixes #3981 🛠️
> Make `DockerClientResolver#resolve` threadsafe

- jib-core/CHANGELOG.md
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
Updates changelog to prepare for next releases: 
* jib-core 0.24.0
* jib-maven-plugin 3.3.2
* jib-gradle-plugin 3.3.2
> chore: update changelogs to prepare for release

- jib-maven-plugin/kokoro/release_build.sh
This PR adds a workaround to the `jib-maven-plugin` release script related to the Kokoro environment migration:
```
com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest > testPackageGoalsMojo_complexServiceRemoteProfile FAILED
java.lang.AssertionError: expected:<[build]> but was:<[[0.002s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /tmpfs/docker/overlay2/344b91503161185dd904a5615aded79b8e6933f6fa7eb0ecbca3452428eff1f3/merged/sys/fs/cgroup/cpuset., build]>
at org.junit.Assert.fail(Assert.java:89)
```
The additional warning pollutes output in a couple of test assertions where logged contents are verified. It is suppressed in the CI environment with `JAVA_TOOL_OPTIONS: -Xlog:os+container=error`, but this environment …
> chore: update release script for jib-maven-plugin

- examples/dropwizard/pom.xml
- examples/helloworld/build.gradle
- examples/helloworld/pom.xml
- examples/java-agent/build.gradle
- examples/java-agent/pom.xml
- examples/ktor/build.gradle.kts
- examples/micronaut/build.gradle
- examples/multi-module/build.gradle
- examples/multi-module/pom.xml
- examples/spring-boot/build.gradle
- examples/spring-boot/pom.xml
- examples/vertx/build.gradle
- jib-core/CHANGELOG.md
- jib-core/README.md
- jib-core/examples/build.gradle/README.md
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/README.md
Addresses post-release documentation updates in #4006, #4021, #4023.
> chore: update docs and examples after core 0.24.0 and plugins 3.3.2 release

- jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java
- jib-core/src/test/java/com/google/cloud/tools/jib/registry/RegistryAuthenticatorTest.java
Fixes #4032 🛠️
This accepts the Basic auth scheme without realm.
> fix: fix WWW-Authenticate header parsing for Basic authentication

- gradle.properties
Opening this PR to troubleshoot CI errors  on main branch after https://github.com/GoogleContainerTools/jib/pull/3892 - I'm suspecting that the current test suite setup is not compatible with gradle parallel execution, since the errors look like port allocation conflicts: 
```
com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest > classMethod FAILED
java.lang.RuntimeException: Command 'docker run --rm -d -p 5000:5000 --name registry-e0dea1b8-cf48-4b92-8e29-2aecf7a1426c -v /tmpfs/auth:/auth -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd registry:2' failed: docker: Error response from daemon: driver failed programming external connectivity on endpoint registry-e0dea1b8-cf48-4b92-8e29-2aecf7a1426c …
```
> chore: disable gradle parallel build in project properties

- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/BuildTest.java
- jib-cli/src/test/java/com/google/cloud/tools/jib/cli/WarTest.java
Fixes #<4090> 🛠️
This PR is a follow up of the tentative PR https://github.com/GoogleContainerTools/jib/pull/4093, as the previous one is merged.  It addresses the same problem as described in the issue, but in `BuildTest` and `WarTest`, respectively. Same fix applies.
> Follow up: address order permutation in MutuallyExclusiveArgsException

- examples/helloworld/build.gradle
- examples/java-agent/build.gradle
- examples/ktor/build.gradle.kts
- examples/micronaut/build.gradle
- examples/multi-module/build.gradle
- examples/spring-boot/build.gradle
- examples/vertx/build.gradle
- jib-gradle-plugin/CHANGELOG.md
- jib-gradle-plugin/README.md
> docs: update docs for gradle v3.4.0 release

- jib-core/CHANGELOG.md
- jib-core/src/main/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplate.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplateTest.java
- jib-core/src/test/resources/core/json/loadmanifest2.json
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> fix: support parsing manifest JSON containing `LayerSources:` from latest Docker

- build.gradle
- jib-core/CHANGELOG.md
- jib-core/src/integration-test/java/com/google/cloud/tools/jib/api/ReproducibleImageTest.java
- jib-core/src/main/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilder.java
- jib-core/src/test/java/com/google/cloud/tools/jib/image/ReproducibleLayerBuilderTest.java
- jib-core/src/test/java/com/google/cloud/tools/jib/tar/TarExtractorTest.java
- jib-gradle-plugin/CHANGELOG.md
- jib-maven-plugin/CHANGELOG.md
> Update apache-commons to 1.26.0 and set PAX headers to address build reproducibility issue

- .github/ISSUE_TEMPLATE/issue_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Update CONTRIBUTING guidelines

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/CliDockerClient.java
For https://github.com/GoogleContainerTools/jib/issues/4267
Reproducer: https://github.com/mpeddada1/windows_deadlock (note that this reproducer doesn't using `docker` but showcases the same issue observed in https://github.com/GoogleContainerTools/jib/issues/4267). According to the official documentation:
```
Because some native platforms only provide limited buffer size for standard input and output streams, failure to promptly write the input stream or read the output stream of the subprocess may cause the subprocess to block, or even deadlock.
```
> fix: address windows deadlock issue when determining docker environment info

- jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/JarCommandTest.java
This test method was originally introduced to verify the `--from` parameter of the Jib CLI command in https://github.com/GoogleContainerTools/jib/pull/2972. However, this is already being verified by the other test methods in this class (see `testStandardJar_explodedMode_toDocker` for example). 
As part of cleanup for [Container Registry's shutdown](https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown), this PR removes this redundant test.
> [jib cli] chore: remove duplicate test method for verifying --from argument

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/CliDockerClient.java
- jib-gradle-plugin/src/integration-test/resources/gradle/projects/simple/mock-docker.sh
- jib-maven-plugin/src/test/resources/maven/projects/simple/mock-docker.sh
#4311 
1. Fixed gradle and maven integration tests to make mock docker executable output OSType and Architecture. As discovered in https://github.com/GoogleContainerTools/jib/issues/4311#issuecomment-2405793374, Jib ran successfully when the `docker` client was used but was getting stuck indefinitely when a custom docker client was provided through the `jib.dockerClient` feature. 
2. [Improvement] Added timeout to ensure that Jib doesn't indefinitely get stuck when an output from docker info isn't returned, instead we throw an exception with a helpful message.
Verified locally through `./gradlew integrationTest`
> fix: add timeout for docker info read to prevent Jib from getting stuck indefinitely

- jib-core/src/main/java/com/google/cloud/tools/jib/docker/CliDockerClient.java
- jib-core/src/test/java/com/google/cloud/tools/jib/docker/CliDockerClientTest.java
> fix: windows deadlock while executing docker commands (#4267)

- jib-maven-plugin/CHANGELOG.md
- jib-maven-plugin/README.md
- jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java
- jib-maven-plugin/src/test/java/com/google/cloud/tools/jib/maven/JibPluginConfigurationTest.java
> Check Maven user properties with highest precedence when fetching a property value
